apiVersion: v1
kind: Service
metadata:
  name: gardeners-db
  labels:
    app: gardeners-db
  {{- include "bonsai.labels" . | nindent 4 }}
spec:
  type: {{ .Values.gardenersDb.type }}
  selector:
    app: gardeners-db
    {{- include "bonsai.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.gardenersDb.ports | toYaml | nindent 2 }}
