apiVersion: v1
kind: Service
metadata:
  name: grove-db
  labels:
    app: grove-db
  {{- include "bonsai.labels" . | nindent 4 }}
spec:
  type: {{ .Values.groveDb.type }}
  selector:
    app: grove-db
    {{- include "bonsai.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.groveDb.ports | toYaml | nindent 2 }}
