apiVersion: v1
kind: Service
metadata:
  name: tending-db
  labels:
    app-name: tending-db
  {{- include "bonsai.labels" . | nindent 4 }}
spec:
  type: {{ .Values.tendingDb.type }}
  selector:
    app-name: tending-db
    {{- include "bonsai.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.tendingDb.ports | toYaml | nindent 2 }}
