apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tending-data
  labels:
    io.kompose.service: tending-data
  {{- include "bonsai.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.tendingData.storageRequest | quote }}
