firebase:
  ports:
    - name: "9099"
      port: 9099
      targetPort: 9099
    - name: "9199"
      port: 9199
      targetPort: 9199
    - name: "4000"
      port: 4000
      targetPort: 4000
  type: ClusterIP
  image:
    repository: ghcr.io/bharatdwaj3/firebase
    tag: v3
  resources: {}
frontend:
  ports:
    - name: "5114"
      port: 5114
      targetPort: 80
  type: ClusterIP
  image:
    repository: ghcr.io/bharatdwaj3/botany-frontend
    tag: "319b159"
  resources: {}
frontendNginxConfig:
  defaultConf: |-
    server {
        listen 80;
        server_name localhost;
        client_max_body_size 300M;
        root /usr/share/nginx/html;
        index index.html;
        location / {
            try_files $uri $uri/ /index.html;
        }
    }
gardeners:
  ports:
    - name: "4003"
      port: 4003
      targetPort: 4003
  type: ClusterIP
  image:
    repository: ghcr.io/bharatdwaj3/botany-gardeners
    tag: "319b159"
  resources: {}
gardenersDb:
  gardenersDbCtr:
    image:
      repository: postgres
      tag: 15-alpine
  nodeSelector: {}
  ports:
    - name: "7435"
      port: 5432
      targetPort: 5432
  replicas: 1
  tolerations: []
  topologySpreadConstraints: []
  type: ClusterIP
  volumeClaims:
    gardenersData:
      requests:
        storage: 100Mi
  resources: {}
gardenersDbHeadless:
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
grove:
  ports:
    - name: "4001"
      port: 4001
      targetPort: 4001
  type: ClusterIP
  image:
    repository: ghcr.io/bharatdwaj3/botany-grove
    tag: "319b159"
  resources: {}
groveDb:
  groveDbCtr:
    image:
      repository: postgres
      tag: 15-alpine
  nodeSelector: {}
  ports:
    - name: "7433"
      port: 5432
      targetPort: 5432
  replicas: 1
  tolerations: []
  topologySpreadConstraints: []
  type: ClusterIP
  volumeClaims:
    groveData:
      requests:
        storage: 100Mi
  resources: {}
groveDbHeadless:
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
kubernetesClusterDomain: cluster.local
mailhog:
  ports:
    - name: "8025"
      port: 8025
      targetPort: 8025
    - name: "1025"
      port: 1025
      targetPort: 1025
  type: ClusterIP
  resources: {}
marketplace:
  ports:
    - name: "4005"
      port: 4005
      targetPort: 4005
  type: ClusterIP
  image:
    repository: ghcr.io/bharatdwaj3/botany-marketplace
    tag: "319b159"
  resources: {}
marketplaceDb:
  marketplaceDbCtr:
    image:
      repository: postgres
      tag: 15-alpine
  nodeSelector: {}
  ports:
    - name: "7435"
      port: 5432
      targetPort: 5432
  replicas: 1
  tolerations: []
  topologySpreadConstraints: []
  type: ClusterIP
  volumeClaims:
    marketplaceData:
      requests:
        storage: 100Mi
  resources: {}
marketplaceDbHeadless:
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
pvc:
  firebaseData:
    storageRequest: 500Mi
tending:
  ports:
    - name: "4002"
      port: 4002
      targetPort: 4002
  type: ClusterIP
  image:
    repository: ghcr.io/bharatdwaj3/botany-tending
    tag: "319b159"
  resources: {}
tendingDb:
  nodeSelector: {}
  ports:
    - name: "7434"
      port: 5432
      targetPort: 5432
  replicas: 1
  tendingDbCtr:
    image:
      repository: postgres
      tag: 15-alpine
  tolerations: []
  topologySpreadConstraints: []
  type: ClusterIP
  volumeClaims:
    tendingData:
      requests:
        storage: 100Mi
  resources: {}
tendingDbHeadless:
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
visitorServices:
  ports:
    - name: "4004"
      port: 4004
      targetPort: 4004
  type: ClusterIP
  image:
    repository: ghcr.io/bharatdwaj3/botany-visitor-services
    tag: "319b159"
  resources: {}
visitorServicesDb:
  nodeSelector: {}
  ports:
    - name: "7436"
      port: 5432
      targetPort: 5432
  replicas: 1
  tolerations: []
  topologySpreadConstraints: []
  type: ClusterIP
  visitorServicesDbCtr:
    image:
      repository: postgres
      tag: 15-alpine
  volumeClaims:
    visitorServicesData:
      requests:
        storage: 100Mi
  resources: {}
visitorServicesDbHeadless:
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
