apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bonsai
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/Bharatdwaj3/zenBotanica
      targetRevision: main
      path: k8s/services
    - repoURL: https://github.com/Bharatdwaj3/zenBotanica
      targetRevision: main
      path: k8s/exposure
  destination:
    server: https://kubernetes.default.svc
    namespace: bonsai
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
