apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bonsai-observability
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Bharatdwaj3/zenBotanica
    targetRevision: main
    path: infra/helm/bonsai-observability
  destination:
    server: https://kubernetes.default.svc
    namespace: bonsai
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true