apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f observability-compose.yml -o k8s/observability/
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: loki
  name: loki
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: loki
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f observability-compose.yml -o k8s/observability/
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/bonsai-web-application-default: "true"
        io.kompose.service: loki
    spec:
      containers:
        - name: loki-nginx
          image: nginx:latest
          ports:
            - containerPort: 3100
              hostPort: 7010
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /etc/nginx/nginx.conf
              name: loki-config
              subPath: loki-nginx.conf
              readOnly: true
            - mountPath: /etc/nginx/.htpasswd
              name: loki-htpasswd
              subPath: loki-htpasswd
              readOnly: true
        - args:
            - -config.file=/etc/loki/local-config.yml
          image: grafana/loki:latest
          name: bonsai-loki
          ports:
            - containerPort: 3101
              protocol: TCP
          resources: {}
          securityContext:
            runAsUser: 0
          volumeMounts:
            - mountPath: /etc/loki/local-config.yml
              name: loki-config
              subPath: loki-config.yml
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: loki-config
          configMap:
            name: loki-config
            items:
              - key: loki-config.yml
                path: loki-config.yml
              - key: loki-nginx.conf
                path: loki-nginx.conf
        - name: loki-htpasswd
          secret:
            secretName: loki-htpasswd
            items:
              - key: loki-htpasswd
                path: loki-htpasswd
status: {}
