apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f observability-compose.yml -o k8s/observability/
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: prometheus
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: prometheus
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f observability-compose.yml -o k8s/observability/
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/bonsai-web-application-default: "true"
        io.kompose.service: prometheus
    spec:
      containers:
        - args:
            - --config.file=/etc/prometheus/prometheus.yml
            - --storage.tsdb.retention.time=7d
            - --web.config.file=/etc/prometheus/web.yml
          image: prom/prometheus:latest
          name: bonsai-prometheus
          ports:
            - containerPort: 9090
              hostPort: 7090
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /etc/prometheus/prometheus.yml
              name: prometheus-claim0
              subPath: prometheus.yml
            - mountPath: /etc/prometheus/web.yml
              name: prometheus-web-config
              subPath: web.yml
            - mountPath: /prometheus
              name: prometheus-data
      restartPolicy: Always
      volumes:
        - name: prometheus-claim0
          configMap:
            name: prometheus-config
        - name: prometheus-web-config
          configMap:
            name: prometheus-config
            items:
              - key: prometheus-web.yml
                path: web.yml
        - name: prometheus-data
          persistentVolumeClaim:
            claimName: prometheus-data
status: {}
