apiVersion: v1
data:
    ADMIN_EMAIL: ENC[AES256_GCM,data:HzHxlLW4ldMsrJuoVVABkzGjE0IKyq7qlviJsQ==,iv:Osvekv0+5nOYmvZsXe457SjEK3wVSOYFK4mtb5+LzPs=,tag:0KgEWY+LvfDAYRyvt0gqOg==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:gykAoAnY3iB/06Mj,iv:75976CGzqB8lABhyaqxNdVt3Slsa5yR6lOQ097IKFUU=,tag:RcU9hQnbTflWzZHT9YSCIw==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:V90qY+fu1iOITg/Ey1NJzl2Epu8Gl+uxWkS1JwIdwdhXuiJ0wgGFHyrEzywm4jKK8VhWQFr1kwLxcG5QM7k8c4LiZLO7OLL+VrE1NzwDUgx9ISOyDMSENV0TZTUoOllPhrkB1pXSNWnFJn8vbJU3FKBhcE8=,iv:Q4kERpvBZd9X8ew2B6rk5J2yBHo8S+5hpcnr5UjJ290=,tag:EGe+ohrNJf6zXYrIC2+ydg==,type:str]
    FRONTEND_ORIGIN: ENC[AES256_GCM,data:Rjs4yD+r1KLL+WrTG2KcLjupR0ZFsRf5l2jYcA==,iv:SS2ZaHtMDPeSb5J9x5LaahBtAQNuucxv5GH/Q78AdJk=,tag:alrsr39eo1rYTaCqDWeOtA==,type:str]
    INTERNAL_SERVICE_SECRET: ENC[AES256_GCM,data:6dYL3c+2XkBZYttlBkZDNIrOuNSIrfyt2oATiQ==,iv:VpuDOyvPlG/FGaJiAML/0Abzz6TpUMbJfVVM4VAz/xM=,tag:ZWvmI3kpSedhPLEp16rJ/Q==,type:str]
    JWT_ACC_EXPIRES_IN: ENC[AES256_GCM,data:nQWp1w==,iv:rPSopq3SxxVw2eLN4tklSZkq585fDelOz8z9H4o2KcE=,tag:URrHGRYG0MKVgvofgH26hA==,type:str]
    JWT_ACC_SECRECT: ENC[AES256_GCM,data:8BN141eagdCgAQmH,iv:unzaOm5BrpDyFaJ2J8/RnazDIkzD2Q5ySwWByS/6PYA=,tag:7W591dHrK3M5L3yLG3GbDg==,type:str]
    JWT_REF_EXPIRES_IN: ENC[AES256_GCM,data:5hxh6g==,iv:0i3lspF1llftNbT0uGmAXu3I9WuJK87ArDTmqOnA4Nk=,tag:3kPSmz7Xv7ppwxcMLFKVTQ==,type:str]
    JWT_REF_SECRECT: ENC[AES256_GCM,data:SV1HVyngdEItiXNW,iv:zIY9c6qwR5oz0kbZPSMvcRGRItXIzzJwRwcZGsAkNqE=,tag:ruD67k3GGEjlkKy63gSJkQ==,type:str]
    PORT: ENC[AES256_GCM,data:y52cjhmZrdI=,iv:o8fG6ylj1arwVWzecUogPazmBS6DoubOLDN3f8N0GMc=,tag:OTPt5Gh5pw16lur2gDzSQw==,type:str]
    PgSql_Database: ENC[AES256_GCM,data:B1ED0InSazPtwjOOD/8F3Q==,iv:1OPkWCNAZOqZsnVNs+3ZPwmixrKSnPuKBt6AdPoK2b0=,tag:L8tDW5uiv6Ourz+fgz1yMw==,type:str]
    PgSql_Password: ENC[AES256_GCM,data:EQVgAPOhGjg2R8gYVphjaepwHfg=,iv:lw3+LHiaRtzf8O/TMlK5Wb65wEwtD286D3Wses+ZKSU=,tag:E9hSSXQoxAfbnt7i326/Ug==,type:str]
    PgSql_User: ENC[AES256_GCM,data:tSBtlDfrTt68iaRCbBxZx5B0oO0=,iv:k6m5CnV258YzJS90UzeAo4iUOAsdKCmJcLzyzegaXDM=,tag:Xy/tBwOsu11ApTX4Of+c5w==,type:str]
kind: Secret
metadata:
    name: gardeners-secrets
    namespace: bonsai-dev
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g2lray3jp4plrwd6x2uzhk2gq563kcshuc0xy962e4kzkg9789gsdrlenq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2Tjc1TEV4Q2U2UHpGMXU2
            RVUyOVJnbUx5Vm1LTVNQQTYwemNZU3g5dlJ3CjF6RFgxT25Pb0Z6SklodldmRXdn
            cXRmQjdBR1ZpUHVmTW03dUNqYXFrSEUKLS0tIGFnUll4NVYzMUdrMnZJNzJuQTN6
            RmNoOUxLRkM3T3BkUW82cDFTc1dBMEEKvgxkvWwKXcxOD+IIBmxytWkh04BSkUn5
            ++WmY1HyAfZJ/XY9gh0ypJKALOIYZGZu/8J5wqaES2STbg6Jb5Rcjg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-06T14:10:52Z"
    mac: ENC[AES256_GCM,data:1UyN9yGed81ZqDAuniJWZd0qmFsW+D9a8CJrS4t1RFJDDtiISaSa3HGp0NhZb38LhtfCeUAGkM3rNi811762RX5pRMyq3ADT+8VThpYIBy5Dpxx9Hl3PI0FPuxOhffOMqsE56rM7g7Seb+xVjVeP4zXf5PskquSwRd9afvLNE7I=,iv:BVvgBXABhPQGfGTlzhOJkeG6n6iiDDYxFliwCRvPbo0=,tag:THb8MIhikxonv7nlLPgClw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
