apiVersion: v1
data:
    ADMIN_EMAIL: ENC[AES256_GCM,data:B8/pomO4isaQIHDIS86EeqHLbRfpggsJLkAglQ==,iv:GmWk6heHUN3fKRA1D/XFbEcq78Su/VvczCgKYwlpR60=,tag:2Ldz55c6iHuMfaXLz4Kl3g==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:t7wDKi/ij6yS9tL7,iv:h7IVPejpYbsSp1gpKWe//wyAstRIV/IKkUtC9Muuf5M=,tag:Sj3jqYtAm4ZEZU0J8vv5pw==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:grn1TYPFs8r+3sXay57KshPSYZui3aI7L3Ef04bg4lgjrXkcG8PQ6DjyHouddiUzkBRcD2jD4hyg7QpAEwyGTQx3FTfpB3VjsIZA6DZdi3zJBN6tzQqnhgXLh00V7LrWZo0p/sXksR24FmtB6NTlA90ajuw=,iv:ty3G3rFr6EesN/H2oNg9dDw7t3r/gfndOV6yDpRKWT0=,tag:Oxyc7ERysH/CJv7budeAPQ==,type:str]
    FRONTEND_ORIGIN: ENC[AES256_GCM,data:flrLSWMLN92lKLFMnlREY+NxGJT7N9r0DzAfSQ==,iv:JEQJspbLSL+n8Eq9lnqSPbeHKKGZPIMZrg5bt+spQeU=,tag:flR+l1TgOCBdy4dHCXHgfQ==,type:str]
    INTERNAL_SERVICE_SECRET: ENC[AES256_GCM,data:N9boaKLtpzLGs0fss+zG+563kviDXam2sgqPsw==,iv:6LkKOkHoORK5TVjKQlxo971tAsN234LUg1E0gy//GZI=,tag:usOy1DMejwacC7+GGN2ucA==,type:str]
    JWT_ACC_EXPIRES_IN: ENC[AES256_GCM,data:/meJqg==,iv:Y9mxTbawSKigxUfF/opFy5MxdI2W/3YnORbfTuBZ0iM=,tag:3hL6iw08fyE8GtHeoudw1Q==,type:str]
    JWT_ACC_SECRECT: ENC[AES256_GCM,data:P3ktkO4HJxaj8kNg,iv:hiTpSyWs0uLrGXXmD6pdPVfd79E0ClgVySIGxGO4Ahs=,tag:vVZQFdhNc9dSZ6PQYp73Nw==,type:str]
    JWT_REF_EXPIRES_IN: ENC[AES256_GCM,data:PYOI9A==,iv:gGUQWy67fnIR5KCiJVz6yKwXuQDm9X2UMTcbb+jl5yg=,tag:hnJl5+RbdhsABLe+QwoPfQ==,type:str]
    JWT_REF_SECRECT: ENC[AES256_GCM,data:ifANXR9V/EZEnvrk,iv:0WCLXlcD2v6YgvOf/yEO42KmzlYfP7a8P7BCm9osmec=,tag:8vx6JhhtDsrYCv0xjAMYqw==,type:str]
    PORT: ENC[AES256_GCM,data:xuKsbzCAaec=,iv:lh3VsLrBdKtG8nFQL5nJKbXA+s2a529sOy7eLvX99pg=,tag:B5BeeWwgzLC5FEb3HYQSRw==,type:str]
    PgSql_Database: ENC[AES256_GCM,data:xYIpBHHnWwY+eCcZiCPjfA==,iv:fLfV81J1JS6NMtZUQj4Lw1AtFxX4bKTRIn7UIglyOsU=,tag:CIfEzV3hDdMFm6kTs6YjtQ==,type:str]
    PgSql_Password: ENC[AES256_GCM,data:L1RMZsp2o67w/X1wX+emtpY4ss4=,iv:W0IN2Un3zeqIQlgK8+63Hisw/l4kf64RCCAer0BaekE=,tag:8n9ZdG/CWyVBN02A6WcZvA==,type:str]
    PgSql_User: ENC[AES256_GCM,data:EdHARRgf76ppch4+PvTDYk0aE4U=,iv:djjFA6xWt+s1c4oPFV/+D4heXd7ZddH45B5/UGzzOf0=,tag:ufeKYJgfU1yoFBrZ1/c+0Q==,type:str]
kind: Secret
metadata:
    name: gardeners-secrets
    namespace: bonsai-dev
    ownerReferences:
        - apiVersion: bitnami.com/v1alpha1
          controller: true
          kind: SealedSecret
          name: gardeners-secrets
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g2lray3jp4plrwd6x2uzhk2gq563kcshuc0xy962e4kzkg9789gsdrlenq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTazdTQ28vSU5sQTdrb09S
            Nm13dEJ4MWRNZ1hFdkVlcTkyYkoxQnB5NW1rCmxQa1dWakxlVmN5OGdWWGNJdkx6
            Q0gyWFM0emd2VEdkY21aZUgzMFVsZzQKLS0tIFgyRC9xZGtTWFdURDdxWHkxSWdU
            bjZPc3NMYzJUaFoyR1ppaDk3QUlsK3cKCJhcmLEic9klw3nbDMvfbfMtb3OKUiht
            B6iACYWrP6DKUAPUvUv7sM1m71Rk8+JN8BvaZ6VtXSXn+B92x/OmDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-06T10:42:25Z"
    mac: ENC[AES256_GCM,data:zlXi4Sshs6qDg/nb7XE0hoULjtmXkYkxnkBE6oo72gVUp1ZDjvR9ybhreAhubarzF5P1Wo5e8ixsyYr6Ehx71D9yefgQZhWW+AP6cvHU0fFarACUYcdnkHiQLMlypzpDvBOk9l+CVJ749xulkPiKxr4r7zO42SffgW00Z7tWL+c=,iv:uuWOnQDhoxJdTxhBLtFZ5jGuCDMWy9QyN+TT+zQOv24=,tag:mnr5bn4mhljIrGIig2yZ/w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
