apiVersion: ENC[AES256_GCM,data:JoU=,iv:4qp5RDGE/CBJzFB/ucZBRGRsVoFQn8jhZAxp9hVVJWA=,tag:RVpE2KKA3uFjjM+89BGvfw==,type:str]
data:
    ADMIN_EMAIL: ENC[AES256_GCM,data:eaFvy96cuVcUXe4ZAv4uXMRX7nMfadHvam6MBw==,iv:qRJza2bczOkCorxEVJ13p2PLLTadyJFzdmO3ai4Njug=,tag:j8KvGH1u1oB49eAoO+t3jw==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:LP8rMTzmsMB5QKwV,iv:0o0BZvjrScQACA7uPfVZBl8WyJ9Z28WsH1nzr4U9LMQ=,tag:g1ZekrY4RqYtYphmlMi4yA==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:PEaDRmyQ/Ot4aQ8pgXZbP3OxpIrEDdw3UbV+GFmzjrkES1biiw0ZIq3T1bnTPOc4cJ3ZNQsrYIBa+bJ7PipES58n3UCP6ByvTIl87WALJyUh1+tlQR/XvY8ladRkpkyf1KJ8/2PsPHwQilTdFhoGRQAWrdU=,iv:DUD64VV/ck9ulzaOv1efhTdr4hHaJ3t3vdtuCV5sCfM=,tag:kAERfBDwHtnS+ClWQdW9RA==,type:str]
    FRONTEND_ORIGIN: ENC[AES256_GCM,data:c7O9ouLmk7xUu7czsgDAPPOspXSVIzG4k0ACxg==,iv:3f0sn0nZRrHNgetlAuoHX8/x168LdBoacYaIRIZ77rQ=,tag:bWAZXPiPN2lapZtu+r0Fmg==,type:str]
    INTERNAL_SERVICE_SECRET: ENC[AES256_GCM,data:0vN+obEkNlgf0afM0KXvXoIeHRNuAbrRKFH15Q==,iv:Vi9+jRLFRcuULG3ktnK2UFPR8ONUDmYIXPJlB8cafwk=,tag:PLVh3PcBCGG1x6gPvtqE+g==,type:str]
    JWT_ACC_EXPIRES_IN: ENC[AES256_GCM,data:5ZUXvQ==,iv:1EWNJxQUi5dtfWBtBrAlln0DiFxKEthbN+fO3YUswWM=,tag:RHTrzAykrA6S6nHbVZj/nw==,type:str]
    JWT_ACC_SECRECT: ENC[AES256_GCM,data:CYpmr4GShOihJIwZ,iv:kfGHcS7zQ6/TRyr0hv0IPvyRjDcY5pZh4UQ2dZmZoew=,tag:CeF7FjXzoFLhQyJMydYNpA==,type:str]
    JWT_REF_EXPIRES_IN: ENC[AES256_GCM,data:u4dMcQ==,iv:Vwact1WGgBj9jNGAbqIy8mTSeL/NSzbI2uEHGkQ/KC8=,tag:Zs+fTr9Sa/QT+wYkFF0wdQ==,type:str]
    JWT_REF_SECRECT: ENC[AES256_GCM,data:nKKV9tBMJuFet7zq,iv:0HK5DX3jv9mTjgDycYVGq/VPKrk7VF38nnXV9h4MVa8=,tag:IDQ54oco+y7NjIkIRl26tQ==,type:str]
    PORT: ENC[AES256_GCM,data:5HflCFVyksU=,iv:F7AaPbTMHERDvn3czfLKqw0GL4RPMiCF+G0Y1VZCLj4=,tag:oMcS7ATo7Lon17A1i89O1Q==,type:str]
    PgSql_Database: ENC[AES256_GCM,data:q6zdOaS1RPEpd/WU+s3VSA==,iv:fQfAbpvMUgUXYeFnPjnILUSOZuaOXlEeQgKujU9h5zM=,tag:JoCz1cHLkmBqhSmH2bFAAQ==,type:str]
    PgSql_Password: ENC[AES256_GCM,data:+YvoMDQ0fisJsi1N0mK7Bi34Kns=,iv:83g4Tg/7Sx27gY5ZPEfMkHrzkguJ8Cjorq8jMr6iiBs=,tag:gKh1OmashKtF1De2Zl20Cw==,type:str]
    PgSql_User: ENC[AES256_GCM,data:jXD3IpiNEINCPXAcuJKnZiRiKQ0=,iv:deRkL5+HbH/TGtHT69jvPI/TnamfA6YN7hjxzJ+bL6c=,tag:NfeCcJitA2FxVSEp7gMUBg==,type:str]
kind: ENC[AES256_GCM,data:05/7bxbD,iv:wV73Zzrrv/rqe0HdJSYkg30OSK/ZnqEHlbATy9cmBV0=,tag:LoI1VbYEE0IsdyvAtr0eZg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:gHcsaRIzj0EBGJdGSX2w0Bs=,iv:J6EspIDqJW4BWAxw3wFGPfsbW5gS2/OMHbefaaPEcQ8=,tag:obqZtivmvolk0zZTZyiXdw==,type:str]
    namespace: ENC[AES256_GCM,data:0gUftDh5ZaR4xi8=,iv:P2ZPdF6HOXOcQWDl+gCYRTGBCUXdNwBi5UnkpwMm9wQ=,tag:WJYbDgqiSIYb27qSnAu9Ow==,type:str]
type: ENC[AES256_GCM,data:LFq072Z+,iv:Usz8Cx+/DH4MF5yIwvD3DD9N5qnAOfivAFyEeysobXQ=,tag:PJXzOkofCOtXaIOyl1FrCA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g2lray3jp4plrwd6x2uzhk2gq563kcshuc0xy962e4kzkg9789gsdrlenq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBeFZuVzV6SUZ5VmVvMktK
            Y0FRMXEwTDFSdzZxWkVDSVZpcFN4Y2ZzYnhnCi9YbmVuVUN2TDZSdGZXSHZhQ1pn
            R1YvdmtsVmFYR3lERUZFS2VpRWhFZWcKLS0tIDVaR2hBaTh1ekhqWk5EOTFaSUs4
            bVNIYlIwMjRUVmxBVkhZMjlmUGtUS1kK31GJHbcrmSU1n4jDAprMLwfhwyKcu8da
            FUreMPmzKnhkwK50ThKkpWmLQIN91AeihnO0fal6ZSiiPxjYXBFhJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-04T17:58:18Z"
    mac: ENC[AES256_GCM,data:lRgH1CxM1kvH3TnRyiceUsYxa+tyOcFxoqdetpF8Tfr6KTjRel4ypgEjtHx4omsHzRx45rfNfNI6yvLpD8fl5LoA7t/zzU9i7hU1vKpPwlH4ckImNkv/i4Ebzl5wSP/GH6eHOJIbK4tOJReQ8vgjwnaWZbSD6cYmpU+YXjq1sZc=,iv:tSepj/erXLxsO9yttaVgRsWQzQ4EcMAfKgKBl/jCGhA=,tag:h7P7lpfKg1ZgH7tMBeNrMg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
