apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:x6x35ah0fdPxHyxEmqQFyn3Fw3vCjnO+gYtNIW7mHgHRAJhMfSl2frxAyVqrZgDubpJ8M1GFaubEplfIoU+QCh0fDg5wKEw9AwuzdvFriYb6S0QoPdrQf7OLIWHGpdPmIQD+IvpMpyXnt0dKtmaxHsJdydppwOwj2X5JRsxtD748torYBYEUcc0+yFQafK1sqcR40OM+6KTK7iDii9giB6r7XQ35YsDtm4ZKmeLGRehkMu6BpF/VKQtqit9PAL95uhjMr6Xv7iWXYNgygQUz8ggWxdxIZX/K7bioGREoF+8mDgjYyryWgLjPRpn58cxn/HN9ZDW/rZHU0bdL9fO/uLkueEmy2ZmMhMpSQrGrrnNevz6JzwLK3/4dwICSNMdstWNE7Y/qKjRCONwbsmGzfklKYLS1x9REmpsoRA==,iv:w+GOxLccJhOcWy1Rehyy7dR4xXfNE9ac0tlC8EEENvg=,tag:1HjyCFtD7FK6oNjslxy7iw==,type:str]
kind: Secret
metadata:
    name: ghcr-secret
    namespace: bonsai-dev
type: kubernetes.io/dockerconfigjson
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g2lray3jp4plrwd6x2uzhk2gq563kcshuc0xy962e4kzkg9789gsdrlenq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzSmw1TVByaWVWUzR4a3ND
            ZU1CYU9WT0NzT0d0ekdHWWJuYTdrT2tNZ2xvCnV2bVlYYW13bUp5bzdidW9UVGdN
            QmlKeEJjNmYzdS9uM0sxdTNySzU0UzAKLS0tIE0vQ0g1RzczWlBVSVlGZVpuNW4r
            ZE01WlRFYjdCeGFYaXFTV1M1Sm1vNmMKqu6aazboyxu9Ve0s3lu8My0T551VAf68
            Xr7nqo3UaQGbmGU2HWfgYjIYH7P4t3A810Q4b+eoMN95Z83g5Y4rzw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-06T14:10:53Z"
    mac: ENC[AES256_GCM,data:vRoP5inIO33k0LuCPt0DEsRnnmVr3yjKQDTOZKocp83lLWFwicP3n2F+SYHH/1w1IHHfTzndm2UnOusWfjaW85r9XdWOqJAz77tLEFGuK960bxzJyc5UINalldBZ3r1zkVB3BBGeOdkW3EWJwLQOsq7IbfWOs89z3/CqZKlxf3k=,iv:J/N5hJgzZsknY4Orb94HaJUMBvcwyZtDUUwSNFANEg4=,tag:xo3WxAJefuiTkCI8QdzC7w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
