apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:QbXBSflQNjKRafdlOYA4CztYoOZ28guy0m/FG0hDvtaDuHhKIAeuuCcNNUkuLveti6EiaBVfc+jAFVPwD/L6aMMC3WcVH+GwfBfeS6jxjI6aHUPgkT9INEQRGmBhS1ZYhd8+Et+2PPQ73cNEj18qSgVmherGhmPgaUP1qopCbaKUM+/7kt8mUSAnCSsMdkUmaO6VLmb1z1FEn/YdGoJN5fyKO3fD9Womf42CXbwdQN1ZEAqHk7TO/l1S3R3Y7KdtYyjfSZGVah2wQrB08kknf6hIUhV21AtP6A2m1dpaBV1WuBCYHrpZYPwaWXVT1SZqItEYJIqHhBRvMwA1LSp/oaSDZOBgIvq1PIHWpvirEHuC8FYH/28vxfc2yZAsPsO2qYZq7iGVQDWrVxvRdHcKpf00C5veJlB0LR3R3g==,iv:orA2orOUFo38XzBRmEDHMQU96pjLFRZJUxace/xoY1A=,tag:wQPqFEAwNbENNB0+Ebxwmw==,type:str]
kind: Secret
metadata:
    creationTimestamp: "2026-09-29T04:02:36Z"
    name: ghcr-secret
    namespace: bonsai-dev
    ownerReferences:
        - apiVersion: bitnami.com/v1alpha1
          controller: true
          kind: SealedSecret
          name: ghcr-secret
          uid: 2a7b65f7-c578-4b83-8b82-1e1c350e371e
    resourceVersion: "1065001"
    uid: c6d94cc0-85dd-4820-9cfc-d27987a006e0
type: kubernetes.io/dockerconfigjson
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g2lray3jp4plrwd6x2uzhk2gq563kcshuc0xy962e4kzkg9789gsdrlenq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3aHFIMFg1OW11M2NaNENt
            bEc5TDhGM2pRejZhWmc1TzVZaUdEZk9LazI0CnVHQmlubVlEclV5dXFNUEMwaWVv
            cmhCTURNZ3MyOERLV3d1RGg0dEEwck0KLS0tIEN4bWttM1JNdmw1WWtPT095ZVF3
            WkJ6RTF4QjQ2SHVrbUNUQ3g5SzJYeUUK7MdV+TNIdEk2vlMV6MDWLYxlFyIQqO9F
            f/Skg0rwiXC8scMHtodQeBZy2seDyWytaX26LSoVJohyC7xzpe9Qnw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-06T10:19:14Z"
    mac: ENC[AES256_GCM,data:LnCS8fgvSsQw/YQZQLh1M0owEP3+/DCf/kAiNS/3uj1ZVbRmrWxM1aeuBotQ90vx0cnwUkFG20E10CB+UIU40FwKlAhsyvU2hJ0pGLWsnYFvrPVDcKzCEjfk+n3rSsivApLBZIDL81A/cGANWAEedSxcuUmp+2/rPPp/hGk8T50=,iv:elOfgXkqQ7FhiCJQUe2Vas+dBKlgmZGszr0Ry0SJaBg=,tag:t3j0ySgrtqLYmAB1tKxYUA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
