apiVersion: ENC[AES256_GCM,data:Ybc=,iv:C7U5GtrbHAM3lt38kgJheTCUAIR9edEGT0rCGIIR9Mg=,tag:64TBo9X69FiEci0J5ko9pg==,type:str]
data:
    DATABASE_URL: ENC[AES256_GCM,data:shjJMLQXjIQbwbYNdT0zClGf0Bz42mG+9DApFDkH5MbKCVhpQUIOkg6qt/wwmDoyz6fCz+rbay9f18gnVFSuiQ0k5fvmeC/zamSDjyheBxcGFLaCFWltVzFNZDzy49dkK7x7mQ==,iv:n5df1AydRXkn5UNlijVFqI0vy8zZSczxfjiPJOvDaN4=,tag:2fqqU8xk/2qwqHL5Qi4ccg==,type:str]
    FRONTEND_ORIGIN: ENC[AES256_GCM,data:lii+IUDThBwNLCgE/62ifRkUykfdPThW1D/RWA==,iv:lICxKSLUNOG3usUMk0VUlxXjfLzdtlFlhlHb4WU6UIc=,tag:aPIEaFB1Mm2H429Z5Apm3g==,type:str]
    Fbase_project_id: ENC[AES256_GCM,data:KoDuM1WgDAxRoL4Xyxu61g==,iv:fLzRAtE1YGWaIq317Wx92/r2srrOyUQDPbkTNCDesdY=,tag:aTJEKmKv5EsfzeSoXllh1w==,type:str]
    GARDENERS_SERVICE_URL: ENC[AES256_GCM,data:k3owZ4AMtqDz9dHl0CbNtdYjBB7FXJW6Bg5aaw==,iv:d2ZKoYeqPNEjyOmlWHPatrKyCj8BXYACAjXiJQWSzWI=,tag:zrf2zp6kuc/QrIAA/cJ5Tg==,type:str]
    INTERNAL_SERVICE_SECRET: ENC[AES256_GCM,data:VXKGvyEDenJbh+5qX2xibJo0IeWeJMpIb6WDjQ==,iv:GPl/FSCq1hHQWKO7YbPP97rJSWU8wWclfQVKA4WBGm8=,tag:n+65SYMnk0OhDvIgkPVbMw==,type:str]
    JWT_ACC_SECRECT: ENC[AES256_GCM,data:1laJ+8siwYP0hV0E,iv:z1obxzS330uaT+nZbf2+B1m0eU9UKLyq2B9uUn/JQwU=,tag:Q0UXuPTjojAmFD5IMpDxLQ==,type:str]
    NODE_ENV: ENC[AES256_GCM,data:u3gRhaIYydl/PC8UDyLIig==,iv:nowUj0U5eqghkapVxY/lybZpONSLYz+zgE50qxFF7PE=,tag:dA3HPHRQRNh9C/EyQi07BQ==,type:str]
    PORT: ENC[AES256_GCM,data:W7fFxueFlEU=,iv:n4lY28aLCHYXHkjDuRE4kQL67Ld9teJVzcGy1OvC6iU=,tag:oX/CiBxGdfr558XKKfRgZg==,type:str]
    PgSql_Database: ENC[AES256_GCM,data:e1x6xCXQbscN991c,iv:weolrttYVR9vKYkmmZRh+5zh9Ob+16qaYUYr7WRG54A=,tag:k8XRgCbm0QfcNx8aaoal2w==,type:str]
    PgSql_Password: ENC[AES256_GCM,data:W0RBVZHjvXs1puR34/00jw==,iv:1tBLR9oSjB5w9Rl6oOfPbKDyUjcie9YLSBc1GH4Angs=,tag:XSL4soUKH+Jvww5HtDEAxQ==,type:str]
    PgSql_User: ENC[AES256_GCM,data:1o6N4ce+AnB1f4fempUV1Q==,iv:d2Er1oNifG6jKdzUNGDaXeADqKgJpKUfaFt+WfWudww=,tag:0RhUkdxf/edeQVGsplAfow==,type:str]
    TENDING_SERVICE_URL: ENC[AES256_GCM,data:cWu12etdzvt4AwiP3OI1rFtgY0DBHoexF+DCfw==,iv:cvcSaw2cXqKqaY1mZyLuicmMM0ZkTsB+fVSWH4uGkSg=,tag:QY/6mfcPBveXHgEF3IsxQw==,type:str]
kind: ENC[AES256_GCM,data:d3HTETOY,iv:WRGCVMlHEa8ttd4Dd0zda+Wt9m6mxzsp/yX0PRLKSlY=,tag:vAuRiBY0V2Yre05KuUY/VQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:XlcK4NA6UaqVHHN74g==,iv:NTcN4BvdGjb+yUhHgomFpyCHjsGYIfE/FADNCZ3Y6ks=,tag:liC7j87VYco+yA8w1dHrXQ==,type:str]
    namespace: ENC[AES256_GCM,data:auHKETP1xecVRJg=,iv:Bj0mhmCdZJKIGsHjE29FA+400fvy7lptYyZ0b5ysbmQ=,tag:oZTP7dD64pgXd3IJA98/hg==,type:str]
type: ENC[AES256_GCM,data:/47POLCh,iv:IiQu/8CYfdYy7/XXD5K0zQDron6Z6Ng99v03MHZ0MWs=,tag:SIraGMSMizRiA7v8K6o7iQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g2lray3jp4plrwd6x2uzhk2gq563kcshuc0xy962e4kzkg9789gsdrlenq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArQUFScGpDNU5TQ1NEU0RB
            Y3N5UW10QjN1dUtRZWw0RlpWbWRUUXBnUzFzCnJHclRRTWVqZGFhNlIxa0svcWp4
            SjBGUjRXL1FlMjYvNzIzTGRtTnE4Vk0KLS0tIGJrTXFzOTA0L0JBckkraU16N1Ry
            RnNJeUlHSnVGUEdkNE1sUjA4ZFZnc0EKjX77hoDqSgPdBJNiF54jQvN6JQcEJ1s5
            Y52OojLLT5lKqdpLS1GEwwg8wC0esotVvSORHSfetWi/vKLSkmnfYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-04T17:58:18Z"
    mac: ENC[AES256_GCM,data:aeIKhqb7SotK/gJBL1d+xxYne/73TlzO/oZb3kFG+yZYWvRwEqin6s68XDc0uhWk0F2kKRaxF1RkwarB8lPbBQhV05Pibw++f4uESMPa2UtZWQJgJsXd6PukCo6DA032eJd7mQDRlPRC2UA+2xTxrjtowN0q0gOiGxzi/js8j2k=,iv:0ZQBYzoMnzTIfuVrPpBf+Sdk8PmyIB4rPOTF7uVmbqI=,tag:wKwiWYKhaPGkMFkv0XlYVQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
