apiVersion: v1
data:
    DATABASE_URL: ENC[AES256_GCM,data:9I0XZIspXwqWvXYMm/y/YYODRuJ7L/ycwVZPiRDLxyrCWgVMHhgA/1STnGvtgKLYjbuHL5xFBfSWO9bsz06/V8nOPgAznyMqua25/ZFQKMYp71SprnLte52UHnQcuE0NUc0s0A==,iv:DI+kiG7QRJFKHVoGpBUBVDZCwA8f6+A8wKK6+Nn1vWQ=,tag:RJWpPnDErVYZ0C260AjrYA==,type:str]
    FRONTEND_ORIGIN: ENC[AES256_GCM,data:RNb+QiH3TDjQeHEKc6UF076ObjuSr3o97d7w5w==,iv:wDc6/6GPH2IHB5vf+zC5tX9dTmou5eJy7HFW/UibHpU=,tag:e6YPbB0ilsxHA4uKxZ1A+Q==,type:str]
    Fbase_project_id: ENC[AES256_GCM,data:RvkEPUngqwbVEwlfSP0UuQ==,iv:Lz7O3Dp64hXCpaB0hlkcPSBCmvcHs8NryppykVebdBw=,tag:UjIi6s5QirHA8Io1H0Q4eQ==,type:str]
    GARDENERS_SERVICE_URL: ENC[AES256_GCM,data:HapiHCsWSf2v9blsybB1Vstfn8WQCwJtk3Vxgg==,iv:gEnZ92SrIflPHdvOk0PcJp/6Jb3GGrIqqg1e9FJvAWs=,tag:swptpg8Xs8jPQB+yrtIRpA==,type:str]
    INTERNAL_SERVICE_SECRET: ENC[AES256_GCM,data:EjNGn1lcLSGMboZ8doT038ajwnlHlWcuqMrnzQ==,iv:inCJxeW9SLyHusDCDBFEenPXJdaOcwZWa/gTq8RWoLY=,tag:aUJ9J/oPPzJgApkmgmWLcw==,type:str]
    JWT_ACC_SECRECT: ENC[AES256_GCM,data:IhnJY+qqbc5bJc/I,iv:k38jzmfUl+74SECooCu3ItrxpR+fFWkBbi88p8/hWkI=,tag:HSYl3dCg660dnrQsJgkXQw==,type:str]
    NODE_ENV: ENC[AES256_GCM,data:qucK7UlOYqBfGNkwOl4uvw==,iv:eB7+/ksFD9lQILfxAuAmp78yztGx2TmoeJrkUmdt6sk=,tag:duYgkDJCpUs8SsK6iP+yiQ==,type:str]
    PORT: ENC[AES256_GCM,data:g+pluBEnxOQ=,iv:Xx5aAUCn56LljsiKSfPtJ3cyffb+OtmZRbuOF6Bvc6o=,tag:5nJhJqZoOZ4c2aV9y7yvGw==,type:str]
    PgSql_Database: ENC[AES256_GCM,data:mkqau6wqDxKN/bjX,iv:cuN51AHrJaKcwwl1aL+Z09yfteoWuln6CR6l0elE2BY=,tag:COgOE/xETOWrre4Kg978FA==,type:str]
    PgSql_Password: ENC[AES256_GCM,data:koZrNthMnub4SFQ8o67JYQ==,iv:gXmNhJAS91tkCqTcCtRRhstkanehSqi8gof7a1HeL6o=,tag:Dfk7GySAfjZOQw1yLrJc4g==,type:str]
    PgSql_User: ENC[AES256_GCM,data:zOGpPoWQ8zEVjJzRRH4G/A==,iv:GF4FjzjRK8Q78gEZ6XKoKiPLiYunDLFmN6UAnj7IS60=,tag:NdMsWgnijw/ZCP4UR7pjGA==,type:str]
    TENDING_SERVICE_URL: ENC[AES256_GCM,data:515BC6rKVxtIclDziWUKKdTDZEC2Nc7EYCZIkw==,iv:GUT1gRcF7socXh48kYGUWTdzwd5KIvisMeIMeDnpJxg=,tag:5z60yAT0ruTmesLcdt+nQQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: "2026-09-29T04:02:36Z"
    name: grove-secrets
    namespace: bonsai-dev
    ownerReferences:
        - apiVersion: bitnami.com/v1alpha1
          controller: true
          kind: SealedSecret
          name: grove-secrets
          uid: abce2346-707b-4f5c-aec6-4ee371e6cac7
    resourceVersion: "1065004"
    uid: 6be90e43-4127-4268-b812-f93af146b18e
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g2lray3jp4plrwd6x2uzhk2gq563kcshuc0xy962e4kzkg9789gsdrlenq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0MHpFS3c3VElFVk9hZkgr
            SDNhQ1puS3c1N1hFZ2xpMzg2aDcvNVhXQWdFCm9Ba1E4eXlhdngyNEE2cTlFZHJG
            ZG1CVisyeTRsYzdkMU5HeUZOMDR2ZUUKLS0tIDFTQnl4KzZ1NnJXbnJiRlVLQnRZ
            b2RGREgwRmRBSmZUNHh1TU4weWp1S2MKZT+6P2lT/Rb1gIKteXVCP1K3WdspB/Kj
            sM50m8gOCARl9ffbNNSJi/WE6uez5vwqKkTl4w0anj9MYK5KzkUJ8w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-06T10:19:14Z"
    mac: ENC[AES256_GCM,data:YOC/VUx/t71zuzKv0IkrOxIPFnO1eu+HLfOPnZpK0MxZAD8VlZxOLLr5BJA5umclRt5auEnb2S47TUlXZTKttZrrxsB/PGm4FE9ORSXNWhDvY8pvQa3HrUwLfJYOMMulwzX2g4IHw4CmHjlNs7SlAdTKnxJftqjs7BhrFhdnEiM=,iv:t3H4RTwEf1DPPlbxPOwG8vt8/3dOnnX8tEQOYxMlhhY=,tag:8KHNiKleZmjulMaafkBdzg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
