apiVersion: v1
data:
    DATABASE_URL: ENC[AES256_GCM,data:BVaPIsqzxpb3FAl5b5qH8BLgDXQbKB8NKMNaE25Le5hdlUtAPhBGbpwNmpZjrpxwUsh+uUA9cZMcCxZUp/rFzVkUuy1lF0QhZY7gE6sjQ7yo1rBXTbvDedEDvWWpkZtozOfXdA==,iv:NA5YpOa1YmTpCTyCDR0zOw5CGefWH9OklrqqgFA0eso=,tag:N6e4EGkIS94evrwzrXhmlQ==,type:str]
    FRONTEND_ORIGIN: ENC[AES256_GCM,data:9BNVFW+OlLfuc0S5WIDSNQmdTblbaisFrRGgEA==,iv:z5okdCBWocEyGuvKOWkUFsv76NMlwIGI0Cpkv5rtP0A=,tag:vXTyQcIFrVnx/ZMQsGyhOw==,type:str]
    Fbase_project_id: ENC[AES256_GCM,data:8VSVfBw+HPVpYXqHex25VQ==,iv:iG/8XoWilAQrhBfoZv6dCbYQ1eqDOZyQjmJalHCJUJA=,tag:2rOHuM/I7Sf42QhqLAhZIg==,type:str]
    GARDENERS_SERVICE_URL: ENC[AES256_GCM,data:ct8QILLqqpY/mdjNVISAiqnSSzPFQ4OnkumUuQ==,iv:wFzmjeqSZJuu/9pNza4YskAzP+2JSU9dcGa5ra4HSTY=,tag:MysLdkpDtZ+chNaQoUbmXA==,type:str]
    INTERNAL_SERVICE_SECRET: ENC[AES256_GCM,data:rRF2q4NQ7xqs2hlYohJa4wDKUTjCLIlo6nvXpw==,iv:3QRS+yiBmjX8hx1J5uFINDLbiv/vNh6bmLSOK6uh0q8=,tag:nTaSU/1lAhjDjI9i3XiM4A==,type:str]
    JWT_ACC_SECRECT: ENC[AES256_GCM,data:ibTAbkQCVwlaEXOa,iv:FA9S/KwGt2qOUiHxX6wA+QwnjwYjJh/pjBDYPrLtY9Y=,tag:LlhYPck1kJ6FI7RPOjdGhQ==,type:str]
    NODE_ENV: ENC[AES256_GCM,data:/M4TWC7tsWm1JO0oz7Pr1Q==,iv:iFa1ljbtliywWml1dqslwCrzRy/xjCnvQgwWSvu75mI=,tag:8TryxBx907GOk06oKMHrKQ==,type:str]
    PORT: ENC[AES256_GCM,data:PH3W0LJz5kk=,iv:ZVPzhkDiCYbsgZJzIL/ROhd8Z0u2QAF9LokFzJA5Exw=,tag:uO3e1UyWCL707Uq/ypiQVg==,type:str]
    PgSql_Database: ENC[AES256_GCM,data:xjbto67dD3djS0if,iv:ff36v0XZOvpA9wEj5+VfMYQBahC95z+11stmBO1H650=,tag:k8q3TfJH98wzp5Cp4JwORA==,type:str]
    PgSql_Password: ENC[AES256_GCM,data:lLmG4iXm5I7qIIg6uZuOMg==,iv:mvMI4D5WI22HxEPmknU2zOTQ9qnA/IhgGwMcAY1lbaQ=,tag:sk3ob8TITOXwZZzzYtWTfg==,type:str]
    PgSql_User: ENC[AES256_GCM,data:zkMcMs52RrMblK3qTfnk1w==,iv:txkh6HejVULzZVfBDIAbCfGAwut6A928kipczSZmC00=,tag:HCmxNAdOMHOJA4+hIKHyzA==,type:str]
    TENDING_SERVICE_URL: ENC[AES256_GCM,data:lbHZqo6gVO4GU4Ele4iw1BaE8T4ae8YMIeiw4w==,iv:SqrLY0WhMZxNwdm3yqvXhBmWUayTKogpRiu93yBBv1E=,tag:tlrTpRGlKR2HznfrQyTk4w==,type:str]
kind: Secret
metadata:
    name: grove-secrets
    namespace: bonsai-dev
    ownerReferences:
        - apiVersion: bitnami.com/v1alpha1
          controller: true
          kind: SealedSecret
          name: grove-secrets
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g2lray3jp4plrwd6x2uzhk2gq563kcshuc0xy962e4kzkg9789gsdrlenq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOeGhTcks5TkIxNmR2Ukcr
            NzZMZUgvbHpDWHFjcTArOTRCUDVIVjZMYkhrCmtHSU50L1hkOGpoNE0xR2lMSUgv
            ZXZFN1BPTlRpZWE4a0Zod1UvakdaaXcKLS0tIGRHNlhHUE5KRHA2SDRwSEFyWVYv
            VkxjN2w1NEFuMHZ1Q0FTYitHRkdYdFUKM8W4y6XuuWOg1R9SjN1kxFKQekCbL588
            HchtfylbUHOzmJc2QW4T+rvSKbr1rxWdLvdtl52QNRnjkhieQ5j4Lw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-06T10:42:25Z"
    mac: ENC[AES256_GCM,data:T8qzIVzTwmP0d952wq3mD5qX+XltPYaM38E2IJ/vpO0SAboUtPFQt3C+llvemffuHcv3zcvg8Ck6qJOQEUWKXZV2WV3I4jM/ZxSK0I7p3meiOlZpFzrc4Gz3VlPEg1k1YHA/07c94A+UlfU58wnHifz/r/jf4W9iSxs7V0ozwts=,iv:WVEW8awDiwQuPSsZSekegCK4rlrThcHy/8qSHG0rG4U=,tag:rqMGQtsByvLrsAWqcO6pTw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
