apiVersion: ENC[AES256_GCM,data:iuGG/1MjW0gou4pcyYpwHJyNYDCEnjZ0uyPzLCTkzA==,iv:r3+zjTudJ8reGYkSp8OU9BA7Q4xtR88QQx9zB9wjv00=,tag:9JLzPc78K2WZ3cxLuRNZsQ==,type:str]
kind: ENC[AES256_GCM,data:UiRd3uXhkw5LUH7UAw==,iv:tYGfA4rBRccRA6lfONUT4He3tkKFiJ1AR2h4HgtaZMs=,tag:pG4bSMmHon51q7E3rDBh0A==,type:str]
resources:
    - ENC[AES256_GCM,data:cCtH4wqRulsJUqQx+kcjd2qR6B1lDgiKFLXM,iv:egMqbmCc3w8FbO2l9lpYxv8zrH+nA0yFYP89f6SECek=,tag:h9bpFslEk1thZmGaMKb3xw==,type:str]
    - ENC[AES256_GCM,data:05M3zcTj56qH50Irf0SaJYuggJgTTDI=,iv:dElehS7l844teracjOE0tXbwNMOuiW9ZOL9/ERGTgcI=,tag:LAJhuZW7lIqf16BI7eZ9xA==,type:str]
    - ENC[AES256_GCM,data:3nYyp1yuQtyXDx3gB2TSCm+G20grgSSUSN0ga7E=,iv:0aD3FLvrQp59ykGYCvvMTgNsTaNxOA2/2+LI17VXJ4M=,tag:Zwdw4pNLO5qwanda6JgqBw==,type:str]
    - ENC[AES256_GCM,data:7fcmYbY5IEechI+H3RhrvrS7Hm/EcR6t9g==,iv:/D7o3Zic7ioRQ8ldnw+zycCYDqwhkxPtx7JDD7tW/Ws=,tag:RR+nySHZvC8yvg1XqNJ/Fg==,type:str]
    - ENC[AES256_GCM,data:F4kl7UNbJgyuOUEUTSwwS4QDKSBm5lBpJkmoX9eQu5+lug==,iv:PGYBtgqsdRL/3D4ObPWNu2R8L2Erua2zCBiA7f0fw6U=,tag:ocigl6849wJtTAZg5ws5nw==,type:str]
    - ENC[AES256_GCM,data:O+ZMxvpkGc5CKp15BLDgkwQ38YoY,iv:pef59k+ostw5TTl2e6ZQ8YlU0X6Wf3SQDI/3hBYFFFg=,tag:KRDzof3z+3iKOb7Zr/mp+Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g2lray3jp4plrwd6x2uzhk2gq563kcshuc0xy962e4kzkg9789gsdrlenq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlSXQxd1UraFh2Y2FuaE5r
            aStpSEhGVnNIc0VrM20zcDFZbzdOWFE2K1dFCnZGSGdRWFlDbUY3MXhTaXdsL1RX
            SnBieEttZ0k1S1d0ZS9CR3ZqdGIxc0EKLS0tIDVCL1pFbHZnRW1DQ2U0MjBtMDBE
            NG1zNlU4c1pMVXEwRnBYbmlTOHNnQWsKxzTkO70MwWPY42Mek/jtgoOsJ82lQFjf
            5MiJLhQj7XxG+3BfboGG5it4wuFodkktlr6sVrMXvYePhoG+t++2/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-06T10:13:16Z"
    mac: ENC[AES256_GCM,data:HfalcYEl0srN5rXr3GgYrq8KoMo5D7T7q3++RSWiFxWgBo4Sw5Vke3ch1IBvao8oIXvN15uzh74WVo1ihD/aW604rL4vsJcNeycsvKJ0Wobh4574vjaWLkubmDTrq+FNlr21CkD2OTzxC/Qg9GS+uKCySRQahUvDJi2Q81pODhI=,iv:hplHWjpOyakh5NHyutyoWUndt9T+9PUPPk4AzgykfQ8=,tag:Z9Y9ZbqetbInEDcvV/2ReA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
