apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - gardeners-secrets.sops.yaml
    - grove-secrets.sops.yaml
    - marketplace-secrets.sops.yaml
    - tending-secrets.sops.yaml
    - visitor-services-secrets.sops.yaml
    - ghcr-secret.sops.yaml
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g2lray3jp4plrwd6x2uzhk2gq563kcshuc0xy962e4kzkg9789gsdrlenq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArV2Vmb3hrWlM5NzZEZUdM
            c3hTeHY0c1JRamI1MWJoeEhGRmdEdGV5cWc4CmFCZjFnNHNMR3lIc0xkN0pieVZT
            eUlGenhxYncvSmtCdGlFYWNORFp4Z28KLS0tIHB2bDhoblc2cUVpN0hYQlhxcThw
            RjZHRkRSNnROZjZLZGxLaFE0dzA2ZFkKT7GDIbfQJFIKwN/d/pNnjz+LSt3YOvE7
            fquLoCPxJVyZzQMqnFqehstQyUADeOmkc43RkPHuhBnI7A3NVgiwKw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-06T10:42:25Z"
    mac: ENC[AES256_GCM,data:izeTrMzMZ7ndJY8PAWtg7jtC/r/0HB0MNZltP4+a3ttlIwzAKFK88DE9Z4osQbSq8VB4h0UCsS3S+NTKr4nR8Y3scbUBA0QlTOiAno8vslsmJnYBzLPx1BEKnmPzDgxdHarE2fVS+ophCZ9nMzG/lCjmjddc/aQE8z2gG7tZOm8=,iv:/iAkDuabPJK2OD5g6Wmn29hnVp1WzQT3UIKSCArStRA=,tag:5lC+7KaRykfS9h8QJ+rHfg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
