apiVersion: ENC[AES256_GCM,data:aRg=,iv:dQvTlW3feUMD9lK3zJNRARxqQGmg7wCC9NE5AoT7iXE=,tag:4bZRccCRUxLp3bZNCDQ2zQ==,type:str]
data:
    ADMIN_EMAIL: ENC[AES256_GCM,data:PhFSAcq7w+i+S9+MOoiWpMQqx2eR6+Jbdw9TkQ==,iv:v/oGuaG3vR2WOndUUvuM/1Sk6pL7XUCtmPkHBHahbmg=,tag:YcD3+yJm0Me05mUGqhE7lQ==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:zdVKExZJa0P2Kyw+,iv:Dp11T+EpmPfZEQwGZvKV+DhO/YG4MlQZqYhkcpF+dyE=,tag:QjTdnojVcJH4Ow+2bNESBg==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:VKxy9Nv3DEGU9LUUPGNXTBmPNW3gkcAzO1/lnad1OdjimUh2A0Dvt60x4gw8TT9QD1/YBejDqBI9p9X29XWwvoZUQ8PHg26FI8NU0Grbq/TUJo01G6niT34X5F3RpFffwgnLqHZYeRK0PhEZ3MsaGyXoLNj/ZTEA75eEPP3huFM=,iv:QYlee4C2UmN1s0/QIIWc8BaRsCmQ3ku9fA2w89HZ/GQ=,tag:DZ2LxfOl7SWAuTI9dI3o/g==,type:str]
    FRONTEND_ORIGIN: ENC[AES256_GCM,data:wVKSBI7QFF1CK5mhc79eZIXxS5TbU7a6iQdsYw==,iv:MgibC63hEw3JZOGOuRV3eg7HUUoWxjV2fLoPCf2NTQg=,tag:9OfuiiVZOvKlPd0/ivAo/Q==,type:str]
    GARDENERS_SERVICE_URL: ENC[AES256_GCM,data:ZS/jHQhWi4/7WsnR7xRQzbc9OEKBeb90eh/2vQ==,iv:zEkglg6/L1vhewPWiJbDnX8oQpgskKNvAG+z3RpuBTQ=,tag:me4k69wOVjeVt3sixsssJQ==,type:str]
    INTERNAL_SERVICE_SECRET: ENC[AES256_GCM,data:J+zrjIwsz/M8+KDfyl5zx9fdEZbOA3/Qjkb8RA==,iv:8b7SkTbRuWdFktxvK99ZcMDMGnBE21oIo0qeXusxlKY=,tag:10+kGAEgoyYsZofdCTG50g==,type:str]
    JWT_ACC_EXPIRES_IN: ENC[AES256_GCM,data:WXiGuA==,iv:uDx5l114HhBTmUDZzG4+g6EFDwlx+7dfL+CypmAvVAU=,tag:wGkqVWUUGaZ01vl6pZKmaw==,type:str]
    JWT_ACC_SECRECT: ENC[AES256_GCM,data:RaxdCUUe7Yb+GD/t,iv:zw2gBwaQbEv+cywasXL9dMDdWvQbOO6P3uvWTv62CzI=,tag:sxCy7acjOMCD1ODckvrq+Q==,type:str]
    JWT_REF_EXPIRES_IN: ENC[AES256_GCM,data:kRdb8Q==,iv:eTSC+v1XGJwICu4ANXVq6VE5ZMJqYzXCZvZlyYybLJQ=,tag:iF5NYZJgMc/8Y6ob+nMPxg==,type:str]
    JWT_REF_SECRECT: ENC[AES256_GCM,data:xWRWan67o7lxR1oG,iv:TcKTMUNiReDZZbvpcbaymCo5PAN5CKrHUG9Ck36Vcmc=,tag:0KUWYwjwgQX7kr1jVCgKbQ==,type:str]
    PORT: ENC[AES256_GCM,data:8AFO+Ol9ZSQ=,iv:8NHJz1bCGjM+rC9PXYg1XumIGuyjKeBKa7JpLXcoVBU=,tag:YAfjSgfWntVrErRI5NBrhg==,type:str]
    PgSql_Database: ENC[AES256_GCM,data:ZsH0EfJgYA58WHIAmWUIucGeZKM=,iv:9O7kC2E8iyEcsuljA5FUH2H5qpj21N9O3TsZw5zmfhk=,tag:KWFaz3CNW7B39025H1xvmg==,type:str]
    PgSql_Password: ENC[AES256_GCM,data:rG9Z3J/d2f0c4M/Qz9URcr1R8Ral7MSN,iv:Q7tZ2eKp5CBrUb+8pga7WjKe55fxJY5zFhQd1A+kyH8=,tag:Y6/jSl+ex78b2OtY0EZ74A==,type:str]
    PgSql_User: ENC[AES256_GCM,data:IYNPz1Bd2fTLTf7VYiAeAKtUuTjpetuY,iv:ESm+hKfmq0AKIALvmFn3weaNV9JvSnlc65TE4mSXinY=,tag:ThgQIT8Ybgbsq/fkCkB5hg==,type:str]
kind: ENC[AES256_GCM,data:4AYWnQ4t,iv:aIPgISp1dTFTXfR9jRe4vadWGCtQzHOd6K307TEx7mQ=,tag:eIM3AJZCfeezB0j9TiRfkQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:bUssICksei0s7GHp3e/eAdi8oA==,iv:KVQJU76x7M15P3f44KnnOcV58QmZWn86Im5gX2O/NqI=,tag:34Wk/gjBLp2AWsRJfNShMg==,type:str]
    namespace: ENC[AES256_GCM,data:yJCfPZmQqizcpRw=,iv:fHwtIt93gCegkGz5QdILGTpcE/D20s8qjr8vlmD1eXk=,tag:JedldyJEueBHtIvxrL++GQ==,type:str]
type: ENC[AES256_GCM,data:LrFlHkmj,iv:JKcGcQ58nRoDgtzOKs6A2Mx43BSU282k5pEGzF0A2KA=,tag:ALb7SOk53r2LAnlbu7YuXw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g2lray3jp4plrwd6x2uzhk2gq563kcshuc0xy962e4kzkg9789gsdrlenq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBubVM2dlJURWUvUE5RWGY2
            dFNFRXNMSm1RWmVOVjR1eGJNRUtpMUp4SUNNCkc0ZEZINVF1bENhZy9lZHNTa0NI
            VG5mb29BUUVrbW5TUVJ4bmoySkRnR0kKLS0tIFZhZmNhVXZQRmQ1K0JPeUpmQm82
            L3dSOURSNytYYlVEODVMM1JWMVVwQkEKlDhC4tiOdR2qRZjU3ymFud+gHy/0s2ys
            9uqmsXK6zbvwG56/DorL6/tuje9zIb2tHJ4OGxHU8ZqeB06KuQ/pLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-04T17:58:18Z"
    mac: ENC[AES256_GCM,data:Z/MGUVRJKACSalgXjvPxbDoXHvguSqlPuNPa081WrA5FGTDchFvXahDI0IyeKt09xLZDC3suwRVlUvwMJmQ+FliTQ1msWnwo5jhS3OpGae31zg8RxI7VHZVxEc9AbTY0G6dKo2rjEnwTRg/cXAaIiaRMkN4g7ILcR2UcgZ3PmHo=,iv:w+wYD/CiXjlDLpBmtPs5CmcEAcEY+fq0Eh+kwrGelSo=,tag:x4uIlV84cDBDTOzaZqIRng==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
