apiVersion: v1
data:
    ADMIN_EMAIL: ENC[AES256_GCM,data:ORQSEBidAW7IJgRGWTl8fA138sZCUPaIjgoYoA==,iv:DKSm+/Xx+409thrN2UU1MLENnsD5GdOcNEqxuGDjSYw=,tag:qGhwR0sU0L5Oam9M9G2RnA==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:IAN4Cb3dLeq9JHJg,iv:hoekNnGLMyI5SxjovaXDBozGQZ5t0NnParhqxqc+7sc=,tag:ecJzJyU4ab3H6iw7ROAigw==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:Kg6Jwi64rYjnbLyslBCwsYOv93ymMGqg0LzCtQP+gAlyVN89Lnxu7+unuFa/8E3zWdPPDPrtOXa5OoRt1vV6I47C7u/TZE1ro59xs+hT/fOINi39qmZfN3qIyoLIWZSwS9EpU8eUQxygYUgXc0fsAX1Mc8x8SezInYnE9zG5eSw=,iv:T37zn6gsZ62nB2UiO8XO/ccrw1MfJpEFZoa9LpwfWpY=,tag:isxpi/M+pyYdML6lVWOc/g==,type:str]
    FRONTEND_ORIGIN: ENC[AES256_GCM,data:RF2Txnp7l9zS+NFxkntj19LlSgnRKMhwAEgsqw==,iv:yQKrilfcqWWd7XAeW5jIjzwYjE7mOszeAjzICLO6azs=,tag:HxJ3i/mwwpGFw1Wd0fHb5g==,type:str]
    GARDENERS_SERVICE_URL: ENC[AES256_GCM,data:ElchBKcBR+zWS6QlDKI+9RSH8ROemZlRYhAIKg==,iv:xr2VbA8XVR0hKzvakjln0xYI7wiv8z61IPCG2ba4Q14=,tag:G1yix495XyzDqCOQUOsdeQ==,type:str]
    INTERNAL_SERVICE_SECRET: ENC[AES256_GCM,data:s0GqIa4S4Z7JSwXTP6nrqROtI8gga6C3T+o/tA==,iv:08Mi0CC0yUdSiSsrckFupgP+LIWQoBiy/tg0nOgRgU0=,tag:HtQcrUQQTqBDBXgQoc8egA==,type:str]
    JWT_ACC_EXPIRES_IN: ENC[AES256_GCM,data:ZFDcBA==,iv:in1ugLw9lz0aWP7caQgwu4YcUT8kSakeRkfMnpyhes4=,tag:9AiYa6rRvdWHC4z3uNyNEA==,type:str]
    JWT_ACC_SECRECT: ENC[AES256_GCM,data:8K0okLgec5LU6tc8,iv:31XJPAysmPn1xNwmEKoRtP9U/aUZ1R8FKT+7m8LOT2o=,tag:L99Dqrh4w67lMY//iImEKg==,type:str]
    JWT_REF_EXPIRES_IN: ENC[AES256_GCM,data:txcoMg==,iv:sxrFti1696ApGXqmWXgKfrGY2arBSh7sDPD21w9fnYs=,tag:eE4z+kL3+bKX6RKzIbgh3A==,type:str]
    JWT_REF_SECRECT: ENC[AES256_GCM,data:FVLCvfcYu8X/nQFq,iv:U5/SU0XhoxeAvSNXV2xMPFqlE76VScsYlYCddn5IsXQ=,tag:yZ51AS2AxmxnylTR06/z1w==,type:str]
    PORT: ENC[AES256_GCM,data:CILA0BqsJa4=,iv:ZCzekSAJnFLLvhlQazSrmmGyNIJJkjoKn5Sntb0mKcw=,tag:Em3eQQ2TnY9HyE9djN2dhQ==,type:str]
    PgSql_Database: ENC[AES256_GCM,data:1IcDdfDdCSbmduuE4H+2emC8du4=,iv:iJns4Tkb6nDPKYIi+A9vuPwIMnSp6QAqf3FhXnh0byI=,tag:1AhK6Q0O2Az2pG3ikp94yw==,type:str]
    PgSql_Password: ENC[AES256_GCM,data:de20/dq+BOALSmEcMtiR0na/TD14uSU1,iv:P/7+sccYseQib9ZXJ7ajUJ3Y+Iu73mlUgRMfdtwLWRs=,tag:XpZJ44olELbvXkbX7md8rw==,type:str]
    PgSql_User: ENC[AES256_GCM,data:edjIpTsT/ZF25ZblqksqSoOk4l4LjGZC,iv:gtuW2yFz0XKV4WyLjE0gP87T/QQroR8oLjeCcU/6qfI=,tag:ZAiAXjxIHLa0OZ7W3Z6D5A==,type:str]
kind: Secret
metadata:
    name: marketplace-secrets
    namespace: bonsai-dev
    ownerReferences:
        - apiVersion: bitnami.com/v1alpha1
          controller: true
          kind: SealedSecret
          name: marketplace-secrets
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g2lray3jp4plrwd6x2uzhk2gq563kcshuc0xy962e4kzkg9789gsdrlenq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKeXVXejNLejMrbHBqRFFv
            NEcybmZhL29KTStLWmsyb0c3WlJIRnVRRlRBCm9CTXJXTHcxN1ZWM0RuN0pFcmxJ
            TGVQdXNiNFYyaEZiN2pnK2lyY1VBa0EKLS0tIFc4YkQ4RTJVa1JGaFFkVThsNnVn
            SnJIZE53TC9hRk9BK2dLMmo2KzZCM2cK0w7HOkoCznnz8vPsdGx39ZAbbSyNIUa8
            KOh2fnXcua+r3wrBj5TZdPAQM8eeLDvTTHLCcUzvUZeY9JAqPB8Ajw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-06T10:42:25Z"
    mac: ENC[AES256_GCM,data:57bBRja/jEzJmYpuvJZQuvYFPgWx1msE20Fc1tZJkz2yMXwas1UPo1nJeQkkfc2b/g5clJOzNO4yV0nNev3Bewd0veXqS71Z40kPHEK20boBvVV2d5YzrlWW8QHjmrNk3KWvZUWPKMRdbmPCVa0Vqj+1+ltGEvvM3Ohec9SY9fA=,iv:OuCa8ca1O3SKQQBbx4rujTO5kuIdzid75pjQ5Rwx97Y=,tag:5IoznWwQTqGtTq/ENsi0Bg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
