apiVersion: v1
data:
    ADMIN_EMAIL: ENC[AES256_GCM,data:47YK83cPnudPzeiF8VoNSM6quodztp5vrB4h6A==,iv:yDH6jyn23p4N8Prp8cuQu7SfiLwI9q416jQysGV0xtE=,tag:B0L5XzVbESgIQ3jEcYfm+g==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:a4W2/NaV0dfvR59A,iv:DGs2x9jmPaohmVk5hnqWfIvqJt1mcEGL022S/HP/uBA=,tag:r8oMy6lwSGHvvl3kTs/8lA==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:TCnWthc2EEfdEdVhA9ROceNynWCDIzTxviQxYac9u97qxTK6W1Hfhg9+I+Rv4lc5GvuAvSiZsu34Nfv3OAi3vmVYnCwMdUIXQeQhsHpgfc4mhDxc33BgH0meXnbg/M6zf345w+LhSvYh9Qlxvs1/Ybm7LUV6ZYO2KDKM5tFx0xE=,iv:xbw6ay9t0ZgCF+FT6rX/EfSqBa65cHLZ8WXfILMNzj0=,tag:HTwNRsyJQLWynTATxCHOdg==,type:str]
    FRONTEND_ORIGIN: ENC[AES256_GCM,data:QCCEnV87piCcf4cLxNP1J7pdtJDMmtS8PArMzQ==,iv:Tu06f7hawXzfvyDngXwQxEW0GEb4uYhkME0w52cSE1g=,tag:veEspLIOwnz0uqD6Yz45wA==,type:str]
    GARDENERS_SERVICE_URL: ENC[AES256_GCM,data:q3cPs3aMSoDiIcG0jfDuzyqszqaW0cCoBcSARw==,iv:P7Aow5vqyHyk2urZ1XwwSdIm3JeEkcCW7Bn6SStyZ+E=,tag:HD2n5lVg8LgHGdxAf8z5OQ==,type:str]
    INTERNAL_SERVICE_SECRET: ENC[AES256_GCM,data:GZ8pQ+5Cg4RF65bZoJQLeJKByj9jg7hjkrJm9g==,iv:KRgXHWoiOb/yK9XgeGtXrE8A7JPcxcYva2ZytT7LGgI=,tag:dCNPpgjyLeOvUnGD7MlOOg==,type:str]
    JWT_ACC_EXPIRES_IN: ENC[AES256_GCM,data:JKkDyA==,iv:J5IvMnNQDu6ScgQtbJremLnT1OuzOvb/QORrtOOq6oE=,tag:TiebyRfMm5rcam5J5NW0/w==,type:str]
    JWT_ACC_SECRECT: ENC[AES256_GCM,data:v7JqXIDWIkSNFxOJ,iv:vDAGmWv/DIgFL9uG2OstdmV5tB77J/ty/ycgtS2tbts=,tag:Vm8RjBlXUKTPZ4PWv1svRA==,type:str]
    JWT_REF_EXPIRES_IN: ENC[AES256_GCM,data:TS47Fw==,iv:4SRRVcVU0NjkhnsvJgAs6zdDm0LMcWeJEQCJVbdgu/M=,tag:zgoNN2m7nxeBHIU2Nzb96A==,type:str]
    JWT_REF_SECRECT: ENC[AES256_GCM,data:eQL+yvK+wWdrbN/e,iv:N7bbCrs8yxsLGSnkqCArqEMyel3MNVMmMUDjB9MWVrc=,tag:SFbSxWf/5oBjTjseZP9Fow==,type:str]
    PORT: ENC[AES256_GCM,data:bU2V9ajVi40=,iv:OJ6B+rYJ9H3M9Y5T0CjgzEWwkscjytDNM/qjmff06HY=,tag:3KaL7m/Xw1BLpfvggmEKgA==,type:str]
    PgSql_Database: ENC[AES256_GCM,data:TzwWv+HQUnj6jL1HRMlQpEyVP2w=,iv:NlXsh6Uu6d4msaKoy3tZ4KmHf5C3v9ajDfyAIr15SSo=,tag:MfVU9snDGRy3Tt3qSc0dPg==,type:str]
    PgSql_Password: ENC[AES256_GCM,data:YVLvGY04k0IxWFX75dBGeGBanyLbYYY6,iv:yyWOsy1aul4Vvx7H5yYfdPyg6xyIwbwbSvjyJc+k2z4=,tag:FxAI1jBg4q8NGm40qYMBjQ==,type:str]
    PgSql_User: ENC[AES256_GCM,data:NYFLebg99gXqGrM5b+woOA4QEXIK0ZbD,iv:A9mgOSJoJTMWZw452mHItb5Gm5FLO3eQRFHfvDnaobE=,tag:pIBGzA0T+xcY4I9N5a20Lw==,type:str]
kind: Secret
metadata:
    name: marketplace-secrets
    namespace: bonsai-dev
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g2lray3jp4plrwd6x2uzhk2gq563kcshuc0xy962e4kzkg9789gsdrlenq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWODZ6K3hEcjhjLzNKcXl5
            MXJRNDVUZHZ1TFZNYkozTjhPVHF2SERSN1ZZCk8wYnBVTDlNNEoyNkszZVdDOWh3
            dEJrWmI0MHErcjdMK0NOZ1B5RTVNZlEKLS0tIGh0U1l4cTNFZGpDeEIyYWFHa3gy
            TWtIZEpmWC9VK0tMYndrY2JTMFNXN0kKPrKgn7LhLBR/smegsNkMae1BXeXmDwi/
            YZ7pxx4qNtfV8nuGDIifixwtfg3aUw/BAejpA4jy/aB5XC/+kSOwQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-06T14:10:52Z"
    mac: ENC[AES256_GCM,data:5mVawTuAHjbqG7bFJl32qRBFAZQQ7NgG0p5zPBvTYxmFRJI5vMNHAZLWrCmnwwKf8KfNURK99v4TcmJU/ISwj/7HgX5pvrQLTIG267ebfyXEvFhqnSRXXQKLHzHwgIAsA3mI4bPJNUu4k+KwW+l/XonHYCIk5qRdkWv6mZ7D6So=,iv:fynMrds0PGOSO3dSe4btATTlP3kxbH3Y7KcqMo+Z/10=,tag:BDvYYg8jbvoHEY11TE/DTQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
