apiVersion: v1
data:
    DATABASE_URL: ENC[AES256_GCM,data:lqZs7QmuUZ/NHkOyr3KDYe1aWTHpsp9ihxAF/jWNXWOFkPjS1LgfOHwfMvdfUya+gA2dlHRmtaLSffNa6c0gD3hWq0JWjhxydoOvJV6r4TBLNxDh0Eb2LA3Co2jDVBiAONyAcPpyA3h3Nojo,iv:bBxoTxio4yIhnZigUSjH8j1tF092qs683FTul2scBJI=,tag:i1HZCrUoC0gY7CxyjpEiZQ==,type:str]
    FRONTEND_ORIGIN: ENC[AES256_GCM,data:W/u4Yc1qwX2QHOjl3etHDtTxFLSqD67yrlkegg==,iv:bAPeysN3OGMPB231o+T8FJUOFjagZAdlMOB5RsJh6VE=,tag:xaJy76g9CUBbF0EYoUCQng==,type:str]
    GARDENERS_SERVICE_URL: ENC[AES256_GCM,data:87uCozB9hzgFQZQHz7ahcuwsjc/9BcpdL/kTkw==,iv:8+GL2/cFG9MtU59iFH7MSeBJJZyNAIgUaNERgCrMs+c=,tag:PgIwGtWKdfjN6iuTyoLjfg==,type:str]
    GROVE_SERVICE_URL: ENC[AES256_GCM,data:PucmVTEuTye940IrNizItTRI8iOz1qYB,iv:v2Zg5fL8Z0PLiW792Hmm6k4OKNqupYzCipwlmwlPW50=,tag:shH34w8BqaF+Y1c9TyDwsw==,type:str]
    INTERNAL_SERVICE_SECRET: ENC[AES256_GCM,data:bqywFARmVscQ96xaC1G6j3i6YnVXYI8OzuGTAQ==,iv:EFtbLrQUZhSx5Kbdzx7kVfZ1gafTNw4JSfz5myFyPU4=,tag:HZBnKHo9Z94mvmb7AQhP1g==,type:str]
    JWT_ACC_SECRECT: ENC[AES256_GCM,data:r39Aqu8jomCashhX,iv:ZpJcg7x+VC0no0ZewkVq1G1TAGaI6DvilQwaR0R+t6A=,tag:T1LWBXDNXQ5vi+UArj/QUQ==,type:str]
    MAILHOG_HOST: ENC[AES256_GCM,data:NODM0qDoKrRRJytX,iv:ipCZXvWqR3fph8GyUlj1l3giPKuukIaQjHsDzpxas0k=,tag:5lQvvryvrz9stRCjD9ooqA==,type:str]
    MAILHOG_PORT: ENC[AES256_GCM,data:lFABpinBS3Y=,iv:fXApM4UghZPJz8WPsNBp4kgTJRXlYDGNIrEFC2+X3e0=,tag:AXXqq0BRE1xMN8O2Zw4eqQ==,type:str]
    PORT: ENC[AES256_GCM,data:ooyI0INM1zs=,iv:UzDYlrHMI0BnMMdHp5nHvz6Znsmf5fAq5pNXJZ838FY=,tag:rYav+/E+RVxtRQ1FAjjWRA==,type:str]
    PgSql_Database: ENC[AES256_GCM,data:VV691xTfF84Y2f56wier6Q==,iv:EPF8+Vpq/rRlYFdq0f/+R5bz4Y31aNak+CNQFUd0iis=,tag:+ATwQBTepi4d8I1B+rYjmw==,type:str]
    PgSql_Password: ENC[AES256_GCM,data:MRQ2naSxO2RZm0mAL+zprQ==,iv:46mXkQankVVCHu5jSJHyscNd1xd+vCiKE6NXfgfLyFM=,tag:0EsljyH6qMxbFOX26mnA2Q==,type:str]
    PgSql_User: ENC[AES256_GCM,data:1fhOMJ4BBybTK21hk/zNRw==,iv:sLmOT7+MSrA7bspFLAudQm9odVdKLzsb4Su/9xwbBjg=,tag:l2cX4CJ/V578gXW611mLJg==,type:str]
    RAZORPAY_KEY_ID: ENC[AES256_GCM,data:k65mWUR4RCTcf5wIt5uVbs2eUwLQuTQfOvl1LhW+Jnk=,iv:/ozhhEWqpJu9KPGMn4d0LKtuHGTYAnTH+MZFHvWkyRc=,tag:qsj57MP4zmp7JOqIxl/oTw==,type:str]
    RAZORPAY_KEY_SECRET: ENC[AES256_GCM,data:sbEdHiPkB5xiR9KQuDZ7TqE1At7YPcT7/ahh02WNlJQ=,iv:lMX8yvUSfI1kJqmoEy3Hw+nCXK+6rFCC9fuwNfnjF4I=,tag:0uQpOKDz/WFlUWSRax80xw==,type:str]
kind: Secret
metadata:
    creationTimestamp: "2026-09-29T04:02:37Z"
    name: tending-secrets
    namespace: bonsai-dev
    ownerReferences:
        - apiVersion: bitnami.com/v1alpha1
          controller: true
          kind: SealedSecret
          name: tending-secrets
          uid: 49fb6673-c55a-4257-8079-7509103cf25a
    resourceVersion: "1065013"
    uid: 8c6a0aed-e05f-4db7-a7df-91c843277cff
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g2lray3jp4plrwd6x2uzhk2gq563kcshuc0xy962e4kzkg9789gsdrlenq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Mmd0VG9nOU5jM09lNHht
            NnZIdko2dVRKS01BMDNkd29RWUlUYWY1SlJBCm9HN01jYit3Y2hhdnNZL1lHRWFZ
            bkVLVVBZa2lia0R2bWFuZ2hiUFBpdkkKLS0tIDhCTWRvTjZqUXpmMnhEVXk2N2Zm
            dXpVcjFhNWRNUnppR3ZzMEtRN3hXU0kKDd2iuEmFQm275tZOhqwbf4XcLstwCpFi
            NZlv6MbsKo+SLWZojSu+BKXH1QgYoiU69W1rfgsYxmZSxFQP1Sk0VQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-06T10:19:14Z"
    mac: ENC[AES256_GCM,data:z9TM2ZIXiwXouNFYbX9uzRcQUr6D9TauOaCOBa9/zydgpeCYq45mcjTGBwRbj7giPJOZJuDh0KwoD5hbQhdXgBn8bBvXr7XwtAbSZs4IcEVqxu5bmzPU9nx7T5l9wYkNw+qML5065lKaZsLtMn8Ncw+THg8lphcLk9PyXhBfyg8=,iv:3GHcZfh3pimo+BGQASWvQiF6Sw5G0ZEf73vKi/gugJo=,tag:+pqRJIYfjT0nQYThaktRCA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
