apiVersion: v1
data:
    DATABASE_URL: ENC[AES256_GCM,data:o5IIIQvEtPCiVuPbX5kT5TSQWgZYWaeC8ebg47T+RRVtRS7wYiAViTX9N6xvy0m86m4JsjVSU7K13MzDwgHvCsRxIW29NWxMxcdwqBWpvAWrN4Vvp1Y6LHhhOEXRkpVEJSOk5wWImxWI5qAC,iv:Bnp0l1RWAdOnzouH6UBMGdEtvJ8eZhjmfLdrmC+65FM=,tag:SmAiqwA2rNLPsbpWq8LIWQ==,type:str]
    FRONTEND_ORIGIN: ENC[AES256_GCM,data:MdbI9JAULN4+CiVmoxAftqdJkEM03gEqDVN4qQ==,iv:wWr6fm9hbgqrrpACREd8hiaahg1h9RGFL7k6z0B3pTg=,tag:6nh8UciUHiT6lMXuxvQR2A==,type:str]
    GARDENERS_SERVICE_URL: ENC[AES256_GCM,data:kRb+aV2+m5127RtORhcso8xGNxoQF/QSHg0lbw==,iv:XiF+h+Rn3tQJH8R82k9PbTYvknO6WrFwScw44Oh3nIA=,tag:FqbUhCb3qEgu0qzwD1zpwQ==,type:str]
    GROVE_SERVICE_URL: ENC[AES256_GCM,data:4BZYNJRKC6scFoN51tAujwS3kZWybKBo,iv:2amYHazonz1GOq4kwEWdr58qBFhxzebky+NE70kJ40Q=,tag:DQEb14amtH6EXcGQay4oAg==,type:str]
    INTERNAL_SERVICE_SECRET: ENC[AES256_GCM,data:/rcFfOOvYWaT0BQydG+Zu8rICKbMGNQIeYr49g==,iv:NhUAtloht8OaOpuPdn3CyWzoQgaDUbgfIwAcLL0oDJo=,tag:Nt+GfmAnVPpT9LJrk5cgpA==,type:str]
    JWT_ACC_SECRECT: ENC[AES256_GCM,data:Mu3RuHhCTt3kM2Wd,iv:X8lhwDeugqMBxBDb4xAEcr3In/ZZaOYCQw7WGdKG2f0=,tag:Z5gHsdIymuMurkH3DgX6gQ==,type:str]
    MAILHOG_HOST: ENC[AES256_GCM,data:n6lOUhAKYtKoGCpO,iv:0czj9luP1llq/eUNoxbm3p1ASFyhPvSzVLbH03vbtJ0=,tag:9P9cxhhfV0HG7jx+sx9eVQ==,type:str]
    MAILHOG_PORT: ENC[AES256_GCM,data:s+AsV+M342Y=,iv:2OkM7IK6fbYbM1D2XemskdByfejznD+QgLxiQQk2eFc=,tag:kF5sWV27cLiKgrrwOJ0X5g==,type:str]
    PORT: ENC[AES256_GCM,data:n5T/QQzzbro=,iv:oPz4BEyr6bEhpdMZ/VZRgqbx9ktA/rDDjo5XyTwflDg=,tag:3MuzLzP9SapcxS9+phcHOA==,type:str]
    PgSql_Database: ENC[AES256_GCM,data:JwNzSG5yo+GxbX3wgEyOag==,iv:Dvhb5fZDUWArmBjsznmgYR4JdJ7Y6ni56Bj+Rbf5vbY=,tag:7hP6ZLTS40BiEeAbrLJs+g==,type:str]
    PgSql_Password: ENC[AES256_GCM,data:YZRNzdnhYkVfoQ6u2NHGoA==,iv:/i1eROJx74H4WcRhEntAOFNp0iaKc1vhbwrTyczdBoc=,tag:81LTgOl7iHFHDpx2jifkoQ==,type:str]
    PgSql_User: ENC[AES256_GCM,data:8iqwem23ZmNLHyvxKIUIQA==,iv:h4P//Dm8VzFEKt9WTAHwlRxfsg9WQEDCg8EaWvvYslE=,tag:oNduAmdKtSAo75rvqM2ZQw==,type:str]
    RAZORPAY_KEY_ID: ENC[AES256_GCM,data:rIXlBknDXj0aIIwFaNIkwi3D8XUYcgmK+6YY+JQNuY4=,iv:ciwzAwDE/WtQfGDIzi3t8CtJd+wALCnfJ+oeIVoto54=,tag:i4FEnIpqnHeA13AkoLDWBA==,type:str]
    RAZORPAY_KEY_SECRET: ENC[AES256_GCM,data:h5S8dVjXlwIhng/9qQsmrNG8XgO8aK6XTVRUoO66TT4=,iv:DLzl4CuFgiTwqTKbR7KGeMmc5lhTD1vp6b2V+kQb6/0=,tag:Qton8Eu218yjxzUkhwaDrA==,type:str]
kind: Secret
metadata:
    name: tending-secrets
    namespace: bonsai-dev
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g2lray3jp4plrwd6x2uzhk2gq563kcshuc0xy962e4kzkg9789gsdrlenq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpaHJXNFRiSVRUV1RhbjQ2
            UEhldlEwOVpLc0EvVFhvT3RoQnJvL2V2YndRCjFtaFZ6T3Vra0FwM00vUGJhaURy
            OVZBU0pNdXlIUVNER1J6eTd6MnpCRE0KLS0tIGJmSTJXTlEwTm9hbjFVWUZCR2VN
            UThPNEJ0MFB3WnAzclFxZWRBSTZ3ZjAKN/7Ji5g/lSQJ1NFmK7txql6Knssx2LO1
            Uv0Fl9PR7LnWNnVXkc40ptzG6wOLWzy7Rk6R2ZGPGcCUyT+xggob6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-06T14:10:53Z"
    mac: ENC[AES256_GCM,data:enAzUFj5EqsUyJc8cc9RWybgaHXKwzvIJeowOMhpiT8pKsPeZJStrk7p2xuf5BjaZhivNYr+WCq1l6kz4oyC4YSm63RxlYd0HayZ3egbA00LLmJcRUSPOl8HL/BH2nsfG6U2xCQScaxV5aXYewZ6hHXPZ3pbeJVNP1LtJ/KZE80=,iv:GAQ2RrOeyOJolUe1IDmhCQYqoQTi3lPah6FoRMTBU4E=,tag:uyh2EJZq3839fchzaehawA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
