apiVersion: ENC[AES256_GCM,data:Ii0=,iv:PJvr3brGhjTTSsCxTAzmGmjG1LUHldqa0ILjdFaO2Nw=,tag:daX9+aL9lexGiyNeMUrTrw==,type:str]
data:
    DATABASE_URL: ENC[AES256_GCM,data:KUKwU7A89jeTM+j/ReL2iCu+JXj+cZZjCGY5Ai8WTZgW1F3Jm0dPiEYzzP4MtN/P+CSVh6zjowyovbeiZHwCaEZMV+ihhUI4/ZQC74L5g+Thh5CEHb5VOgNZJzV5H6g42kTqJ/mASM/Z+0Wa,iv:DGChPpjt3KUqe+O0bocvQp7KjiqJBz3fwalRQRU1/BY=,tag:UDhq6YqyDZnY9Zrj0rxoIQ==,type:str]
    FRONTEND_ORIGIN: ENC[AES256_GCM,data:rbiIOpeY56agpAmYefLAloUsJTDMkKrVNlpUqw==,iv:ER9+o6JntS5wZp6F2BSfaVzsZpqSvAWqHmgYlF3BUAQ=,tag:Eoewcu8i4yOu/qaplEutAg==,type:str]
    GARDENERS_SERVICE_URL: ENC[AES256_GCM,data:SKw+Z7QQxhacJcCvQHVvFhpV5jKdZSEy2sXfeA==,iv:uIQFLI4sWrGZm29JIPbQBMwxz1AMNMmrTwQqGamaZqw=,tag:NBhguwH6p696hULR7M7CrQ==,type:str]
    GROVE_SERVICE_URL: ENC[AES256_GCM,data:YhXBFjwgm9qolpLJqmKIVhzG/lRUP6lB,iv:Gh7puh9CBTXw8CBZ+fySoF1/al79PmmR1ZzgRMVRDZ8=,tag:nIgWotLz3C6Sn8T3v1aFrw==,type:str]
    INTERNAL_SERVICE_SECRET: ENC[AES256_GCM,data:392BIt4scoPL6Bn1pUkI7AvNOEykT4g8f9LK8w==,iv:0C3bicyxmX/WDJI2NJPnOoewx6eJXmGT8nsycB1Yuig=,tag:xAf9A9kKVKS6i+Vf9u1tpQ==,type:str]
    JWT_ACC_SECRECT: ENC[AES256_GCM,data:nWYg6AhxIfU05QdU,iv:M4idv1afMLNHwyEVAKGEFHMuBjFpDFTbHeQZ992XBi4=,tag:LMUEFIMl5DJBiJdmVkhGPA==,type:str]
    MAILHOG_HOST: ENC[AES256_GCM,data:jmmR+lSyWV1EH2aV,iv:fA3xv9KsZr5BctXTVdQ+rD8IPoe8P2xRolXPXp1TIJs=,tag:VplKDeBx/GSUWvyD3VRaYw==,type:str]
    MAILHOG_PORT: ENC[AES256_GCM,data:1TRqFM4yCnQ=,iv:mjFqAGZQJ+hUC3cbijH17jMyE7ui9TxGE2FlTWKpkHE=,tag:K5UGRyuk/B57Ml3I7nANlg==,type:str]
    PORT: ENC[AES256_GCM,data:e19uz6NA+kQ=,iv:67aiTHEt7GTaJG7ACmhrmwYILKZcy5gJhXDHHKwDC4Y=,tag:3nJ1JOrWfWhF44An3+FGIg==,type:str]
    PgSql_Database: ENC[AES256_GCM,data:TMk8lcO7ft30sSOcCWry+w==,iv:h+FYLRKVJ7CBEOZB6ddae09ai0KChXR0ctQTp7Sv7mo=,tag:o6nX5j6ATIZuCnzcxct88Q==,type:str]
    PgSql_Password: ENC[AES256_GCM,data:ll275StcvtpsUjWEIYEtlg==,iv:qRP42kyu1EUBKQCzHr0xNUYIuFZIUFDJBHTAPgQxcS8=,tag:pn4EcY0gBzkbk4cur1/Cjw==,type:str]
    PgSql_User: ENC[AES256_GCM,data:x7MdUCngylXYPatEiG3kSQ==,iv:DjIOZbytuL88Nr5/G9AC2lrwcIj/elj5K9Qwk7Kn8R0=,tag:wESeMGVx68KuFnJMBXtgtA==,type:str]
    RAZORPAY_KEY_ID: ENC[AES256_GCM,data:TbcmsUFrMMz45b+Is2tPVeq668HE0+ABguTDHeeyS4Q=,iv:u6/q9RZ+K01uIrUCT11ofgoWCaKnaPLFfnIxxvVzMjc=,tag:i13oNgHqVftbQzZdRTSGCQ==,type:str]
    RAZORPAY_KEY_SECRET: ENC[AES256_GCM,data:LRLjm86/2aNMgPYk6scgL67G/k3RO5RyZ0MzOuxgSGg=,iv:GmIh+A1lQZRjJwRtyERePsltuVrwkECgwtAPjvZaPXE=,tag:S+agp6TdaXqBjrPz2txu7A==,type:str]
kind: ENC[AES256_GCM,data:HFE91cyq,iv:AUepZhWx/DGFUJv1hF1qgmpGu75MVwlGDUWmKu+hpFM=,tag:DmGuHgj9BJ1h7NxLeSt5Kg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:+gDQX8M4qS2HisZXc9KS,iv:hUHK5oH98BrV0sCU2x8crAHR7bc5d0JcIDIxOvjBioY=,tag:vEJHs9KeI5SjfFHjHQ/rxA==,type:str]
    namespace: ENC[AES256_GCM,data:vaG8HwkI6Bo90XI=,iv:ALTvrCZPHiI7UiBx5B9NGphGs8o1dS9rrpOJ5BZFQ90=,tag:JOovG3Yg8Jj1OYWxDJr5qQ==,type:str]
type: ENC[AES256_GCM,data:vCdl09o/,iv:H+akWVlLo4XS9ipGcxhcT4KjOpRyaKKBAWsS5CNxAnQ=,tag:cfevuaiIXzEJvNT7A+qFCw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g2lray3jp4plrwd6x2uzhk2gq563kcshuc0xy962e4kzkg9789gsdrlenq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZaFFiY2xTNHlPV0Uyem1v
            RW1MRlhiRUFqQThPRVRpaHplR2lGbXFJVkM0CjFjMTJFMVZyYlJJcUE0UlVhTGFj
            TTduUHF5QThubHBYOUVMRGMwRTc2clEKLS0tIDd4eERKMDJoblVNQWpvR2tyMW1T
            TUg0Qk9wcS9UQmlpSTYzUjkwYVRJWEEKhtyQjhn+QoeBzNV0Dum8KQf9tyz1Fhlv
            ghlgW6lX30qgetS3lPvvob5A76VAsW7dARJbsnpBHN/JJEkwEL7KhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-04T17:58:18Z"
    mac: ENC[AES256_GCM,data:3Xo6m39uCNsiNJXysdgFWbigF8Wugn+Jvhitwo/eSohZOgJDe0VTkBYTs7mpCO6qWsME391po8awfWS6s+s9gNJh39+IWF/6KifEa+ko4BsY+ijZYNXnD+s+niAykA8LGVMFbDdURIX67uBGIa7KKx0688u0KJrxThGgspp7TN0=,iv:MvJMnj/sgLkUSxwE+t7201wcrUulZcltK1ANnfTUYhM=,tag:Gig+wkIpogECZW/BOoXt0w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
