apiVersion: v1
data:
    ADMIN_EMAIL: ENC[AES256_GCM,data:O0zpjusvB+1ixrkRKc3qZUOG0vvZfQTQiGAuMQ==,iv:GwW1ZpqP24R9a6LqB1DgJpg5A8GqjPHbchgJuOBXAuM=,tag:QE5oOAhfs9dOciwiF/VgJA==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:0Fw97ySoTeyjispS,iv:lxXFsewcgvKCue3gvR2VhFpc8EC7bgk5BXAsChbNs+M=,tag:2QcOK8d0Z+VX8SJc6Dte9g==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:YxCpha5E2AddEGJOm0rc1xUwl3GvDCssIdiv+5Y+DdbqgLvmRLWyK9vRnpDvof3Ma0UqMevTDg5BwgHob1Zqv8pcmqioiWt3CbrEBoabEqxVSsgCgaBrYNdIOy9PPj5ZFoOlJDk1UO8WmYOtVHbpaG3SfNNqrumB,iv:9XohHRIBuowKLLjYEq5kSTGLz/snzUWaFS87W/W2iXU=,tag:4BGWZRDttNfV1ypc3JyRAA==,type:str]
    FRONTEND_ORIGIN: ENC[AES256_GCM,data:0m6W8sWR3OkZlbQH4ilt8GM88AHKM5FKn4Au4g==,iv:FPP2bcwtkvShACqVEG/n1QpdJVy9hdL8gfpvwdW6yKY=,tag:8N4HbwQKmAVpX/0lTUsbUw==,type:str]
    GARDENERS_SERVICE_URL: ENC[AES256_GCM,data:1KDFauB4KWXXZzETNCRHXv+HCSfBWwMjzQDjQA==,iv:pjpTd/4a8VpSrB2xTD+G0fLBzMlI5XM2JdpJvk9gBJI=,tag:m6mZmWHaQ5CAlqJt53CI5w==,type:str]
    INTERNAL_SERVICE_SECRET: ENC[AES256_GCM,data:LU0H/7Sy46qoZSs7LSv+vbSgYmu46A6v8TPYmg==,iv:wMDJ/Kc+WDCq5TYlZSkQxkoQbdmrQi/KD5l4iaqB8GE=,tag:AdpDyIKVkS3AAN1Ie/N2PA==,type:str]
    JWT_ACC_EXPIRES_IN: ENC[AES256_GCM,data:nbJeHw==,iv:xfRd64qGSwalIoLAJnxFM4ZxN0bEtpN016qzZUDiU8k=,tag:qdL3i0HSawLldmIwDTlhaA==,type:str]
    JWT_ACC_SECRECT: ENC[AES256_GCM,data:LT5Gl+UvTloVbThf,iv:/gzOp+c+vYdPu9vdUwdmvCjOEBx6m5L1o4qvYGQQqHY=,tag:N4RqWhw4WePZQwbO0Sqpig==,type:str]
    JWT_REF_EXPIRES_IN: ENC[AES256_GCM,data:c0CjyA==,iv:pmemTmhUOnFe36XbWZgujX01Oo7kdPyprZbt5JwRrck=,tag:uCDH/F5IT7AYdBHCOpThMg==,type:str]
    JWT_REF_SECRECT: ENC[AES256_GCM,data:fylUt92KZPVEbWCb,iv:9PAv/6NKApqBN4BhJzFruHZMqSp/RYLlnhEVpDzia7Q=,tag:yemQBLn37JttMEqDGCCC9Q==,type:str]
    PORT: ENC[AES256_GCM,data:Hu9ow497dTk=,iv:iZUoK1tuZVRfC7mzxp6c8ifXUzda0DWh5ieGlV17fzk=,tag:GruP/uIc4o+HdzhOtkry/Q==,type:str]
    PgSql_Database: ENC[AES256_GCM,data:E9DSXom0bSLUB2Ih85z98w==,iv:0nKsbk+4MUR65PJ/Du1sjVVSoHf8yWeE9J87DMe2jkM=,tag:iua0y+OXk60ITnH/DPvOtA==,type:str]
    PgSql_Password: ENC[AES256_GCM,data:lBnIA6YUUHAVZ1ExSXzuSw==,iv:1LyT/zXxfz5mIsgUFg5+yq2mz/mY+w7MfxdFx8s7PzY=,tag:fafvsW14tefo/O2+PP23dQ==,type:str]
    PgSql_User: ENC[AES256_GCM,data:SGhFlmdm98XV6qfysZ9cQw==,iv:yEpKqPmvT6ia4BziGxffevXK07gzNC0cUEerb5a2UEw=,tag:YnTo7p+9SRShkHiBIhotKw==,type:str]
kind: Secret
metadata:
    name: visitor-services-secrets
    namespace: bonsai-dev
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g2lray3jp4plrwd6x2uzhk2gq563kcshuc0xy962e4kzkg9789gsdrlenq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArZElDTEhkUExERktVYnhx
            bkFXbk9sNUd6Z1VJYWJDUnNHcnpWc0swR2dRCkQ2Q3NzNWpHeTRYZVBtaWQ1VENL
            ZDczb1p2OUY2dThGWVl5NVdTOGxDMUkKLS0tIGZqNitDYkxBRTFqQllGcnJCSVBy
            NFJ4RW9tUGpHZHFEMC9VUTRwSUNMTDAKbyc82DApfgDoX4JrwJauKsASNyfIPEZc
            sb/L1vEoYKGNGujITHYjYs+XnIyc2hFMvkscW/oLzm4n5L5hBipSYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-06T14:10:53Z"
    mac: ENC[AES256_GCM,data:crpTMFRba8yVAr+nd5Dit45ZYKNTe0nl/+wpb5jAsTa+CHZAqVht/lASuw31SnLEqzTaViufLiGiGsl0iHCAAhb6B3SGN+/dLjHs5IiOLMmajqgA+vWPJuTeCmtJEslQ+tYEAROM6wn+esMzYB4iM8VCBFC5BTpUWrIoCZQj2/o=,iv:x5iTEDmXxm9rZw2Z74WZz0IGtA7yyZM9znjA+lsgAwc=,tag:261GHkIaWIWG5B+c5K2RKQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
