apiVersion: v1
data:
    ADMIN_EMAIL: ENC[AES256_GCM,data:qhsrndbIG9Xl8NsjnJFrEAWi5FWMyWebL6N3fA==,iv:iRYvU+LjfQF4jcXj8uc0awz2ZWAMyWrJyVQLdvLhkiA=,tag:CEFWH9ozMp6hUMdGdtJwCQ==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:aeXBFtKSeM6M4VIS,iv:Y8bKJ3nQYiS1fd4bUnc6R2edzuOxKNLLE5y4T6rwwHs=,tag:V2vjHB9SVYM4aM760784DA==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:HS9vq/S93GstMiofaglC9SB46bvdZaswL2ZED38AwwS3GuLxBsYC+HQD3X6nCnfqiwqsUIIgliK3KwB8a90GF2UlX96P8eWmAXDqMwoS21JyQYtZKNjduoCJO2F36RXumNJhi+9EkgOtQbe0ERkXz+QqP3Brn9RG,iv:KxwEJzKeeWi/CsDS/1kFYDIXa+e6YkInXIeB+46UG1c=,tag:Gv+peNL44WE/7iQIvN2Cjw==,type:str]
    FRONTEND_ORIGIN: ENC[AES256_GCM,data:gg+hDtfkYoNMJap7krAxM5IhkpA+GP9i7foR1w==,iv:2lMwfnR105/nQopuiTOQWapu4Pe2tIcr+0fbvYZKCUs=,tag:yiIfJLEdBLJP5axzA5pcXw==,type:str]
    GARDENERS_SERVICE_URL: ENC[AES256_GCM,data:fUsl++h55mhbrr37pMqhJ8S5HXDtPXkVFSQEVw==,iv:FjDUPGcA6t6yrIukBFlcuuvwZ+tGCvOZnMl8kT3p+P4=,tag:GkFy58Mjwk7MB+IpjOMUcQ==,type:str]
    INTERNAL_SERVICE_SECRET: ENC[AES256_GCM,data:+gW/ldNcWVfFV2e61ynuOXmBkhPQQpBdEhuXFw==,iv:6/m+JRVadmMzGcXnogRkkfYGX7mp/7pxli2RJw5dV1I=,tag:F0/zIZrlpRrQljJnkIn86A==,type:str]
    JWT_ACC_EXPIRES_IN: ENC[AES256_GCM,data:OfSkuQ==,iv:iiyscdH9U5NBguEoTtVlQKTJlYN+yw0ytroihWl5MEQ=,tag:Rqchtj9pTeGIHuLFlpfCcg==,type:str]
    JWT_ACC_SECRECT: ENC[AES256_GCM,data:1zqBIaKaY5aQC2oJ,iv:FqlTA+LagK+1/PcN1iwYe8LtUw3ZQ1Bi9KaFZKf5Osk=,tag:3xwrU/lM7CACYwqaWVfZRw==,type:str]
    JWT_REF_EXPIRES_IN: ENC[AES256_GCM,data:TXU9eg==,iv:1MixFkpmuBsyB4RPZPgbtH8n6zrdb5LaBZy7l+0dT88=,tag:PjjF2h+J2NAnxSg+M+srLg==,type:str]
    JWT_REF_SECRECT: ENC[AES256_GCM,data:2GhmY6ybbJEPaoBM,iv:D1v7sAt1HddLusKRfRGNxAlaPmtn5+6twoBopjfciqo=,tag:pUTLzIdHGBqY7GLR0rjwPg==,type:str]
    PORT: ENC[AES256_GCM,data:BYBbNTFvQUU=,iv:yj3QEzyj2BkzQF7DbpKLrFXviIc7xL2ZhPcNvwE5ifY=,tag:ivhD1kpOVMZL8IRDTTptCA==,type:str]
    PgSql_Database: ENC[AES256_GCM,data:0KKltwi9sFaLuBDzfzpyuw==,iv:uNu14dlETIXic+q/ETmBCtAAfX2dpRFni9o95LMJlcg=,tag:uPaiKTB5FKEinUomoQdPmg==,type:str]
    PgSql_Password: ENC[AES256_GCM,data:llkoFxQTQ8n5MePE69jzTg==,iv:+kEvCpnh23GXODGmwvQgwG8PBA1zLTSVvJvAvDb9C8o=,tag:k2ai7BLFmRo8HIP9NLpF2Q==,type:str]
    PgSql_User: ENC[AES256_GCM,data:Qi70oJz4NJGiH41RFB0RsA==,iv:GCOsqQLgu35krBQK5ccLWqkouwtrA9zpVoMgtK9hlVg=,tag:QMazf5w9lz3TLc/OOUtpRQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: "2026-09-29T04:02:37Z"
    name: visitor-services-secrets
    namespace: bonsai-dev
    ownerReferences:
        - apiVersion: bitnami.com/v1alpha1
          controller: true
          kind: SealedSecret
          name: visitor-services-secrets
          uid: 74ecb13e-d97f-45e0-89f8-0da57bd07d33
    resourceVersion: "1065017"
    uid: e76fb7f0-34d1-495e-85a5-e6faf041a57c
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g2lray3jp4plrwd6x2uzhk2gq563kcshuc0xy962e4kzkg9789gsdrlenq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQM1B2VGlHU0E2S1dkcGwx
            MlJTVG54SXBuTlRRUGNnc0pYQ2tFL1BpQWhZClhTTmJqQVRGSk1SWkloREJ3TkE2
            UFlIdENiYVRSa0pCUU13azRPM0s0SjAKLS0tIGJuMzM2WW1NS3lscENrNCtoUy9p
            WEFlT1N0TTFqZUNoeENzR1dzMC96YXcKiCfBIC4Sou9CXvzi/3Pi/mtEm0ARKMhv
            Fc5h5nYfSPQG3mGwGrr3mNcfIQ71Dgox/SZVPzmbN3GpPlXsw4s3zg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-06T10:19:14Z"
    mac: ENC[AES256_GCM,data:wCkfWEYAN31RMGkVwkgqzVgrXAiWA2HYe+kK5Zz5hqoJlqCdpKvFj+l1C3/VxjenMOalaqn89eKCvtMRSSM5yP6NneJTgaR8P5r7Y/yN+sSOqP6o9RgXpa+x3MXaDmjVO8brcOlikrO/y+U6h/Yw8OssfTg4D7dEMX53Oy6lCJo=,iv:/Eswdk5xB2lrYvNBitkbg9tooGSas36TyURyRwGr1Dk=,tag:nUnqsX5KetDrBL0ODBRTEQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
