apiVersion: ENC[AES256_GCM,data:HAw=,iv:6Iz905uhy4z6Navtfb3cpUtEEJHScgNNqf0y9Lp9rV4=,tag:CmWl5U561klQNx/UF14s3Q==,type:str]
data:
    ADMIN_EMAIL: ENC[AES256_GCM,data:GI9mKN9x33JnPmgHjAYmjFLvXu2WlLWUqYgF9Q==,iv:liLOLlOuIbwQ+PMylcM5vtQBvau04cRS5I6xAFZOEgY=,tag:fvnSYJAeW3z54E7BKlzdtA==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:Lwyrg8zymUQouh+h,iv:Vlt0yR1Ld/PcAVGL7ch3Ys5vZXb++GLkYF80rmWjdfc=,tag:ezoPpOWjXOt1LIEr5WbjuQ==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:rsANbUNb7pB7njWEKqlXJZkKKMzKnXPeP/W9JZP0gxk5q25nMwA1M9TO1kMF2ONE9MsLDtWaLAPDVcp/xksrnHQeOrAQ1VzfXK2MhRI8wtcTXdP7P4QKYx0MTo1lkhMqGC6SGn3PCUPm4Vib6glUEnNvfAcZ2AL+,iv:5Z2wvsNLk9RJxR4VNm6Z7InkFkZE0WjObJb0cjgxasY=,tag:xarMqHyCE4Dz9NFjNv9txA==,type:str]
    FRONTEND_ORIGIN: ENC[AES256_GCM,data:HxYZ4OK+46H8f6hE44POpN17kyiviSYPd2p5SQ==,iv:OOVp7RbU8W/DqV2lHW46NDA6wKfsy/bheb0nagiyUv0=,tag:QGwOROy7wSykWwxTHJph9g==,type:str]
    GARDENERS_SERVICE_URL: ENC[AES256_GCM,data:ReBn2WCIXHkBCv0Dd7gg+pfVoC8V9wJ7hOJfSA==,iv:kbgSsGxkaSGzpDNpHyz8PXkbwu1SkuMCQj21rw/BCoc=,tag:G1DTyj0ehR2MfMmy6p0B7g==,type:str]
    INTERNAL_SERVICE_SECRET: ENC[AES256_GCM,data:T1nnHT7Ze+ebgaiA7ZOamDoFulIZs+UYJIZXRA==,iv:JcFm0c0TCDNqqI5o/d2GzWMX2xKt472DtxhhndaPLJg=,tag:UaEr+0xM+EJSLtVrICV8ow==,type:str]
    JWT_ACC_EXPIRES_IN: ENC[AES256_GCM,data:ynZczA==,iv:MhmHYuvrua1vW5XLlafujMegwDnq2qSJ0HXL/71HSzY=,tag:bXrzzDR0m/Odmqm7mApwGw==,type:str]
    JWT_ACC_SECRECT: ENC[AES256_GCM,data:8sr7sd+nquc6ZAkR,iv:S7zvLJCazh4uzy1OS23BE9nDllMKM/SPLXG3alkgsZU=,tag:gNGOlqdyojQhh5XjYMmr3Q==,type:str]
    JWT_REF_EXPIRES_IN: ENC[AES256_GCM,data:cgwT1w==,iv:4CRCo2+hOdaLd9TYXTE/scamH+R4eyCuZWdGunIAtYY=,tag:EzZCHxKlLAuFkqD+rOSBQQ==,type:str]
    JWT_REF_SECRECT: ENC[AES256_GCM,data:KjbFEiZPkmXk0TfZ,iv:FOL2/pF307u6kozjqEC5KM6fVKer94iEaflv3uDI0Mw=,tag:hBzHACJo8QzZiTj+a2GWLA==,type:str]
    PORT: ENC[AES256_GCM,data:EmfijVhlDzA=,iv:0PYvYy4Gc7uF9XMiRThNZzQylv2U0cPoM9O1+0Db9yY=,tag:+QSKxklSIAuF/W4xtljEEw==,type:str]
    PgSql_Database: ENC[AES256_GCM,data:mRjt0li01li9LhFC+irawA==,iv:7t50D5zcCxFAcFthhr1xDrcGYwQ5Gvb77XpR9aQrvDA=,tag:B6XXjwVFZ/tR+5EzjgUaGg==,type:str]
    PgSql_Password: ENC[AES256_GCM,data:EVFDzsVtt6oQ27tosTibQg==,iv:W/ZVJGvK+Lv02aqFiRBe+68yOY5CxxNqVF0H7VZNZhY=,tag:fMES3OYjDmP+geN6Z9L0ZA==,type:str]
    PgSql_User: ENC[AES256_GCM,data:QKEgAW8FOv96T+xtTr+FCA==,iv:cmBJYVfsnEo9YFU2OoCHd8w87OBvAuYp7MVVXHxsGVg=,tag:LGbBI7whSkE7nYNEVS1LVw==,type:str]
kind: ENC[AES256_GCM,data:f+ZY3sp8,iv:mL0lVEn1nBHsqYKBz3UfR8DxqPVtMmNkXQpWtRwwk/Y=,tag:VWiawC1PpVwFt3jmNJaxYA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:rtM0Kn8Fe6XMnx0LpB0SoP7psBWWCwJN,iv:ZXTW56aQD0tObKLIq6pVVPrZkjWtJTJy0SFQZn4c4/Y=,tag:wzEA2yM/GWU3UhTjDFbM+A==,type:str]
    namespace: ENC[AES256_GCM,data:/anIHs58x6dH0BY=,iv:3wOkceTTGwUrOuJgTCYruDYqJizQvy/WUWCF1as4rdw=,tag:9cutKjPIvHP0ZFBx6QVXpA==,type:str]
type: ENC[AES256_GCM,data:ULMEBAoa,iv:0FYXxasYcOtQ71OVs1VUiZ2HB+OfOvbrRVabjsmbU+c=,tag:s3pHO6j+9xUK6vAeCJqcPw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g2lray3jp4plrwd6x2uzhk2gq563kcshuc0xy962e4kzkg9789gsdrlenq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMZk1GTkgyQ0k1d0IxT1BZ
            d2oyZ0dpWFVXeW1CenJISkU0Uk9EclZKS1hBCjJDVUorRytoV3dqZmdwSDBYdi9z
            SWkzK2J2RXJXc1dIYm1kTGE0dTcrRWMKLS0tIHloS2RSa09sdDRJSVoxbXJ0MFBu
            dERkWllicnFYNHE3amUyTHNOanZTYTgKVfS3Ih07xJPE5qDhk9Pu0OMUxRXhKKzd
            0HnqpoZJhBbi5ACd59RXnklUwkeZHLznnh0CLvCbPcVjtHiLyfHdbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-04T17:58:18Z"
    mac: ENC[AES256_GCM,data:fnq9IF+f1jCm1LUxx4j5rf2dQt8oa7qWuwGekmn9Tir4HF1fa2uSpbXHGx/rOVeNQQdEfUj4ByqLFBy05iMf8Pu6qqnuf/zvv0VAd2A4WhKz6YDPAsJKOQsVYLBIPL6ZybgPFrdJp78TKfkdwynCiobM1w4qNlG4pt/W2xnBMlw=,iv:tZy2n4vOGMC5LsjUIdPOE384f5hT4jD014LUaE3t4q0=,tag:MrZMnnwtHbBA2kaB1Ud/gA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
