apiVersion: gateway.nginx.org/v1alpha2
kind: NginxProxy
metadata:
  name: {{ include "bonsai-exposure.fullname" . }}-bonsai-gateway-proxy-config
  labels:
  {{- include "bonsai-exposure.labels" . | nindent 4 }}
spec:
  kubernetes:
    deployment:
      container:
        hostPorts:
        - containerPort: 80
          port: 80
        - containerPort: 443
          port: 443
