overrideNamespace: bonsai-prod
deployments:
  - path: platform/external-secrets
  - path: platform/gatekeeper
  - path: platform/sealed-secrets
  - path: platform/traefik
  - path: platform/trivy-operator
