apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "bonsai-services.fullname" . }}-ghcr-secret
  labels:
  {{- include "bonsai-services.labels" . | nindent 4 }}
spec:
  encryptedData:
    .dockerconfigjson: AgAPP/yeYarBe0R4Y4kpF7DZ8AXbbX/bjH8Ge9PfE+iN5hCxeV1l0feHG9pjmRDrhYuFemV6ovYfmQtajYh7T/CEEJZ3iEgQMqwrXTZQpiPZxW+qqTkslhyfEUhYCnTMW0hpvhg7E8woVyRx8tycYUDwGX5Rul8SSN+w+t3A5i1N7dv1NZR7bDTEo3Z9W83ygy2SgZGO9D62Vfo+j2HS4joxx7IB8vpFKW0vV5HBr9QXw2hKXiG9jpYi1nt287eSGfBfXD/H6KIHqzOCFN/me/BFgIO1vLfV/xnlhj/Bp7ivahaB/iobzlSqEt0p3OibhsDu9cRWY3T8CtjpeaN6UaXBXqPxvLkhTRvA1gY5bNZ5hD67OuqqUqZZvaK9IHSnriwaBPkmcqozIWI4frNDgUPW4fh08GQU2vzo9EX+5UDyg7FGVZeKV+/IC7+GHT+KNjpTOk6Cl/Wz81hrN1101LP5jt4usTSEw6jOL6tBapw3krTMaINJpdakdFRVSjuui9c0MsF8Ty/FG+iubAkRmHoP8WKlVsis880aAYE2K6wA7EmBIwRrBGQqno6zCQkztLc3dyMeEgD9yU58gOliDuWiIpyibyE8bf7BcxA9rqPeKR5aeP81VkaurxKVvzj6WvvQSOz+wd8xOemFFcS5kWhXhJhmQyoVwmeHD6mMD1zAG35TyklUQMwceIaUuxD8DLNbkx6Nf6ZFM7rKUC8OWwlt2G7ZGeoiFMUeeeClg/yWJ3Jc5amccazLYJjJ381iS0U2OD2dXbAXKMRLCE8DpjZEdw8LRmL3S/HPQhxf8nlDf9PvxaNZLWUpSf5Y3VAMv2iw34gubCnpEJURmxV/5U2R3KH1Mqm0NRG7LY0nXo046XSm4Wo1W5Cd3PMP8SGt/d1km5o0QsOFQHq4n8m5XfNILK+bJc5VmmeHgJEiJHhfovpCvNR11yri8XTwxIfWVgN+lf0/zmetDlga9+kx4UkHF3YAnqyUwtty15EmXMbV3LnOEAn2PZb1pwn6
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: bonsai
    type: kubernetes.io/dockerconfigjson
