apiVersion: v1
kind: Service
metadata:
  name: {{ include "bonsai-services.fullname" . }}-mailhog
  labels:
    bonsai-service: mailhog
  {{- include "bonsai-services.labels" . | nindent 4 }}
spec:
  type: {{ .Values.mailhog.type }}
  selector:
    bonsai-service: mailhog
    {{- include "bonsai-services.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.mailhog.ports | toYaml | nindent 2 }}
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "bonsai-services.fullname" . }}-mailhog
  labels:
    bonsai-service: mailhog
  {{- include "bonsai-services.labels" . | nindent 4 }}
spec:
  progressDeadlineSeconds: 120
  replicas: 1
  selector:
    matchLabels:
      bonsai-service: mailhog
  strategy:
    canary:
      steps:
      - setWeight: 100
  template:
    metadata:
      labels:
        bonsai-service: mailhog
    spec:
      containers:
      - image: mailhog/mailhog:latest
        name: mailhog-ctr
        ports:
        - containerPort: 8025
          protocol: TCP
        - containerPort: 1025
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 5
          tcpSocket:
            port: 1025
        resources: {}
      restartPolicy: Always
status: {}
