apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: grove-db
spec:
  serviceName: grove-db-headless
  replicas: 1
  selector:
    matchLabels:
      app: grove-db
  template:
    metadata:
      labels:
        app: grove-db
    spec:
      containers:
        - name: grove-db-ctr
          image: postgres:15-alpine
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: grove-secrets
                  key: PgSql_User
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: grove-secrets
                  key: PgSql_Password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: grove-secrets
                  key: PgSql_Database
          livenessProbe:
            exec:
              command: [pg_isready, -U, grove_user, -d, grove_db]
            failureThreshold: 5
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: grove-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: grove-data
      spec:
        accessModes: [ReadWriteOnce]
        resources:
          requests:
            storage: 100Mi
