apiVersion: apps/v1
kind: Deployment
metadata:
  name: members-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: members-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: members-db
    spec:
      containers:
        - env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: members-secrets
                  key: PgSql_User
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: members-secrets
                  key: PgSql_Password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: members-secrets
                  key: PgSql_Database
          image: postgres:15-alpine
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - members_user
                - -d
                - members_db
            failureThreshold: 5
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          name: members-db-ctr
          ports:
            - containerPort: 5432
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: members-data
      restartPolicy: Always
      volumes:
        - name: members-data
          persistentVolumeClaim:
            claimName: members-data
status: {}
