apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Release.Namespace }}
  name: cadvisor
  labels:
  {{- include "bonsai-observability.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Release.Namespace }}
  name: grafana
  labels:
  {{- include "bonsai-observability.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Release.Namespace }}
  name: loki
  labels:
  {{- include "bonsai-observability.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Release.Namespace }}
  name: prometheus
  labels:
  {{- include "bonsai-observability.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Release.Namespace }}
  name: promtail
  labels:
  {{- include "bonsai-observability.labels" . | nindent 4 }}
