apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-nginx-config
  labels:
  {{- include "bonsai.labels" . | nindent 4 }}
data:
  default.conf: {{ .Values.frontendNginxConfig.defaultConf | toYaml | indent 1 }}
