apiVersion: v1
kind: Service
metadata:
  name: visitor-services
  labels:
    bonsai-service: visitor-services
  {{- include "bonsai.labels" . | nindent 4 }}
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml --out k8s/services/
    kompose.version: 1.31.2 (a92241f79)
spec:
  type: {{ .Values.visitorServices.type }}
  selector:
    bonsai-service: visitor-services
    {{- include "bonsai.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.visitorServices.ports | toYaml | nindent 2 }}
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: visitor-services
  labels:
    bonsai-service: visitor-services
  {{- include "bonsai.labels" . | nindent 4 }}
spec:
  progressDeadlineSeconds: 120
  replicas: 3
  selector:
    matchLabels:
      bonsai-service: visitor-services
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause:
          duration: 30s
      - setWeight: 40
      - pause:
          duration: 30s
      - setWeight: 60
      - pause:
          duration: 30s
      - setWeight: 80
      - pause:
          duration: 30s
      - setWeight: 100
  template:
    metadata:
      labels:
        bonsai-service: visitor-services
    spec:
      containers:
      - args:
        - sh
        - -c
        - npx prisma generate && npx prisma migrate deploy && npm start
        envFrom:
        - secretRef:
            name: visitor-services-secrets
        image: ghcr.io/bharatdwaj3/botany-visitor-services:08e7964
        name: visitor-services-ctr
        ports:
        - containerPort: 4004
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 5
          tcpSocket:
            port: 4004
        resources: {}
      imagePullSecrets:
      - name: ghcr-secret
      restartPolicy: Always
status: {}
