---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-secrets
  namespace: bonsai
spec:
  encryptedData:
    GF_SECURITY_ADMIN_PASSWORD: AgAHYtIKXT+4k09onxLG5PjRbPyZoNiqDWU2yYVraBz8PQAM/meVXkLNzy9Cua9Lm6wLSX8ArV7CbZzsQGrzWhWTPSRPaoLbXOFGw+kGJvJEz/BcJK24iOWBYAJjC1pCSSKfxPLqw2yaIX9wjOlFOTY+w7+By2NB43g0d4ULZ50ZJv1qinXPipXqI4erLEQ7fxUj2MMSAF6qhKYeaWFo6vwyirA0O9PkE1+ev3wOdtMJtQoym7F/lnvDxDxR0KfKlDM/3BnBMyyUlTwiwpTDIPM6Bs0WhxhU6GIyKzyjfliji3LAFj9zSc8GA20GU9qNEOj/VkGG+olWVBTCyP0RjaaTDGeHeKQ+GK1XJPjswwKFVKydZ5XrxkJvsmbYq0WUz7SmRg/suhKm+bEuzE0UJGPMBLkeH8n13aUGJ1W/oE42jkd/PWl0vWmbEKy4QnmaXlmA36nckb4tn762T//EFY/66Jnhwf8MqofeeJgen70MVDplkUkH4xPvgIRs9IdyVm3N8uEDquf6xoIKfBjf5ovasXQvWlz/0yjD+xxjHHP91G8oPm2htVUONpdIZiAFaKcPR9ywOPUh8lm5wYp3AbSV0Mrpx6kxFZQWWdnKqxH79gQFhGxq+qo9d5mzs1a2NMRrqV/r5DsxspgY0F7+04G42YIwqqrGbD8HxjD86RNk9abZUug3UB9heN5qMTD8j9macqAsdcoc5eBElfBdWL+slFNX+UNmWgb+Epxk
  template:
    metadata:
      creationTimestamp: null
      name: grafana-secrets
      namespace: bonsai
