---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: loki-push-creds
  namespace: bonsai
spec:
  encryptedData:
    LOKI_PASSWORD: AgA5yGtyFJinjMjHc7eskPN75xdbhRaYUwydmzKA8JXMre1apiEQ1UNTodtZBekFxqs8ILG+VUb48sqPdF2ijy7ILhByjlx4OLXmuTbSq6Tb291PRDdzb5G9QR6wDBod4xl+jtNenrjl4PWdniIoGO1EIGsDRjxNkKuW6XXLzVsmfyfWrFPHgkOyGCWcJhKBLBrf2d/+9vE05TJyiX+Sjzkf2PPTbtJBvorKgYQ2pTtJeSlNPSiQC3iny00eo9P+zFigXY9asRTyfxxR3hdVVwb5iQzZCPIvDfHS4Z8BeK0Ss2fZc368GsZ1uSygQ9atoBS4cj/bzkxFWonxAu8kpmelV9RqaRB0wa9wI6L1ZdMPnMR5/WOp863meS/3FgW8u7zS2O7+roCMwF5yJZVgV1QuPbu9H8z+1ojmN/GJvuvwVX7AQRyIHa4yZoUFacuNTrNHtdciwXo41yXMycT/5zE5eW41ARAC8tbMqCvnCsXl0/nIp3cOB0gfVjaTefIUAcNgKXqSE3sTfQo4GDmh0uxC1GuoIbbqf3GsfJx4gd5jEevB+TozCEzgGsFFlnfNYj742ZTRGSvVQc/muQfNjft3423vamuHv9uGPVSLqasaGMvafA7UvTsJSx+mf40H86E+lz6iCOhuHB4/rKa9FLAb5JB3TuAdu6LPYWqxTMc+fmsjGfj/+haIeHqIPmXaxD1EuG4IfvL/WqvtRIWI0NL0
    LOKI_USER: AgBjOqbSZvnjuQiEod5XYyh7nZPihGmPkA/uxKIb6MIVrnwNRLSJlN8dMA6s4YgTBx5NAjwjcMaN+QeXa0qoagbtGfCWSLJdZEO/Rka1UnL2uLgjby1zjJJv+OGkmMRbONdtKwzuSr04jWWyLYt3k80xK9masiQAvySA+OJem4BArFXM6mebhFsIBHfxxE49GZRzeavC4NWu2Llgw9WT6UEdfoOwUXcLnYn8G0GB7+4bQs8haKI8pHVNlsqDnjV5/IHQLB498eecB8V1D6ttccYlYCNWFdivXDMZTTrFi6S3KjzFScpWRbWIYhRQyFScFCVhGKWQ2zmJJeAXu8Bg0FjOdNVOt3uaAORT9VXG5KUGtljH92bIJ9fY/7V6yauMZgOzEINkAht9ZhjjaZpScxm6B09vqugaNIv5Ce4ze1sUugbE7JjcbUJZMLynNVTK210eMK3GBc/HC5WQ+zXLvvQhO1jS/bONHX1tJd3wkP9izHNVBZf5xMtC61j3qQOz5oc43s++IuA4NTNOBBgd0WfDljL1n69GMDD9KL5NRnmztrvaPKQX6e6zWxYOdslMSc0Is9s9T4Adw0AoOLJ7ctvuDVjlymykvyUaDWLaGX1TEDwwXaus+iO5XpKPZSu4MwmJCdfHr7ri6qOT1zJwtAeCI7SJn7Td0oPsUZaqNsHeEF4Ti1gcWBur0skdxnc9FS9LCPQ4+S8hDP0=
  template:
    metadata:
      creationTimestamp: null
      name: loki-push-creds
      namespace: bonsai
