---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: prometheus-web-config
  namespace: bonsai
spec:
  encryptedData:
    web.yml: AgBb+LLLMN9DIqCIgjWFtfxBoneiCitFLjc9mHUjLpWJDjBrlak8805S1Kl9LRYhC+4Z5pSp9l/fnZ5ewbLB/wZiuAJCSsuWAY97e0GuS63SMkdcFpMlPSyybSUHUPyU/IwPqUeEfYThb35RF03gwueTkiUiofxsSq/31QlpIOodEw35hSApQzEIM//Dh4jGHkxhXiQYbgJHrLAeTmNRqhpx40ezaNz66lTsB1UIl6V6zSdBBjE6sGy+/FA/WKxDkZkqG3nnwCPBdtGxQpEQSk2SORhHEDvT4QZsxvPgRITx9fJ4MHS/hTQ1GgSSiUWLrJHepjRQdTHi9MXnVS1gOmDwJNgAh/efB/P6ljxeasX7ejVOye8FQ/8IaIq0zqXkPoaf0bPLJ9U+loHZ5e/WxsoDPkaox8/4jhAJufKTzxAasYg8FQg1nclNSwnBm+BpMIGeh0foTZgPZQBZkRk7FzRffLbcox8pchJ+DSkUJ+6G4glb99KbYvcHD1iEJgP9t/IE4pRAvE4Gv4gmKqa5N+K9W6KUzXub6L7WDbSCX1MBMhZnYlGsx8OC1JJptPnS6FYgh4fQj/gbzJjiVqRIIUU4Ou63z4RDM4FcDNepUiIYDUL0oPLJpgQvV1IvZkaXHcNZQBiYt1Zt/fn6Ai+b0ov+zDCTeW3bW3+JJquUROQ50W/15bscM5eUMVpY+meDKqFY8GiOmkJBJXgr+OMxKkalJTg03CWP8u0zifZUW4qrzJGRkQUAPiMW9utbKeQkFg6PCJSelcUT22czG/ZGSie6D5W5/lTx3DBRNBAELLwCdV2LbBAv+VNI
  template:
    metadata:
      creationTimestamp: null
      name: prometheus-web-config
      namespace: bonsai
