---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: duckdns-credentials
  namespace: bonsai-prod
spec:
  encryptedData:
    token: AgCpezHoE2ERWpCvb5jkzIopAcspAook5J+WyKAzOtUY6N5tJPXzc8R5RGGB59Gty9wx9OSoOMbjFvIc6HAdwq/4tiwNTAP0b3HGovZ8EfnQr1amczPBVjlN5VF/SATccK9iJ+dTyaTWL9NtkekHP12gvpqJqSRNCNe+nqS1tFuAqn8LPVUbT08RLVjYZkVTzju292JngPVRHwYUV6QT5XYkpOQ31kSYFQ7lMAZwtDB5MqF0iNJyY3+F2hWn41NG2wR7aqRsZ1Pqb3MBPib1QFQnUWhEa++cge+8wVtJiKs+a14o5MwB2PdKpq1sZXUN5Cy1rni5TdC562honljZiYWu8Iyja9sLZ+n/wxrxXsJFTBBRDz0FsOgaO1tcuigbfz0armPeaR2mfvySP7go6SPquy7QAcdS18KeB0UFdGkuHSl8gXWuDF9RBP0Zxtdq6eOa4D6RiBFcgpDs8kxf9LFCAvGhbjzGOALt1cKCK2U1et45B5bkBB4myZA01xvKYOs0a0xwGFdxjP1UH+h1EWPM5ZICIP35quJ1prlF3x18qQd0PZff7vPJpQ1Hr+VA6MmWfikwp1WaG+dstUqnTgCScEswPBRLEYYsQZ8YPkDMFXE3H8CSjXx7KKYjoZA+IBbGTM+ljFHzL21oodB5P+6F+K4ZfrHHssQyekzIXpK5GpX6PNKlDAoh8eKKFCCuiuyimz+2iwIRFuC/SSCbegYSUqTkjkZAAG+ZtbldtV1i+odz1UQ=
  template:
    metadata:
      creationTimestamp: null
      name: duckdns-credentials
      namespace: bonsai-prod
