---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: duckdns-credentials
  namespace: bonsai-prod
spec:
  encryptedData:
    token: AgBI6WjflJlPwma8XwIAwO9kZ7JTKEx/FKkfVln2hp6ThoMIMFRcx0/e4IbAtVVwoUh71HG48VYFc874rlQC+Ix0SI78VW3WN9z+9b+vUseeiGurmC452eB5ArA5/Uf7JXfxri4D0pd8DTUSZBJ9QMlTPgSQtl06J5oNLKdhaCXQi0oFNhOP6uSPVJ9ztSFOpt2eAeNeQSsxq5CcUcc3L439ccybQPDkXxD9MpOMidPXjmnvH8ts+TpeKf1iGCxD45PwO9VlfdGTd3EtjgXoNyCjktj9vS46qozyEV5OgmcfFq49byZpXXqEy3jJnJK/OD47xLHd9pYnTvvSra9G+MZxs9pds+wvljmx6wHXJ0FASJAqR5V6AmPlMfn855nBgBcu987pHcNoou7zpJOzSSzFFnkS4g5nIePYcKLyNnTFSFlIbNY0r/r9z+S5mpiHooUaLLH+fux5Mjm9ewixvShvqIhcMgUhGC5czZPyFPThkJlsbckkQbH4MEHzfe9i/C04LVZWxzGxAUJusvyaCU39vhDsgoLs2fTLOxNdvHhn4VX3tiecxO3bTfoXBcX7JGTsu1guxT62byL2gSp/fjNiZBxqXtidLiYT8m47X6auBJYFY61rBJWzzANNe6M/Z1RXuY4x5qaCTXqZ34CHxROVKe4V9iNk/jY+0+80W7BMlIYyWnarEgEfZCRv78ZVT4g=
  template:
    metadata:
      creationTimestamp: null
      name: duckdns-credentials
      namespace: bonsai-prod
