providers:
  kubernetesCRD:
    enabled: true
  kubernetesIngress:
    enabled: true
  kubernetesGateway:
    enabled: false

persistence:
  enabled: true
  name: traefik-acme
  accessMode: ReadWriteOnce
  size: 128Mi
  path: /data

service:
  type: NodePort

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 65532
  runAsGroup: 65532
  seccompProfile:
    type: RuntimeDefault

certificatesResolvers:
  default:
    acme:
      email: admin@zenbotanica.com
      storage: /data/acme.json
      httpChallenge:
        entryPoint: web
