apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: rudrashayan-route
  namespace: bonsai-prod
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`rudrashayan.duckdns.org`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: traefik
          port: 80
  tls:
    certResolver: default
