apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Release.Namespace }}
  name: firebase-data
  labels:
    io.kompose.service: firebase-data
  {{- include "bonsai-services.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.firebaseData.storageRequest | quote }}
