apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: marketplace-db
  labels:
    app-name: marketplace-db
  {{- include "bonsai-services.labels" . | nindent 4 }}
spec:
  type: {{ .Values.marketplaceDb.type }}
  selector:
    app-name: marketplace-db
    {{- include "bonsai-services.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.marketplaceDb.ports | toYaml | nindent 2 }}
