apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: {{ .Release.Namespace }}
  name: gardeners-db
  labels:
  {{- include "bonsai-services.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.gardenersDb.replicas }}
  selector:
    matchLabels:
      app: gardeners-db
  serviceName: gardeners-db-headless
  template:
    metadata:
      labels:
        app: gardeners-db
    spec:
      containers:
      - env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              key: PgSql_User
              name: gardeners-secrets
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: PgSql_Password
              name: gardeners-secrets
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              key: PgSql_Database
              name: gardeners-secrets
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.gardenersDb.gardenersDbCtr.image.repository }}:{{ .Values.gardenersDb.gardenersDbCtr.image.tag
          | default .Chart.AppVersion }}
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - gardeners_user
            - -d
            - gardeners_db
          failureThreshold: 5
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        name: gardeners-db-ctr
        ports:
        - containerPort: 5432
        resources: {{- toYaml .Values.gardenersDb.resources | nindent 10 }}
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: gardeners-data
      nodeSelector: {{- toYaml .Values.gardenersDb.nodeSelector | nindent 8 }}
      serviceAccountName: {{ include "bonsai-services.serviceAccountName" . }}
      tolerations: {{- toYaml .Values.gardenersDb.tolerations | nindent 8 }}
      topologySpreadConstraints: {{- toYaml .Values.gardenersDb.topologySpreadConstraints
        | nindent 8 }}
  updateStrategy: {}
  volumeClaimTemplates:
  - metadata:
      creationTimestamp: null
      name: gardeners-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources: {{ .Values.gardenersDb.volumeClaims.gardenersData | toYaml | nindent
        8 }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: {{ .Release.Namespace }}
  name: grove-db
  labels:
  {{- include "bonsai-services.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.groveDb.replicas }}
  selector:
    matchLabels:
      app: grove-db
  serviceName: grove-db-headless
  template:
    metadata:
      labels:
        app: grove-db
    spec:
      containers:
      - env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              key: PgSql_User
              name: grove-secrets
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: PgSql_Password
              name: grove-secrets
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              key: PgSql_Database
              name: grove-secrets
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.groveDb.groveDbCtr.image.repository }}:{{ .Values.groveDb.groveDbCtr.image.tag
          | default .Chart.AppVersion }}
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - grove_user
            - -d
            - grove_db
          failureThreshold: 5
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        name: grove-db-ctr
        ports:
        - containerPort: 5432
        resources: {{- toYaml .Values.groveDb.resources | nindent 10 }}
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: grove-data
      nodeSelector: {{- toYaml .Values.groveDb.nodeSelector | nindent 8 }}
      serviceAccountName: {{ include "bonsai-services.serviceAccountName" . }}
      tolerations: {{- toYaml .Values.groveDb.tolerations | nindent 8 }}
      topologySpreadConstraints: {{- toYaml .Values.groveDb.topologySpreadConstraints
        | nindent 8 }}
  updateStrategy: {}
  volumeClaimTemplates:
  - metadata:
      creationTimestamp: null
      name: grove-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources: {{ .Values.groveDb.volumeClaims.groveData | toYaml | nindent 8 }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: {{ .Release.Namespace }}
  name: marketplace-db
  labels:
  {{- include "bonsai-services.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.marketplaceDb.replicas }}
  selector:
    matchLabels:
      app-name: marketplace-db
  serviceName: marketplace-db-headless
  template:
    metadata:
      labels:
        app-name: marketplace-db
    spec:
      containers:
      - env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              key: PgSql_User
              name: marketplace-secrets
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: PgSql_Password
              name: marketplace-secrets
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              key: PgSql_Database
              name: marketplace-secrets
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.marketplaceDb.marketplaceDbCtr.image.repository }}:{{ .Values.marketplaceDb.marketplaceDbCtr.image.tag
          | default .Chart.AppVersion }}
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - marketplace_user
            - -d
            - marketplace_db
          failureThreshold: 5
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        name: marketplace-db-ctr
        ports:
        - containerPort: 5432
        resources: {{- toYaml .Values.marketplaceDb.resources | nindent 10 }}
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: marketplace-data
      nodeSelector: {{- toYaml .Values.marketplaceDb.nodeSelector | nindent 8 }}
      serviceAccountName: {{ include "bonsai-services.serviceAccountName" . }}
      tolerations: {{- toYaml .Values.marketplaceDb.tolerations | nindent 8 }}
      topologySpreadConstraints: {{- toYaml .Values.marketplaceDb.topologySpreadConstraints
        | nindent 8 }}
  updateStrategy: {}
  volumeClaimTemplates:
  - metadata:
      creationTimestamp: null
      name: marketplace-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources: {{ .Values.marketplaceDb.volumeClaims.marketplaceData | toYaml | nindent
        8 }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: {{ .Release.Namespace }}
  name: tending-db
  labels:
  {{- include "bonsai-services.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.tendingDb.replicas }}
  selector:
    matchLabels:
      app-name: tending-db
  serviceName: tending-db-headless
  template:
    metadata:
      labels:
        app-name: tending-db
    spec:
      containers:
      - env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              key: PgSql_User
              name: tending-secrets
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: PgSql_Password
              name: tending-secrets
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              key: PgSql_Database
              name: tending-secrets
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.tendingDb.tendingDbCtr.image.repository }}:{{ .Values.tendingDb.tendingDbCtr.image.tag
          | default .Chart.AppVersion }}
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - tending_user
            - -d
            - tending_db
          failureThreshold: 5
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        name: tending-db-ctr
        ports:
        - containerPort: 5432
        resources: {{- toYaml .Values.tendingDb.resources | nindent 10 }}
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: tending-data
      nodeSelector: {{- toYaml .Values.tendingDb.nodeSelector | nindent 8 }}
      serviceAccountName: {{ include "bonsai-services.serviceAccountName" . }}
      tolerations: {{- toYaml .Values.tendingDb.tolerations | nindent 8 }}
      topologySpreadConstraints: {{- toYaml .Values.tendingDb.topologySpreadConstraints
        | nindent 8 }}
  updateStrategy: {}
  volumeClaimTemplates:
  - metadata:
      creationTimestamp: null
      name: tending-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources: {{ .Values.tendingDb.volumeClaims.tendingData | toYaml | nindent 8
        }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: {{ .Release.Namespace }}
  name: visitor-services-db
  labels:
  {{- include "bonsai-services.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.visitorServicesDb.replicas }}
  selector:
    matchLabels:
      app-name: visitor-services-db
  serviceName: visitor-services-db-headless
  template:
    metadata:
      labels:
        app-name: visitor-services-db
    spec:
      containers:
      - env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              key: PgSql_User
              name: visitor-services-secrets
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: PgSql_Password
              name: visitor-services-secrets
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              key: PgSql_Database
              name: visitor-services-secrets
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.visitorServicesDb.visitorServicesDbCtr.image.repository }}:{{
          .Values.visitorServicesDb.visitorServicesDbCtr.image.tag | default .Chart.AppVersion
          }}
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - visitor_user
            - -d
            - visitor_db
          failureThreshold: 5
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        name: visitor-services-db-ctr
        ports:
        - containerPort: 5432
        resources: {{- toYaml .Values.visitorServicesDb.resources | nindent 10 }}
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: visitor-services-data
      nodeSelector: {{- toYaml .Values.visitorServicesDb.nodeSelector | nindent 8 }}
      serviceAccountName: {{ include "bonsai-services.serviceAccountName" . }}
      tolerations: {{- toYaml .Values.visitorServicesDb.tolerations | nindent 8 }}
      topologySpreadConstraints: {{- toYaml .Values.visitorServicesDb.topologySpreadConstraints
        | nindent 8 }}
  updateStrategy: {}
  volumeClaimTemplates:
  - metadata:
      creationTimestamp: null
      name: visitor-services-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources: {{ .Values.visitorServicesDb.volumeClaims.visitorServicesData | toYaml
        | nindent 8 }}
