apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: tending-db-headless
  labels:
  {{- include "bonsai-services.labels" . | nindent 4 }}
spec:
  type: {{ .Values.tendingDbHeadless.type }}
  selector:
    app-name: tending-db
    {{- include "bonsai-services.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.tendingDbHeadless.ports | toYaml | nindent 2 }}
