apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: visitor-services-db-headless
  labels:
  {{- include "bonsai-services.labels" . | nindent 4 }}
spec:
  type: {{ .Values.visitorServicesDbHeadless.type }}
  selector:
    app-name: visitor-services-db
    {{- include "bonsai-services.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.visitorServicesDbHeadless.ports | toYaml | nindent 2 }}
