import 'dotenv/config';
export const PORT = process.env.PORT || 4002;
export const JWT_ACC_SECRECT = process.env.JWT_ACC_SECRECT as string;
export const CATALOG_SERVICE_URL = process.env.CATALOG_SERVICE_URL as string;
export const INTERNAL_SERVICE_SECRET = process.env.INTERNAL_SERVICE_SECRET as string;
export const RAZORPAY_KEY_ID = process.env.RAZORPAY_KEY_ID as string;
export const RAZORPAY_KEY_SECRET = process.env.RAZORPAY_KEY_SECRET as string;
export const FRONTEND_ORIGIN = process.env.FRONTEND_ORIGIN || 'http://localhost:5173';
export const PgSql_User = process.env.PgSql_User as string;
export const PgSql_Password = process.env.PgSql_Password as string;
export const PgSql_Database = process.env.PgSql_Database as string;
export const PgSql_Host = process.env.PgSql_Host || 'circulation-db';
export const PgSql_Port = process.env.PgSql_Port || '5432';
const EPword = encodeURIComponent(PgSql_Password);
export const DATABASE_URL = `postgresql://${PgSql_User}:${EPword}@${PgSql_Host}:${PgSql_Port}/${PgSql_Database}?schema=public`;
if (!DATABASE_URL) throw new Error('DATABASE_URL is missing from .env');
if (!JWT_ACC_SECRECT) throw new Error('JWT_ACC_SECRECT is missing from .env');
if (!CATALOG_SERVICE_URL) throw new Error('CATALOG_SERVICE_URL is missing from .env');
if (!INTERNAL_SERVICE_SECRET) throw new Error('INTERNAL_SERVICE_SECRET is missing from .env');
if (!RAZORPAY_KEY_ID) throw new Error('RAZORPAY_KEY_ID is missing from .env');
if (!RAZORPAY_KEY_SECRET) throw new Error('RAZORPAY_KEY_SECRET is missing from .env');
export const MEMBERS_SERVICE_URL = process.env.MEMBERS_SERVICE_URL as string;
export const MAILHOG_HOST = process.env.MAILHOG_HOST || 'mailhog';
export const MAILHOG_PORT = Number(process.env.MAILHOG_PORT) || 1025;
if (!MEMBERS_SERVICE_URL) throw new Error('MEMBERS_SERVICE_URL is missing from .env');
