apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  namespace: {{ .Release.Namespace }}
  name: grove-route
  labels:
  {{- include "bonsai-exposure.labels" . | nindent 4 }}
spec:
  hostnames:
  - bonsai.local
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: bonsai-gateway
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: grove
      port: 4001
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /api/v1/book
    - path:
        type: PathPrefix
        value: /api/v1/storage
