namespace: bonsai

resources:
  - deployment/grove-rollout.yaml
  - deployment/tending-rollout.yaml
  - deployment/gardeners-rollout.yaml
  - deployment/frontend-rollout.yaml
  - deployment/firebase-rollout.yaml
  - deployment/mailhog-rollout.yaml
  - deployment/marketplace-rollout.yaml
  - deployment/visitor-services-rollout.yaml


  - service/grove-service.yaml
  - service/tending-service.yaml
  - service/gardeners-service.yaml
  - service/marketplace-service.yaml
  - service/visitor-services-service.yaml


  - service/frontend-service.yaml
  - service/firebase-service.yaml
  - service/mailhog-service.yaml


  - service/frontend-nginx-config.yaml

images:
  - name: grove
    newName: ghcr.io/bharatdwaj3/botany-grove
    newTag: "71cc8f0"
  - name: tending
    newName: ghcr.io/bharatdwaj3/botany-tending
    newTag: "71cc8f0"
  - name: gardeners
    newName: ghcr.io/bharatdwaj3/botany-gardeners
    newTag: "71cc8f0"
  - name: firebase
    newName: ghcr.io/bharatdwaj3/firebase
    newTag: v3
  - name: ghcr.io/bharatdwaj3/frontend
    newName: ghcr.io/bharatdwaj3/botany-frontend
    newTag: "71cc8f0"
  - name: marketplace
    newName: ghcr.io/bharatdwaj3/botany-marketplace
    newTag: "71cc8f0"
  - name: visitor-services
    newName: ghcr.io/bharatdwaj3/botany-visitor-services
    newTag: "71cc8f0"
