namespace: hon-khana

resources:
  - deployment/catalog-rollout.yaml
  - deployment/circulation-rollout.yaml
  - deployment/members-rollout.yaml
  - deployment/frontend-rollout.yaml
  - deployment/firebase-rollout.yaml
  - deployment/mailhog-rollout.yaml
  - deployment/catalog-db-rollout.yaml
  - deployment/circulation-db-rollout.yaml
  - deployment/members-db-rollout.yaml

  - deployment/catalog-data-persistentvolumeclaim.yaml
  - deployment/circulation-data-persistentvolumeclaim.yaml
  - deployment/members-data-persistentvolumeclaim.yaml
  - deployment/firebase-data-persistentvolumeclaim.yaml

  - service/catalog-service.yaml
  - service/circulation-service.yaml
  - service/members-service.yaml

  - service/catalog-db-service.yaml
  - service/circulation-db-service.yaml
  - service/members-db-service.yaml

  - service/frontend-service.yaml
  - service/firebase-service.yaml
  - service/mailhog-service.yaml
  

  - service/frontend-nginx-config.yaml

images:
  - name: catalog
    newName: ghcr.io/bharatdwaj3/catalog
    newTag: 4b4fc0e
  - name: circulation
    newName: ghcr.io/bharatdwaj3/circulation
    newTag: 4b4fc0e
  - name: members
    newName: ghcr.io/bharatdwaj3/members
    newTag: 4b4fc0e
  - name: firebase
    newName: ghcr.io/bharatdwaj3/firebase
    newTag: v3
  - name: ghcr.io/bharatdwaj3/frontend
    newName: ghcr.io/bharatdwaj3/frontend
    newTag: 4b4fc0e
