apiVersion: v1
kind: Service
metadata:
  labels:
    hon-khana-service: catalog
  name: catalog
spec:
  ports:
    - name: "4001"
      port: 4001
      targetPort: 4001
  selector:
    hon-khana-service: catalog
status:
  loadBalancer: {}
