apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml --out k8s/services/
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    hon-khana-service: circulation
  name: circulation
spec:
  ports:
    - name: "4002"
      port: 4002
      targetPort: 4002
  selector:
    hon-khana-service: circulation
status:
  loadBalancer: {}
