apiVersion: v1
kind: Service
metadata:
  labels:
    app: grove-db
  name: grove-db
spec:
  ports:
    - name: "7433"
      port: 5432
      targetPort: 5432
  selector:
    app: grove-db
status:
  loadBalancer: {}
