apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml --out k8s/services/
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    hon-khana-service: members
  name: members
spec:
  ports:
    - name: "4003"
      port: 4003
      targetPort: 4003
  selector:
    hon-khana-service: members
status:
  loadBalancer: {}
