apiVersion: v1
kind: Service
metadata:
  labels:
    app-name: visitor-services-db
  name: visitor-services-db
spec:
  ports:
    - name: "7436"
      port: 5432
      targetPort: 5432
  selector:
    app-name: visitor-services-db
status:
  loadBalancer: {}
