apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:7010
    basicAuth: true
    basicAuthUser: $__env{LOKI_USER}
    secureJsonData:
      basicAuthPassword: $__env{LOKI_PASSWORD}
    isDefault: false
    editable: true

  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:7090
    basicAuth: true
    basicAuthUser: $__env{PROM_USER}
    secureJsonData:
      basicAuthPassword: $__env{PROM_PASSWORD}
    isDefault: true
    editable: true
