namespace: bonsai

# 1. Automatically turn your local config files into ConfigMaps
configMapGenerator:
- name: prometheus-config
  files:
    - prometheus.yml
- name: loki-config
  files:
    - loki-nginx.conf
    - loki-config.yml
- name: promtail-config
  files:
    - promtail-config.yml

# 2. List the resources to be managed
resources:
  - rbac/promtail-serviceaccount.yaml
  - rbac/promtail-clusterrole.yaml
  - rbac/promtail-clusterrolebinding.yaml
  - prometheus-data-persistentvolumeclaim.yaml
  - grafana-data-persistentvolumeclaim.yaml
  - service/grafana-secrets-sealed.yaml
  - service/loki-htpasswd-sealed.yaml
  - service/loki-push-creds-sealed.yaml
  - service/prometheus-web-config-sealed.yaml
  - deployment/cadvisor-deployment.yaml
  - deployment/grafana-deployment.yaml
  - deployment/loki-deployment.yaml
  - deployment/prometheus-deployment.yaml
  - deployment/promtail-deployment.yaml
  - service/cadvisor-service.yaml
  - service/grafana-service.yaml
  - service/loki-service.yaml
  - service/prometheus-service.yaml
  - service/promtail-service.yaml
