namespace: bonsai-dev

resources:
  - ../../base

# Set all replicas to 1 for dev
patches:
  - target:
      kind: Rollout
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: StatefulSet
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
