apiVersion: v1
data:
    ADMIN_EMAIL: ENC[AES256_GCM,data:xWceTmESjpuiDOJO7jiYA91CrT9oEJ3EIJI+tA==,iv:w/FwF/ZTr9wpUwD3nUxikChnuaUFJqomLC1HGMbv8xw=,tag:1nFJOAsvgJ3ygCu/Msx1/Q==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:7sQ1rdL4VTSZNodn,iv:gR4cMiF5D0MZFG/Yroxh+y/tjOrmKhLeV9HD431usBQ=,tag:Wg6nz0K2zBNwlRvix2PqJQ==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:+wlPLuL1HTjJC/3Sl/bwOznJu5i7vpMDI8iqTbRM6FhIer33hiInP932W1U8/JgFSIpmZkNewgap8P6dYVjLDX3wmdmn4kaNq9H9FUh4ZXyh0HFaXNIZJyukRAGeywCmfFCc4QvugQSeHyhfpOQ7SXhQ0Uc=,iv:OXZGrj2W618cbZYeFO6a5rqCOwvzw3HXuxbPFgQBMcA=,tag:L8I73lVdMVpZRIh1vEC3GQ==,type:str]
    FRONTEND_ORIGIN: ENC[AES256_GCM,data:e/8IKPOUSIo2gpsD8wFnBthBoA2QYWvkYGFPKQ==,iv:yHknCpxTpLrUHW5a+lJpBopefPhEPXLvT+tf5bZBclE=,tag:s40nVAUU+Pd41VuSug+HUQ==,type:str]
    INTERNAL_SERVICE_SECRET: ENC[AES256_GCM,data:XDMLblH6I/frn/ZRFUMoeDxUOjPhI2YJ0zw15A==,iv:be+/74/fLspGLqfpPYrOMa+3FUC9lQfQ7Fh/t7NkiSs=,tag:+gtNHH46Rjo7q92PVohsww==,type:str]
    JWT_ACC_EXPIRES_IN: ENC[AES256_GCM,data:otvg8Q==,iv:6qiUfYDup7YtTdNk7hvvCV6qviSLQ9MfceuKxEz8YS8=,tag:lSFDbCfw/Ohase51mmrYQw==,type:str]
    JWT_ACC_SECRECT: ENC[AES256_GCM,data:Pgna6G9cZ00TN/Y/,iv:+83POGxx0BPBCHhputiKTpFKlOXwEul+iV18DvBIXCk=,tag:dP9KxP4UiHrOsMMuB7xuMg==,type:str]
    JWT_REF_EXPIRES_IN: ENC[AES256_GCM,data:T4SuLA==,iv:tY9GrsLJFV31F1P0LdTw3zUUlcyVljiDKHlZ84lK67Q=,tag:W3T9Yr3Aqa0vibd3nTi+dw==,type:str]
    JWT_REF_SECRECT: ENC[AES256_GCM,data:tDAzRvnJ+CUJrJ9Z,iv:QjZqwAJXxpyBuEdPwnUL10S7tcDAGgOIF8sN2C/6u2Y=,tag:LKxOMHE7PyrDGMBMDMTW6w==,type:str]
    PORT: ENC[AES256_GCM,data:WiMkW7n4JM8=,iv:fM67WTukPReNp8cg2j7p/xj9DHU3yOtZQXOVgM9fvAI=,tag:Jcq6ywk/6q+Wwz3c0H0OlA==,type:str]
    PgSql_Database: ENC[AES256_GCM,data:N8lHdwSN/Tb2FuMoB87XZQ==,iv:0OWqZahPX8RPVihdq+1Rnd0XpHpG1q3liZuJvU/eENY=,tag:afEoEcrXWym4Dgteo/YqLg==,type:str]
    PgSql_Password: ENC[AES256_GCM,data:i6wRufmjZ/EOQ6MBXQscimbfWgc=,iv:gozS73kmWqBrQXXP6n7zlE6GTFWTAqMTJIv7C5xiX94=,tag:GJVGp6IVFziaGrar97GQfQ==,type:str]
    PgSql_User: ENC[AES256_GCM,data:LVdTxMNBUH2dlrcKW1zCYj5gVlY=,iv:pk4ds1RPUglGpRcCRvljTCgx3vU5DE2J2XJfp53mzx4=,tag:rJhD1qdrl5Ps5rk4JETPbA==,type:str]
kind: Secret
metadata:
    name: gardeners-secrets
    namespace: bonsai-dev
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g2lray3jp4plrwd6x2uzhk2gq563kcshuc0xy962e4kzkg9789gsdrlenq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTR3hOQWllU1owenNva3Ru
            dFVCanZQNlE5akd5TWg1Q05QVUVXQ0JzRENJCjA1SEpSVmtuTHJjS3NaTyswMWpS
            cFIzSitjS0NaWiszVjU5eFl2RlBldU0KLS0tIERsblBrRlNjNHQwUmFhaEpHWGIw
            NVJOdHJzaDdSUFk2Yk13d1ovbmpCODAKK3KbQ8NGGht2XDPUE5j4ofbvQVctzYyb
            ayewbHRPjgzzonBAHrDcYItREEhjMr9TXt2Vvw4oKdQx0pw5mbzkDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-06T14:10:50Z"
    mac: ENC[AES256_GCM,data:2tcmyOA06/5GonNA4tl1DksUSXK0DSSNW7h3Z2gsp7zAIUpwn2X616X4lW5P+V2zP1cBy08hwS5RRyfs9Sske5Qobckl9akHztYW+rtfkIMzaBZeUYZ/dkoOd6TTffHvElbAe2vRq0iDDTd8rX9ZmgxbDQMGKReIonLUjpYEw74=,iv:QM3f9endDNlYnjJ6TVpmwqVSsX7eQj1r3qOcQ6TOE2w=,tag:Y6GuJZiVLpgrK2oc6fRuYQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
