apiVersion: ENC[AES256_GCM,data:SJs=,iv:A9ISQUDXPeG6USXFYfcTenao/UZtkU8tAuuLdDi6+Z0=,tag:jB4vK+kfHBEslW4ZjRQzLg==,type:str]
data:
    ADMIN_EMAIL: ENC[AES256_GCM,data:ml0ur0/hGf9AZAxH7jfQGuSVV70DS774hJhMPQ==,iv:SOQaoxrmw9k1bHuroseadv2+y67k6wX05ZkwSkzfTvk=,tag:faZNNM0n/6kTOIdQIjW++w==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:Dt79FmrlYFxM72mI,iv:De5KujLW63PGeq8Q2hfFjLh04VYhETmpWlGr/LFtjOg=,tag:QxF8PUWThX7XTEDWpYWVPA==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:EHBSETzRi5WMNeEJG+wTjdkT0puh9S6PEqmdbjktGuQQxWAkgNFXs2opCO88pMsXtKQxrjY0aqJ9or9b6xLG83/slQHgSTo9TiIIbaFnXX0fjq7Ss+40cUJF+nwdHQOo9nykr5BzIp4pQMeHGa249fE34bE=,iv:VciriBLJt0H4KY5xjVPA8VLpnLE4l8xIUNtT0JApels=,tag:j4DRjJt5GNC0zUmj0B8nvA==,type:str]
    FRONTEND_ORIGIN: ENC[AES256_GCM,data:h3ObUb7y3bVA0GfCHivJgTBWEKqMOHMhpTBl6g==,iv:4zXpnVV1UliecIIPnXxQziIIOJZ1XKFKBrkzN0DQUOI=,tag:fassHrTuJYOQauNzdHUYsQ==,type:str]
    INTERNAL_SERVICE_SECRET: ENC[AES256_GCM,data:38RYYE/xi5cMO02kiVdti/Zx5laB3PzMpPKYZQ==,iv:wkAjWj4+UU4XIrucc3ixdgVF3N3JEsEOjJfOALdQ9oU=,tag:3jb97M+CMVG6L8Up/6AAbg==,type:str]
    JWT_ACC_EXPIRES_IN: ENC[AES256_GCM,data:HWcvwQ==,iv:2wvrrTcmabzY+CzGg7f0u5Jz4NZ3GwTy7yf6o8YM1Ig=,tag:R7avVJ7hgHMg+LrJi0Ue9g==,type:str]
    JWT_ACC_SECRECT: ENC[AES256_GCM,data:roetYCToKB4wkVMq,iv:2hWUxdQBtQ/lGfnGLSE1v1VS5ZUYjFJhl4LzRcmYMGk=,tag:zySu4SXOjwwhR0nSqXusPw==,type:str]
    JWT_REF_EXPIRES_IN: ENC[AES256_GCM,data:BMpneA==,iv:GsyWYJaBRY5KSZciykCs2MkWqJ0nGazrUDx1g2q6c48=,tag:V/decydxyfKZ4YQvHf71sg==,type:str]
    JWT_REF_SECRECT: ENC[AES256_GCM,data:D60tS0JsWGftIMh0,iv:6G2Be3ZBBCjYWreqqA4jNbYwuPNVcKJPgBotl1kQ57s=,tag:lXnW4QY9nFb8/ZjEmcuHbA==,type:str]
    PORT: ENC[AES256_GCM,data:OvS0R/BCp9I=,iv:A3QpC2PPviI9JPMQ6UwUOboexzlLXNeiiXQxMMtTlv4=,tag:NJdjYMAEpl+nmefYBd7teQ==,type:str]
    PgSql_Database: ENC[AES256_GCM,data:dMaIV/olqAT8ns1iyYt0hQ==,iv:gMEWOVeiZ9xT5pkov/hF6hUFEFXIcNmuQgGm06p0irg=,tag:ejwFHvjG+YT+3fMZZK3axw==,type:str]
    PgSql_Password: ENC[AES256_GCM,data:IVJ3wKfSfZ9x5GkEjsQa5rYI9/o=,iv:Cbo20G0NT8GBhLM+lEcAryzi6eFnUGEb4PYZuoX1GLE=,tag:bYB1Y6DcQ7TweVWMebYt8w==,type:str]
    PgSql_User: ENC[AES256_GCM,data:MUJrnec3rZ5Xu6T9ChUxR+EAloM=,iv:BILfbhak80zS9cABnbpZpPbIavaD02fIPUETz//SwEc=,tag:bhokU8XMeZz1NZ4tOnJptw==,type:str]
kind: ENC[AES256_GCM,data:BhnPH7Hy,iv:hKBSuzgUkzbViCTBx8BTg+w3qFJExVpGEZ4eQLd7uJE=,tag:tRbsAbEF/6tHASh1bz2DJw==,type:str]
metadata:
    creationTimestamp: ENC[AES256_GCM,data:T8mjEra8OsH0TYJqrUYbH4xrzYk=,iv:yeWw4XI9CgR4kfJqQjjEBUbQt4zy+yoJqHOpKvDRnXs=,tag:LKgmjAam1tDipTRg3+9EsA==,type:str]
    name: ENC[AES256_GCM,data:+oFUrneOwvbLotbtIfvvoYE=,iv:2rxH3ii/IKz5dKI8YC7ZmRFPuSpBCsf9tgJC1Ks+REc=,tag:1TS5ypASgf5cK8m/cTeC4Q==,type:str]
    namespace: ENC[AES256_GCM,data:txHJGFY1CUKRzQ==,iv:5K768xbKpJUsh0XTjd46vqcJnfvcFRngoNLdm5iO/9w=,tag:Vznsp3rj1RyM4fVmV26+KA==,type:str]
    ownerReferences:
        - apiVersion: ENC[AES256_GCM,data:9MxO9eAQlEF6hBaRGOwR9kBbt8w=,iv:+NU8DCsLGWLUNdd47UXPoEQf/pug2NgvxQzS35QupBQ=,tag:KF9+yfXXMcujyLX5lAisrw==,type:str]
          controller: ENC[AES256_GCM,data:N6Q7JA==,iv:hxA7azuRatVw8FazqvfgOksElfMdFodfgtrZyuTRnis=,tag:ooUyxQc8Kkg9sg4Rp4c9wQ==,type:bool]
          kind: ENC[AES256_GCM,data:vPyqZt45pR46pe4t,iv:QOc1GLLvNMfQjW864p0qbZIKiKMsE++zPmrNVNghwUM=,tag:dkF9lTT3RE8+JM/c77NxSA==,type:str]
          name: ENC[AES256_GCM,data:3UMUXNhOAq8ATzrdaupa5/E=,iv:nAzFay4AlBnQT9lgFb3fcF5LqvaNEoadcvdSp/3EiR0=,tag:ghxfB+5pl0v4cYcaIybucg==,type:str]
          uid: ENC[AES256_GCM,data:eGUSh/ZDsT+G8XWgDbyVwOYN4kf6rrxm7l5LG6fAQ9GVM82Q,iv:kTStztDzqhfRb1sIhcyqy1wTgNAf2k7s1fmoIaz+upo=,tag:AynMDwF74lId5Y/WwiWhPQ==,type:str]
    resourceVersion: ENC[AES256_GCM,data:UkUnrCTkrQ==,iv:rWIozr0rA3wDgflTA9f/nPp2ax+1/IvBlRNsx0MPY2A=,tag:1x4WKaaKqONuKRdvtvS22A==,type:str]
    uid: ENC[AES256_GCM,data:4+EaAof/IJ5xlrXqC30b11lhAMRlkysUMvBrxFkM0hjPhu9k,iv:uWanl+CJIWIGhY+l142BYzqQPdkd22z6fRjHc4muqjQ=,tag:ltLSTUETrYbh4vx2355E9A==,type:str]
type: ENC[AES256_GCM,data:QWv+lnO+,iv:VMa75A2x7M+r/fu5MqTXNweQdGcWI9p1P6HcbJRjcVg=,tag:MWefwbseu2MU750lPXvPXA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g2lray3jp4plrwd6x2uzhk2gq563kcshuc0xy962e4kzkg9789gsdrlenq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtYTZrdTVWOGxwZlNCT2da
            bmFJTHRGTUVvT3Y4dG5EREFWVTZmQ3R0RzIwCm1CaTExQjFMay9NcGhsNy9rUmNR
            MExqSXpNMG5tTFBleWExVk4yOFNta28KLS0tIFRJTlR6dWNrem83YzZaU2JTMzJv
            UkVMOVFqTUtFWW1uYTJKY2Y1N3hUbWcKVH1+JS4TfvovaghRZzn8VGfuLZ/QrTZD
            bUN+j9B5mfX+Zf5gim5Q2z7VNbd9QyrHzZ7wrlDSdPV1f9ofe3X+0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-03T10:25:45Z"
    mac: ENC[AES256_GCM,data:A4tk8VZu/3Cj8mJINXFYGyj/mxTpc+TpXdonCIk+ByhWMSf4Q/cns+WE6KJ7UFJkCK2jrLiL6DvNrgUZlM4a0UyDyUZJVJUlfrYcdcvxTUudwo8SHGh3gsfl2MCH55qEJcAv2m/ods+CXHrwvm4kSBMKl0ujsYu7df+lK20H388=,iv:g4XYzb80rmzKQ31OQRmXY9gUeGPHfKhy7rDrGYunxHE=,tag:oRb3W+UVBGkcbgtkuOO93w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
