---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: bonsai-dev
spec:
  encryptedData:
    .dockerconfigjson: AgAfF1kcpQ0yjvTE4oaAFMZ0B2Yko3UHfHH7+jGYqNV+aNjIjTjVRQHIQVM68PPTiU2m7hRhrSPh2tCVop2JYayML7KC5Nf7N6Nt220ObkRy/ckIMCvIMY0zFYTh6GFuKiBplTYhMNoK5N7GrRBTVB5XhV5L/jTlOK8oamPD/Hg+MgZGPFDiYRJwjm5Ztme+irut4JMiZw7ZXx+WJcjN5YlgKxJIEyFMIVGB+/ABgttAtGyDDDPwgg09D1T06qWf6NR5oMk4xLAA93KfZ5eLEYI0ygREgQzE26eFsMQmW0+AefvQIH+pJ1WDtOIRCJG21TlNZntggwtrg5Wh3oH4SReU/IHHZApx5BRLq7YpJgWIh6siBeOBF/ytJjb5eoRFrhweEGF+3sbzj3j735lCxW/+PBRklqkrhBOgfhieLFD074+CANglfn/PKic9AukS+GY3oHrBgUVmMQeC/p4Oc921A4Wscykjw6zmvNHcWrYNDcFkd9HS8Jsx3JR9Gwp6dzgmrg7rqshrLMT6h9wXYHWnykDcCMUNkO9tkH7kPx9z7g0SCuTQm0QuDm7iLeVP9m4zdXwdS/xQxWMKiyAUmYJkGsx36YcyvrNMs4ijCfn1SvMUTXzq+/Cs8r5CLU0BrUcvlzNzakLM8VjbZRTcPaS/KMrjh8Ksv/G4O6ca1XyZFnm/h5ZY4mgEtXmOMHPeaaixegAdd2dg4wc2O+qWHPmTmRFCH2WsQB83PzELeqMZSr0hbgQiV7WZsX8vgjvRERIzXcSLKAyu3bgM2IoZ3PYXZXsMP+0HBGxOqQcAVMYnuMJ0EbunlEnAq+LUP3bJvlLVEB4tM5hSWnWx6+yWq0tK4bziVv6EHqQCCdDMTinU6YUNZetpw1L/tKUF1Y5ZK5shzpX0wVa2nANc6trYI5FMnMDHf4GBBE362iLybDpXKBe8akcWKJl9QmGZys7u5cBSOvPzfNyWQsknpNSCLgoVxZOiNiHZbkxIY1VitjZBB7+3v/TqiKoU0jrI
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: bonsai-dev
    type: kubernetes.io/dockerconfigjson
