apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:JvcLu/JZujavNFa2vy30SRp07jV9EYLReCYX4hL0XDrcTZvzIKocaKoPjwwiIGYJ+6ns2MolbD7FIMKhd/bhFBLBOA2bu7lupwWzhaaaZ+TzrhE25JZDxbx7RVoNgrW+teYiGSh5xMMnyDR6qFzJ//mBRW9f8cePOjmCWiiMi1WlA31Zwko83olDFmOBfPjXfvALkxkzcLZi3Mmp/Xfjma8orZ5HaRHpAi0Fds06cHQektPEsVZh6HXa6hMrk4vK6AstKga+07gaq2A3Lq48wPUesHwdF6TpC1K7i5ezEUes31Fjyc8Su3N4AI9Z+uVsys3qDf+67oWAGs7VNJvmr66090stuJF0x75CsKxP2CUpYkZ1FCbzheyOmbEl7+AK8VK+OaJOKz3Nfcws1FhVYHWlZQzvwIDpWM8qPw==,iv:hc1S6bFVqNvgHR6R984OCupizNDWhWYhDNg4sCfOYDM=,tag:rN1RdrS+Mx0d+kBbXU1erg==,type:str]
kind: Secret
metadata:
    name: ghcr-secret
    namespace: bonsai-dev
type: kubernetes.io/dockerconfigjson
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g2lray3jp4plrwd6x2uzhk2gq563kcshuc0xy962e4kzkg9789gsdrlenq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxNm5ncGF1Y3l3SEkxZklU
            OWx5RWFTbmhQY0JKalpsbGRNOEtXSGh3TGxFCjdMU0R1aU1DbHVGQjJoZ3VWeFhv
            YzZwYlVsVnlFcTJBaHNpTUM4eUJ4NzQKLS0tIDl0eDZYciszOFhmL01KLytUUlJL
            aWlPaTJJOGtNcWJUakhkaitXa2ZTVHMKIRUjVJreQ+wNu+zriYGloL0gUTK/fB+A
            1Zg4OyMtwnlD1XBDZ1PjeqL8I6iG+v9G98EXGnFGA3mfJl5gauRBwA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-06T14:10:52Z"
    mac: ENC[AES256_GCM,data:5pkjyjSXRjpljH97t8SYM/f8YuBnI83VRSIJU+uRmFClzWSw/8NdNfkC1z1C2OXhegikb46RckfGux04Gz6P3/01vndeHoVrwFbWcw7DiaeGeOuk2h8wNvjoC/UMaRwHy8JouaT7Hh+TPDP89HuPlzXXz6OguGqKEvzKyWxvIvo=,iv:jXKACa+OZiAZj0JeeC/xKy0ba2h8nWSep3WRMXNyEzA=,tag:OpEnytVo2miK8rslp5C6EQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
