apiVersion: v1
data:
    DATABASE_URL: ENC[AES256_GCM,data:vXKFGZKLreYvdY71j2zpWoP5SnpJuzCSHfDKtu3eQNsBZ7vkkV1YxO0lkVrjpyT7Lp7IHXKp5uIw7PHDc8lzkUzNGfNWOA20X+uLjUiwE1WzfUf9WGneOMqc5dwopOgyzEoliQ==,iv:z+54KvlflM+/M/k7zKgv1kWsIoj2l7C6wcepD8DfbxQ=,tag:AI5u8zE68bG7+SQwO3VRow==,type:str]
    FRONTEND_ORIGIN: ENC[AES256_GCM,data:lqNDzd1ztCtKAmID/XH9tJkF78ix4Od5xXFF1g==,iv:R7KlFykw1j5xUAjo14KQXBti+1rIdAc0aQsAqVqjG04=,tag:DxzHJZ3PtGKnhfkkbh1gEQ==,type:str]
    Fbase_project_id: ENC[AES256_GCM,data:cpKNwNC5ZUmGZ49nyG5xfA==,iv:pzINKzGq9EcclXOv7LfRLp0mqrJv9nUBfHzlnxSamZM=,tag:JaR9WzwThEZ+fl+XgGTXZQ==,type:str]
    GARDENERS_SERVICE_URL: ENC[AES256_GCM,data:sAXCm2rlEIN8Y9EDxMX/JV0vCedRaN/W0Otxmg==,iv:iOuK/hiVZ6mZu411uaZ6xhgFmNKbA1tTYPKRqiHq6gQ=,tag:gYYE8z7mw/cCD2FRes5x1g==,type:str]
    INTERNAL_SERVICE_SECRET: ENC[AES256_GCM,data:XDjmQQZAMi7+tLm2ej8sDmHRFkJb6QqsgRXa8Q==,iv:Uti1b2k1H+ogaA2bhT75ftteO7n6fSgLiPS+qjz/s2Y=,tag:cc35M4CoiGeqU1vozlI5GQ==,type:str]
    JWT_ACC_SECRECT: ENC[AES256_GCM,data:l/h7c3o12RfNA2EV,iv:pp8ZnusN3Uor+Xe6kawyb8Qw+6ZxHDKRADyMm5YNa3Y=,tag:i70R1VTVhqc7bkDHGPtVwg==,type:str]
    NODE_ENV: ENC[AES256_GCM,data:rQT5BOQDeIcY5EANq/as2w==,iv:lxk0YdU2hqac5TLVCb3WuW/EKV1CacjjKYqcezaGroY=,tag:AJwSl4KFoIkPA+AhiQkHnw==,type:str]
    PORT: ENC[AES256_GCM,data:2xXCq21QK+w=,iv:fI2mPVVvhHGmGtlO1dZJxHveNo31jiBvBHJAf1tHevY=,tag:OlvTv2YC6RznvgpUpnryVQ==,type:str]
    PgSql_Database: ENC[AES256_GCM,data:kdDDZCcvAjKgD1mg,iv:F8YohJdKkS6JUIm8WaLh8VprnYTyTjxxMRvy/JFHf9g=,tag:5cpF1NjRF34HxGsjXmdq+w==,type:str]
    PgSql_Password: ENC[AES256_GCM,data:YB2ULli5jUCZQrBlpfvOPQ==,iv:UcXZ1xEtvqwq5U0FiGX2W10t7nWibN5Ij5OMW8SJHRw=,tag:WZUzuev1JeUyC+34UnYWhQ==,type:str]
    PgSql_User: ENC[AES256_GCM,data:5MSH4X6KmFVYkNYPoL0C1A==,iv:tG+5ydIi2lYPmZ0GRmvw0rMET/gE1ZNjvZgcjer749E=,tag:BuKl+Kc8xcPuvTOjunV9/A==,type:str]
    TENDING_SERVICE_URL: ENC[AES256_GCM,data:ZnWKF2M+HtND7cR1DWlX8e1fn9vfMoRMG85iFw==,iv:5MXj5BuUgf2nNwJ/+1hbBJsUmYnJ1UtHLXz7+zVvQDI=,tag:PLg+nZ/PGWnjHCBRNTntZw==,type:str]
kind: Secret
metadata:
    name: grove-secrets
    namespace: bonsai-dev
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g2lray3jp4plrwd6x2uzhk2gq563kcshuc0xy962e4kzkg9789gsdrlenq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPTWEvSE01YTdOazB1K01w
            MG15UkJUOS95L0VxbnlWM1ZqWTdHVGZSK2x3CmVic0ZkYkFjU0VreWZXNjdvenNp
            VHQxV0ZuRldUK3E5V21mUjFNcm1BSGsKLS0tIHpvTUtJbkZsQmhXaC9DVTR5QWNk
            dFN1R0VtRkgvaDlEdDVydkdEVEtPTE0Kvtwc2tdBdvr7IigchQLnjAckqHJnRz7Q
            rBMKGcrWOjSOI0B5W/pWu2EhOf9E9wHaa6UkkGkLtY9fxJc/zZNq2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-06T14:10:52Z"
    mac: ENC[AES256_GCM,data:fxAEhpwGgWoJZFgkOfwc64LPfqO7fqBr0ZT6aJE91lXYHdSn1+tVsB7I2PF6WsB+hLH/KeZvhKiTLC1AePjqia+kuBsooxWST2qxlZPn6T7zCjOxUgJKK1COzjuCmWYDe2ZHNcL44B3sVimKGEVvDIcHb4tcAmabILm/67qMB3U=,iv:zhRl3jB27czCLDy7ZDFAXDW14Mvx9B56TJO8Uzi63Hk=,tag:SBBEfzcf1Va+ZnVClJ9BRg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
