apiVersion: ENC[AES256_GCM,data:vEY=,iv:XAasU54o6xu7QZwdBaCUvOJyVg2jZrlDdA6zHv+wkB4=,tag:dwiY4ITgD5U5r8B4tBrGBQ==,type:str]
data:
    DATABASE_URL: ENC[AES256_GCM,data:xZgyOFi6vx7Xdpkx5zNs4+3uAwNN4GSGP38kA47NT8PbxNatFECmlGXHbR0HfUZADZhwaCIIkpourXN22owJAru1WxkV3JV7V3HlewDmyNw9X1lAiI5dsQdnUH7WDcH1Cwohig==,iv:YdBhHSZiTFRuzAo4KHNy3YPrviFxgEcrrgHWx52iUu4=,tag:4yR00YL454qS4E38DNvM6A==,type:str]
    FRONTEND_ORIGIN: ENC[AES256_GCM,data:744k0J9qUfM3MkeN9riPowAp4bBDWPqvQ2BKxA==,iv:gEkkSNRvJkH7v8R88mrLckkIMEt+v6/rVxR+sIVYLwE=,tag:EXPabVT30vxeIvmsbjDaTg==,type:str]
    Fbase_project_id: ENC[AES256_GCM,data:OcuBnEbirL7Y6xdKuvYvtw==,iv:sjUqzS99fHjjoYOSmzoYFf6/krv/65tlLxm0uuFakas=,tag:Bx08liEK7dPuYtyXc9bX+A==,type:str]
    GARDENERS_SERVICE_URL: ENC[AES256_GCM,data:QzcOk10QbB2f24OmitVu+rqjz4mjAKPGSs3A6g==,iv:eKKtZtDhhc5i1R/EaRKF+meyzVN7J1clZhgIHt6SOKY=,tag:nUaKGE9pk23LQP4gN61qEA==,type:str]
    INTERNAL_SERVICE_SECRET: ENC[AES256_GCM,data:ML8ASCSUBRbmQc/DmvOhtLBMTxbrb+cxNc33Ow==,iv:3UIQwInWzZQ16XQa1S23k15jTu7/E8RY3Yh4Gqy5iuA=,tag:851Tf2VAohaHbTRYb79NOA==,type:str]
    JWT_ACC_SECRECT: ENC[AES256_GCM,data:ryAb/664KCG0SpyB,iv:sHVjXB/LFqt/5P4m/75xPe1YAkWNX+f8Fk19xB88AuQ=,tag:aDA+sKIh4pNV0E1zJuI9LQ==,type:str]
    NODE_ENV: ENC[AES256_GCM,data:ZFPXw8bjDrWsPamEI9HsXg==,iv:I/8sJVTjZKRAnyzjdYnmsDkEHnDov3Mj3uz36lp1nRA=,tag:dFOEh61G78Tqw/v1t7npIw==,type:str]
    PORT: ENC[AES256_GCM,data:fP7xgBZDvJQ=,iv:4MXxa8q7tWmkB+sX0NLahG8HpU+EW7E0bGG+175dUfs=,tag:W1jgOrwqgEKFJQ6442BGFw==,type:str]
    PgSql_Database: ENC[AES256_GCM,data:5aBLqvilSpdTMnt6,iv:ehCBsV61O+Zvz/uxnf9n+dMYlrS0JTGjApozLweGDgA=,tag:2By5zFzGJtN7ROOy5dWkcg==,type:str]
    PgSql_Password: ENC[AES256_GCM,data:qyxQlQce1iDHyFtEbyL84A==,iv:/fqbZ5AvaBwzC837JsCPXgtUMhImeeeXi6pLbxJHcQQ=,tag:JaOY/k/rgEvDrMak068D8Q==,type:str]
    PgSql_User: ENC[AES256_GCM,data:uJnnhAdtwK+fdUSrdmjcCw==,iv:VWmLcm8Z++pCF29RCcsCXUNJWSm2q0U85ngvOiHUA7I=,tag:P7K3D0QqSy0nIJUB/k93HA==,type:str]
    TENDING_SERVICE_URL: ENC[AES256_GCM,data:04dJzWFvOVArp8499T3tdLYvHk2C3Nt4CvUlGg==,iv:UsgHA3WcWWb7Je2a1qD/81TyHBc+AkMPeXBENjgpjd4=,tag:d5QGGOH4BYCYRkbX/eq7vA==,type:str]
kind: ENC[AES256_GCM,data:8wr7eUhR,iv:A8jC365pEePV/BgVhH07JYxM+NIFu96NFaf5m1t44Ks=,tag:7DC1iPdr4p1jzXmU+a0YGQ==,type:str]
metadata:
    creationTimestamp: ENC[AES256_GCM,data:2laflXSmCDKPtk91TC3jF1yUoJI=,iv:IQe0D5m7wDngPK0fU3hQwjx1N92fbimOi0O+KTufr74=,tag:LBWQ73A1aEcvR4QV1cNfOA==,type:str]
    name: ENC[AES256_GCM,data:netXlxOrwxvTXcU8cg==,iv:mrYK+qdrJ2NR2yXclGOEZEesozhCBtK7fTO3iSJYQa0=,tag:tsyHk875P2a8oqMPhmw+OA==,type:str]
    namespace: ENC[AES256_GCM,data:NUGsiltIdAJuow==,iv:D/YdKQhHPrNQVU3my/YHvvggu8DkChWIxwomHO53GQ4=,tag:GCfZTSeOP7+4uMBJoR5XTw==,type:str]
    ownerReferences:
        - apiVersion: ENC[AES256_GCM,data:jXCt1/SRCmkH7Sl6w6hGiCnfh7U=,iv:tBXzrJeckq7bs9lbBRWtnrsybpS8tpsJXX4rWUsAcAo=,tag:TIjUNHmFcRT8v5jx0ng09g==,type:str]
          controller: ENC[AES256_GCM,data:9reOfg==,iv:+qrasn/Afpl+NS8DEvdt3idUNQvnERgnRw3a4WVSjgI=,tag:s5v0oO4qi1K7ncRBlE4Q5A==,type:bool]
          kind: ENC[AES256_GCM,data:j0Ll37cNhUgW/qp4,iv:R8MdMgGioCOALC4HdlDN4HQoMBfBdEspfOSYS96d1Yg=,tag:VEKWED9fcVVnDbQurwYWNw==,type:str]
          name: ENC[AES256_GCM,data:vRrXM/+DRfygyz3X/w==,iv:pzY0J2D9HP5iIa3n6izeGeWfr88kdsOX1sysBj1+AWQ=,tag:0oW428wTF2B+XY5Jj1TswA==,type:str]
          uid: ENC[AES256_GCM,data:27+Yib3ZxL2tKk3qlt2xrweyUNqUE7PfLjnYoYGRIphomKXL,iv:2J08JjFB6LSkfm+HtXkGlYldihJWgbFG6TvOV7QwJ3I=,tag:lbed5DB1pGPZdL9CO0GYmw==,type:str]
    resourceVersion: ENC[AES256_GCM,data:Fo+WFJVCBw==,iv:/BpEy98AAkMa+qkn3LR9IMBXKe1bBwFGbGPJYRoo1r0=,tag:z4IueKhOgLhnHfDkp14Xbg==,type:str]
    uid: ENC[AES256_GCM,data:mxZUTPnFynsM8Mom1lMSHTFcKQd+rIaco4ePzIQwZU/Rat5Q,iv:RP2jTRHTUS2Efx0tfKwYQVqJ7QW9VJEwEctRq19D9jQ=,tag:5d3Wi3vPkKC/08SlJ0Eydw==,type:str]
type: ENC[AES256_GCM,data:m8w98wpA,iv:/ope4FrE0kcYTwVL43Pju6ltd6EDQKFT2q+MPXBZIC0=,tag:AetJLErKBLyL4iNUu9y7oA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g2lray3jp4plrwd6x2uzhk2gq563kcshuc0xy962e4kzkg9789gsdrlenq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCc3NSN0NKTk0wM2lMQnQv
            QkhuS3BueCtwNGhiWEhadnN3aXJRaktwUWlBCmtBdFBkcVZGVHN0Q25kM1lkaVZC
            QndUMXhWRVFEdlR2YngrOFZzV2tEZzAKLS0tIEx3eWhsUWsrSCtSeTFxMFUyZHdD
            d01uVDlBRlNhdzNMdjF1WlNINDN0b2MKCu4NLLXfx7xxYQv0WF3Wnhltw13wEDaI
            wpMlVydSBcvsIg7g9xasFZwfHFp9o//bpKOavcOAHKi64o43AVKbsQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-03T10:25:46Z"
    mac: ENC[AES256_GCM,data:cqdjAKsffxccc5iFoSRTpxJTGidmzHZTtx1JYj0kj3iQwbad/U2FOIK4E5RO3oFFf8EaFndoOr4foAFnNHYlxfKQu1hgBruH1CXh0MCHJIIisyxcsXKK9Xj4Moefq5w8fYd/AG6d0f5UFnD5cKwXAhc/xPe7jqSjS9w8S7XxjjQ=,iv:kGgbvaP9a2d1fcFLu10MLzUDlBNLHmYG9CAlYrKQzEk=,tag:kYFy7lenh+DcLwFvymaxbg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
