apiVersion: ENC[AES256_GCM,data:6Xk=,iv:arwx0UO7eDGs2tqm/toYANhBYNARc7G+lIy+zLBijC0=,tag:CvHmZAXsHMBD+MAIQQkXUA==,type:str]
data:
    ADMIN_EMAIL: ENC[AES256_GCM,data:Ghpe+hxD9Bj2wvHTWWywCd5iKtLornttccJx+Q==,iv:FEOvMV3Fnf2g4z53O7brnFSgVe53eJt1fVurhNxlcvE=,tag:F+HW5n0DA34KOUVbgsBo2w==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:WC6HpPlsVBmWnwCK,iv:BysOQbWhxK8Jl4vbQZjLg9Hq0wUxiEg9kMB0Vx0cXS0=,tag:X/Q6vgKvFXS+WCxIzMknLw==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:LzWZqIMpDvjkfIFIbLoZo072YLmqvac1O7KiaGUdKubnXS/Z+zOVmVPMH6ggqqhWFBtaouScSF4pzmsGH4gniQ9Lc9T6NT6FpQq7N9iCtZQ0uFwZRa5jSAE+HUpZU95iPa7O0ejI7XWF6wV9J8p8rXTUu+Gt9fb0zX62QJNR62I=,iv:+Dv4vgjh7CG3UMMO5IFBX0znFds1cRBUU81eLpgssvM=,tag:64LBZxr1/kqMFVmcDfcrNw==,type:str]
    FRONTEND_ORIGIN: ENC[AES256_GCM,data:QoNkqHHx4DRFa6xANH5r/+V8r0GYX5gH2e1jrw==,iv:J/vpN4PtgC1EhvrL5IuQWYjNk2Rk03uTzFAbujU0SO0=,tag:oryiGE2diezMgh5lOm7Kig==,type:str]
    GARDENERS_SERVICE_URL: ENC[AES256_GCM,data:b6e48q8vr8SxTa0fddjp0aCvQBzsMbDCrdXomw==,iv:kQYLDMpEQXgQ8Or2ZxG2G5vygRP9tZU5uYPf9f2Vhpc=,tag:LQopbuaZ9HWMaldvkAP88A==,type:str]
    INTERNAL_SERVICE_SECRET: ENC[AES256_GCM,data:TEQqtB50g/z4ljysXxDWaEnx/SzAPg9jYDDjBA==,iv:zdqNNrqGQNRr3MVsajk3Gaz+PXH6bLcHDbSj2SJOgf0=,tag:hgqLB9gXjAPlSX7hPTUqDQ==,type:str]
    JWT_ACC_EXPIRES_IN: ENC[AES256_GCM,data:5HQZMw==,iv:HlHq/xzWEshHuIcnbSYC8a2sSyliS75Dii3glB6Qcqc=,tag:lleh5xp0SgSdjDA2tQ62XA==,type:str]
    JWT_ACC_SECRECT: ENC[AES256_GCM,data:vrhLjkQ7FfyrgUS9,iv:9gga5fV7qrow5wxfivOmxbw3m3uc5W5s95Wz6rDXO4Y=,tag:XKR81CqF7OVeLonXrNa5Og==,type:str]
    JWT_REF_EXPIRES_IN: ENC[AES256_GCM,data:UEcSKw==,iv:oKwdECSl00zVid9v943LhuAaxt+LH1KNOjJl1nhHT+I=,tag:v8abgCvMkY/kAnEV6eY6lA==,type:str]
    JWT_REF_SECRECT: ENC[AES256_GCM,data:mt28dvQj59dfIdBH,iv:JqIIxoMu2UP+00K07RXTNc/OKbDqnSo9QZHCdQQdiOw=,tag:sa8v7OP2RtiNXFJXZo8pyg==,type:str]
    PORT: ENC[AES256_GCM,data:CLBamBtznjA=,iv:zzDdl93z6lcsc2t+xGGcJ8+UX0ySZ2sG/EW4LxiqL2E=,tag:TKkhRTv4kXw1l6bRuv2ypQ==,type:str]
    PgSql_Database: ENC[AES256_GCM,data:bKiyl7vOOT3NeA+sNmjomwSyllw=,iv:V7vg+yINsqmtwoyHSWlX2FFHlK05dISxhrpA4xcamss=,tag:HgJH1BMsSInimY+RCDjmyA==,type:str]
    PgSql_Password: ENC[AES256_GCM,data:4jjTUOYZLQgy99sINCNUxqtK+boiCeCc,iv:/brSno+jwRSLBqATHDwcdRY872VkTBUx+Mfh69TVL0U=,tag:c56g+aemO9LLy04HDQoTjQ==,type:str]
    PgSql_User: ENC[AES256_GCM,data:SZ/oHeOtIbyiO2Qw3mtxbqZYA+3tHBG9,iv:MpBwCTvQ4dk2liEablgBk1o8cPJyCLdcW4PKVXyIr6Q=,tag:ODk6tpf35iM3G9Wc7gdKOg==,type:str]
kind: ENC[AES256_GCM,data:cR39R2oF,iv:plfhIGPqYyChBO6d3JXQDu0osAtJv3PP/NS1nfJfQDY=,tag:WRbY4gXyfkaa/elPaxDJ2A==,type:str]
metadata:
    creationTimestamp: ENC[AES256_GCM,data:r/qq9BXxYTE5WolrBemWKcu1X9g=,iv:d+mdrgYLh+FXTFrGVTYyREuRM8ohGS0oNd5xalZj7z8=,tag:LD04xBKMJCrHfqLCDYzM/A==,type:str]
    name: ENC[AES256_GCM,data:h3TRHObvr4ToHMz8jY7OX2Lk6g==,iv:HrpGd6bofs7r3rwbPslt7JvawBVGLJgZ4KN3Dt7VHP8=,tag:cgYxqQQBDaQ7+Zv5D8A1rA==,type:str]
    namespace: ENC[AES256_GCM,data:mXBKqZqDuu8MYg==,iv:kIKD1rD3tFOl2Jr8mbYz9oFVN1Ztp7tWKnwhLTAl8Ac=,tag:G1cFPeNuySFYlX/I0YNy0Q==,type:str]
    ownerReferences:
        - apiVersion: ENC[AES256_GCM,data:LYZOIrvteTDRVwhJC8QL0eRjcd4=,iv:Yz6NwWf/KVRLo5j07/jZ+QaEYVQ/MOS01CuyhLAh2m0=,tag:3F4YLRTY5YF4AhVyg7wamQ==,type:str]
          controller: ENC[AES256_GCM,data:QCnysg==,iv:Yno60zWIXaYGZq7RRfTU5IO3OtCDGr07/ggTtTiGR80=,tag:fiU8ezi8XHMsC2Q2RTaD6g==,type:bool]
          kind: ENC[AES256_GCM,data:na8dKUY7Jddy0sFv,iv:AlcxA4ibQ6TcBVFKz7uhFS2FsgB+Rsu0clfEe+EV3Fg=,tag:lRz0RrCjWSwxL7kXgKJNWg==,type:str]
          name: ENC[AES256_GCM,data:+p+zWXHuafpgRKHMCaIBTsBcyg==,iv:0tbs7H9feCfNZX9/j7VVoO37c1QlKagOWBJ/SKNSSmk=,tag:6F/du9qu5GpoI1RGJCgKHA==,type:str]
          uid: ENC[AES256_GCM,data:DgPFn6jWbPnBdLC9lZoGhfluQK4onAeD06udR/YXmZoVcqZx,iv:nnsrELF+RgWsEqZ5rU8h/bBzR6EtAC60tteqHuO6GyY=,tag:W8FH+jWqkMme5cbIYMNxvA==,type:str]
    resourceVersion: ENC[AES256_GCM,data:rAdCqF56DQ==,iv:JuvGjSLx+cr0DjuqwXNAhYjqllSggfkqPAAGe0gBDRU=,tag:mRPp+Q/TP3a9iDoZsIg8eA==,type:str]
    uid: ENC[AES256_GCM,data:/gGGSAxHyIAADz14Pw3rRp5EuEmFNh+SqGpt8KERMB/3K8TC,iv:oEzHhn5BEXBmp0BNS44tnzaZfGs8g06Y5TrEAgedVZw=,tag:LeO29uEN2/Z/YkMqg07IeQ==,type:str]
type: ENC[AES256_GCM,data:NyWXIld+,iv:9cFgicd0u3jmdDFr/M3BPO/DBWY2ny+gs3tLxWQG/2k=,tag:fCsbDeWZ8yT1f+j8gtGltw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g2lray3jp4plrwd6x2uzhk2gq563kcshuc0xy962e4kzkg9789gsdrlenq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvSGU2Y2hPVE5CKzRTODJz
            bXIvUDBCR3pYRDN0QUp0V2Erbzl3V2laNFhZCmxaUnlIZE9oVHFzbkt3Zkl6bE1r
            K2RGbVdlNHhDL2FSZUdiZXluZGFDbUEKLS0tIHpqYVNXUVFlWVBDa1RUR3hWMWN4
            cEtvclcrTURHbHNYb21aT0ZPRDl6L3cKtk+yyleq1Z6ilLe4mqSs4KOgplgjdPZ+
            gKGMZfZQmFy8ivRRRDfcmcn0NTLKd+BuactJXZxOtp0KbGAelrNR0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-03T10:25:46Z"
    mac: ENC[AES256_GCM,data:NNVqxyq95op3gJSfZo4CSdHW+EnETT9INBt03ifAXGtNZcRFap5HaZMlh4hX1d9SGqlDSdMHj6kGnEzC56C3cpT5u6U54K0ydcl6/A0IPyvYr+7W6eqZkViHpMLq3rZssVoYDuXDxlz023sJW/hZUQ5kWak2uxvcI7lt7rA8kqM=,iv:YZxuaDbZs6qj94mhhnOnGQ6pKwRUBzsQwNGHTrMylAc=,tag:3W77ACs1L2VEBcJj9uXgBw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
