apiVersion: v1
data:
    ADMIN_EMAIL: ENC[AES256_GCM,data:v97T2PUycZeHsfnuyx7+IL0pOmWzHQFjKfmffA==,iv:CZe4OIOOJM52jmPyOrg+xTLOcYFtalU03irBgXb3fXk=,tag:8V/DwUw0N5G5VMHUYQh7Tg==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:H1Z2Ki0vzV/Uau5A,iv:lUQGAJdn/WcyAJ7lTDBdyJV/DmL8pMUTJ7rLQz3H9LM=,tag:NSTbznKAADf+xcxIGnkyDQ==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:sY0vvlO0di0o0RB2Vj24eK1x+LJnl0E5/vO0qIP5nKnAC1Urrhb2i7qgIYJBpmn0oLOr53wnR0zlsM8rHK671m0R37HZexBs8JouOYFuCQbZ5270WWsBAJALxZKgM6FA+gBxYbUxXWSsHbjwGuO+4R2BhzN9gTTCe6jDRIf04Qw=,iv:ALn+TTGESb2nwURWKeHvb0tf5GfUaIm3jxKWUnfOD2c=,tag:dglmE1uj7/pS9Re5yQytgA==,type:str]
    FRONTEND_ORIGIN: ENC[AES256_GCM,data:EhYSe3ec99dCoU+Wxh1FUW85SXHYa2DX2D9Eew==,iv:7onmqoqWJmVCI4/lrKXkdSMhcXeQjGG7PNk1yebWYCY=,tag:OXBfWtxC1CJkk31sJtfUCg==,type:str]
    GARDENERS_SERVICE_URL: ENC[AES256_GCM,data:w1prlCAjNIDuy2XJK5KkPGDhef2Q8WmJEJrdXQ==,iv:XW8jTwlTklHjNvPGivAmZz8SCnouhM7PQWdk3E9Pzew=,tag:ddR2bK71bl+ke2eiSgyz7g==,type:str]
    INTERNAL_SERVICE_SECRET: ENC[AES256_GCM,data:fPiq7GtZwkK3X/YRBBlOtT5S3ID4DzBViGyqUA==,iv:D1PmpJl9i0uD9No/VD9BYkWMlXeyL3n5ev1IsKLK3fY=,tag:a4cS/qTbdlij3B7cKvV/pw==,type:str]
    JWT_ACC_EXPIRES_IN: ENC[AES256_GCM,data:9h7GiQ==,iv:gmCMeYXvuvI5c7QMizcmnjisX8i5fzOgcy0D81KrXo0=,tag:Jnl0PMraKPgQsXMklT7WEQ==,type:str]
    JWT_ACC_SECRECT: ENC[AES256_GCM,data:BcW2dznA7obLUkCl,iv:4o1JbSiPSEH1RpsNmAlNlJRdOvSaQ1niw7FDxMtQB3A=,tag:mPi9ioDPy8MQXC4j5FTF7w==,type:str]
    JWT_REF_EXPIRES_IN: ENC[AES256_GCM,data:Zv05wQ==,iv:j1K8gCPngdK2JRV967Qfwr6O8fN6kvpPWKuwq9nKFes=,tag:qnufmMtGOdQ8GqDmtVgPZw==,type:str]
    JWT_REF_SECRECT: ENC[AES256_GCM,data:g4WhrfwoekllnRvy,iv:zo/xdF0KuYDKpwOV0g/rjamv7uhfNMbQXyJZhb+4TzU=,tag:j+fyr+ne4fxcjr7zENqsdQ==,type:str]
    PORT: ENC[AES256_GCM,data:U5Hn0UVZ6pA=,iv:8x+a/qMpxTp4msNBptac8DTXywSyBnMzFfcg9jlIWug=,tag:lyJZsOpOSBi44ZBNjSfIQA==,type:str]
    PgSql_Database: ENC[AES256_GCM,data:RAdU8EiGB+fUdSTshgiDw7UldtE=,iv:Ng5Lotoyx487aO1D81DxvwbDUuRnQ7pShmGcpxoW6fc=,tag:pHq3r7tyKOt7UZKIRJgvvw==,type:str]
    PgSql_Password: ENC[AES256_GCM,data:zeybcNNCljkjuVlfyyXSuBa/hYeSImi5,iv:ivmaqLf0ZiNOuZmqGf6/nbnkcdwDUCRTfu1W9MjPVYM=,tag:tK++F3wuPwoyrY755FmWOA==,type:str]
    PgSql_User: ENC[AES256_GCM,data:DqLHmDNswjfPOePsQAZHFajkcmJkX3dG,iv:UrwFY4aZZwsHDsyH686cAGxwITHaK+dtqAADZmaHOlM=,tag:QAgfNjj2ADOkp/IirMxzFw==,type:str]
kind: Secret
metadata:
    name: marketplace-secrets
    namespace: bonsai-dev
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g2lray3jp4plrwd6x2uzhk2gq563kcshuc0xy962e4kzkg9789gsdrlenq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBncmtyNFJtMHlMNG5oQXh4
            amowemFYZ1A0Qk9iYThPaHVRLzdlRmltZTIwCkVBUktDTTQxMnRKWE9vSG9kQVgy
            YVMzRGlyZlNJVld0OFZ6cHRoUUN1NVkKLS0tIGw4bXdBZ3c1TzJuc0gwcW00cVB2
            V0FST1BRREVIdEptaXpnOFNmSDJnMXMKvOzNaoruYqW/6qAdV9i8NWRwzhgypcNk
            txmF5O1D5IszG7rq3bUUMFqlyBjMeQuy4+TuCtUcbPdBp0FaGT8Lgw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-06T14:10:52Z"
    mac: ENC[AES256_GCM,data:pqvQ0bzPQOn683ZS3CQxkrMsMqhqnZgacGa9kzKFsTJoP3lFUZB+lagMDMJHD9GmKdl1Itss21+jjgdEWyIT5LI+p6+D6DbMPZuJXT7nG2tiDUTiW9qSzDAo6ychr5pCLBUB6mfgH3VavZz206lsIXrShiGMQ1R9XTJ4xSv0hWk=,iv:lcPx4wNsOGpPvD+896rPfCCtUbhEp/BaszHfiJfEXTI=,tag:0mfIEBTyXMyyFKukI5bfdA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
