apiVersion: v1
data:
    DATABASE_URL: ENC[AES256_GCM,data:VfqPppF49ax2zDvh1yHKfHy7PCT7yQeirwlu82MTe5hYek40cNMi4b+Tqoa78yepzu/TThfJIZosikbKCG6AX3+wNztA5WIZgF7125N3OUlFySItIONOfGOKc/Oh3Z2WhAcuFhgil+cRqpzr,iv:1ldVPQ9Rvg5ADpTOBYSEcLz/GtQavK+cK4fORUH/ZAc=,tag:PP2bEqI/LIdMuGNy/Ei3sQ==,type:str]
    FRONTEND_ORIGIN: ENC[AES256_GCM,data:aZldq/OJAdYq3gbiNHYmzsnG8nMu8BVX4is+Tg==,iv:yIuqYPKjWy7tlVzAW9BpIn1Se5GMUgRt5M9WhDYJ2Is=,tag:acEQ5uxPy9CrmvQAwDMSKg==,type:str]
    GARDENERS_SERVICE_URL: ENC[AES256_GCM,data:AYEDEvudN6iiZ8Ff9ki2XvMCGWcH6XW7oAfVYA==,iv:E8H4EGrMhQX/HEYspEJ3YEXvUZgTBXFc7ueyn6yueNw=,tag:FIBYO45l/DjizYYJvBN6ew==,type:str]
    GROVE_SERVICE_URL: ENC[AES256_GCM,data:m2dZl6lzhp5d8KBnrxz2WHIooftwfn5o,iv:7h5r/s+TU78kC3t9wjlmlcusCjDMP92ki73JRCr3hek=,tag:Ty/ReLQ5t8tttYLmj20Brw==,type:str]
    INTERNAL_SERVICE_SECRET: ENC[AES256_GCM,data:2XQOUHvSG/LnP62r71WTVJtXxjpjaHwkZM4hww==,iv:nazuepvKJuABL/y5mGIs6RGH54EFOS6YuHxerzwYzZY=,tag:yMlRmLG8LCQ/dGUqNysd7A==,type:str]
    JWT_ACC_SECRECT: ENC[AES256_GCM,data:RRAXkhJ5i6ShxkId,iv:dMrHoIMp1GNv0wlZZgopfmFEofh2NAjq8RKIfNCh3yI=,tag:ueQIcQDZTcGKpcEkqJyw7w==,type:str]
    MAILHOG_HOST: ENC[AES256_GCM,data:621mkgqFqPpa1kNu,iv:QLtWyjUiPPcz244cLl5RHoJiZPeRBmM0E7bTE4jSRzI=,tag:cXhhbV01jPzbfvsaC0nGdg==,type:str]
    MAILHOG_PORT: ENC[AES256_GCM,data:EsUNOKuPQgU=,iv:9EbMaWKcUg5wD6+MxVk9EjawHIrWyvEKK9JLuU9/Y9U=,tag:wDGCCp1O1LOw2LwV6Y/57g==,type:str]
    PORT: ENC[AES256_GCM,data:bOnoFK6z+60=,iv:1V5uLbnKXwLQ79qzsqTLSFZ8h2uBteuO659Zyqur8TE=,tag:9EzJfTaQubLvLU3QCaO51A==,type:str]
    PgSql_Database: ENC[AES256_GCM,data:joeYYyEjYKwt1Iwxvw0tmg==,iv:R5oSwmNegRcgjhABGXBaPqBwgSPTHuMeAbbqS9PMg7o=,tag:/+52m1hwsMVpWwit9TbT6w==,type:str]
    PgSql_Password: ENC[AES256_GCM,data:+Eh1nDEz4Hfx5GgY1TWRrA==,iv://WpESKiwy6L9xe6xKwdbSRSVROoHv9COGCKHsg72mE=,tag:1oKQzhpWiO6VoQZDfuJ1HA==,type:str]
    PgSql_User: ENC[AES256_GCM,data:av+Aj/wdLWcnTd8TxMkGkQ==,iv:OxsNLcnKbWdfKXUUZW3tM6Po7dbobJSMwuXsO6s8s0g=,tag:OYnKHPCQL+gOEOL/9yzD3w==,type:str]
    RAZORPAY_KEY_ID: ENC[AES256_GCM,data:vhjRtCpWClAgpw1/baPc8dZ82f8uij9O5L/fNjhen34=,iv:Jvb41z3n1VvMXgyunaZ0GIz5YQuXan1I+OQ1CugVF2s=,tag:2F9hCpPHD2PmjC1zFGxfcQ==,type:str]
    RAZORPAY_KEY_SECRET: ENC[AES256_GCM,data:v5bx3ujhmRzNM7fN4VLGXqmrFWRhksLpRlniUA7Ypi8=,iv:ekHczyvl6tXnsFZN8CzF0t35BnC1DSRuiUnUYci7oBo=,tag:lBbx/i5TFuYWdm8BGbgh0A==,type:str]
kind: Secret
metadata:
    name: tending-secrets
    namespace: bonsai-dev
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g2lray3jp4plrwd6x2uzhk2gq563kcshuc0xy962e4kzkg9789gsdrlenq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrVGlNUFlUc0VhaVQ3ZklL
            NFFucDVHWXBNamk2TkszY3pFbWF0MXJnQVJBClUyNlFweDRXd3huendUeDhWNk8y
            cWFsOE4xeno1ekN2QkdqZ0prT0wvNFUKLS0tIDJVZXpKTWh4VkVsZWF6Slg2Y21E
            OWFzOXNUam1RYTJFQUNCeTFXYWtvK0kKj1EmfEc/L4yj5PizGOa1mwz5q15TbK6e
            qjrMcdbeikRtc0AjEzHam7jtYNXl6bKgkdBMGrYx+JJtBtH02F+egQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-06T14:10:52Z"
    mac: ENC[AES256_GCM,data:qUrVuoqohWclJUjHnsegvdG56NG06QtbLxZwNzIOEiGzcWeLqoWsolJuu6y81B7V1Ez1jVJOK1hBHALkI+hD7guM1I8gW3cAifvWtGe7mI72L5mIw0RdgP1z9YQlQGuV8FLud3Ubt0+KvEXhxwtuSwCSBvW64ZcXYxVRfjSw2Ys=,iv:S5ul+lgL0uFNrdtbdwE82ng7N7Evfc5iTSGlfnk1xD8=,tag:v/DpvvGsPc4z8wOJHCRsBw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
