apiVersion: ENC[AES256_GCM,data:v2A=,iv:AwBuxy8VKwzF5wMCyaG6rh/mvi3A5SIa+EktmJ2dUY8=,tag:8YMMDzoJRuuoN816pehzvQ==,type:str]
data:
    DATABASE_URL: ENC[AES256_GCM,data:QpmaLs/9lw8EHqXWOSIhksor9z3qmim+SEayNiXQDsa/IPGsaikp7IopWCs4a3PmDxh7dJrOHfarQOp9/va05l2sWlPskj05Ed8bxdTkQxzK4a7FPDOfOAQcVI6KmGObFYSOSh5pbML6YEOa,iv:oJ+dZrmInvjPQ2UbXUwqTmDaq8pZhqcoX5wDZRg/Dao=,tag:sBtQ7jbaErBEJd9rY/vm3w==,type:str]
    FRONTEND_ORIGIN: ENC[AES256_GCM,data:rg83h3N62FshcB4X+v3+Zadie2psdrWOkoiGeQ==,iv:9C3amzLfmY0v1XxHWhNU17kDUg0jDQFCFe7Q8K24cvg=,tag:9QL8uT12E1mMuhtccEqiTw==,type:str]
    GARDENERS_SERVICE_URL: ENC[AES256_GCM,data:1lOQvH8zvoHXmxZCLEF8puvLONZyLzD24qmMWA==,iv:aMkUOvcH1ALCvP9+vRI2SGYbrZFQxe23Z8coDqiVLoo=,tag:Jp9ERtUfWV1HHCVzAGhw/A==,type:str]
    GROVE_SERVICE_URL: ENC[AES256_GCM,data:d77/NMKnXKXvLUcV6zx71aqsGulkED/W,iv:XjXPAQEmaLFPoZhDrKR6ek0vkHShZRK5XQXawZ/hhc4=,tag:92vEWXW+JGotcWimdiYGZg==,type:str]
    INTERNAL_SERVICE_SECRET: ENC[AES256_GCM,data:pPN//QbNCwGY48Z6+GTkTPFqdiU2CQK8LOZGHw==,iv:/B/l2SPow1DC3vWm73eggFTSDu2TB8QuZO7W827urxE=,tag:JdMq4DILaxV42MglCF3H+A==,type:str]
    JWT_ACC_SECRECT: ENC[AES256_GCM,data:cOQHijCYx4CwHcY3,iv:XjJWsa3X6I4rUf/X3tSqK0TxzfNjb5/+sad1Vg9r6x0=,tag:imEtCLNO9HOQ9CKEAzSM1g==,type:str]
    MAILHOG_HOST: ENC[AES256_GCM,data:sv/HzcdrH7/x44hb,iv:hFK0KYXjaNjLouLfz8gxJEAoAc+ofostnqIxCWr7gm0=,tag:r5WKXZrdqy/7KubpQ3mnQQ==,type:str]
    MAILHOG_PORT: ENC[AES256_GCM,data:cRVgYfKsFlU=,iv:4Z7I0G/4gIK6QbmU+4aoa7bEZq7cjOCbxu9eoY/MqOE=,tag:rCjKRRcUHdQMyyJSVMPd2g==,type:str]
    PORT: ENC[AES256_GCM,data:gLMpjMvtR0g=,iv:ficY6LRTjoLJuGrvv8d1t6bSLHxOnqWdDoFRlhJa/oQ=,tag:e3m8zrNAgOnWA85h5G5bYw==,type:str]
    PgSql_Database: ENC[AES256_GCM,data:jz3cc5fL6lN8gjeIu6oh/A==,iv:QvO65ZHL529xj7gPqt68fTSD56RXs+MYiMgAGeOqh5Q=,tag:IFqgUEd+v6cU6N++yYI94g==,type:str]
    PgSql_Password: ENC[AES256_GCM,data:a26hNVO7NT5vzkPFC4yUYg==,iv:jP7TWiGIlPCIdCTUKNYkQ82t3irTtPzpteQcpYXrHcE=,tag:kU62m+CauVmM/o1Jh8GzDw==,type:str]
    PgSql_User: ENC[AES256_GCM,data:O/FMgN3k2ZXBASd5nkRMNg==,iv:arMWuxoC2OItMA31MjEfnkwh5IsYPKIHaTurpr+YaIA=,tag:LFKFvlzqVTDXiWNhFdrJ6A==,type:str]
    RAZORPAY_KEY_ID: ENC[AES256_GCM,data:ARQioHSQFHs3lk7LNiP5i//h497f+F3zqBxv/w5ZYJI=,iv:NwL1RPpr1QAS8NDAqqZdHUL/GH1vlpblqcESgYJvjhw=,tag:ZR2ugSJU9ghoxEFUmbLa9w==,type:str]
    RAZORPAY_KEY_SECRET: ENC[AES256_GCM,data:THu6LdzqjJtrTPO0hc1QyKThYPJJy1MmRUH/IIGsyDE=,iv:V6fUedzuX+ISXYntgyVll2iG1ysBS+AphQibu3t4fw8=,tag:Rhftiw6il2GfFNCYwolW8A==,type:str]
kind: ENC[AES256_GCM,data:jQBtepFz,iv:CV1g4UhqPPclbf8Ha9hkYv/rp0hJp9/gdAZR1AO7hXE=,tag:DoNrZwnhI+8RRNwsEXXP7Q==,type:str]
metadata:
    creationTimestamp: ENC[AES256_GCM,data:awqooMpB7bwP0xj6w9VXIy3tKQk=,iv:nQx4fUKUCELfxG1Dr6XS2Xiqc3sa3KDPx23aMe4qWhQ=,tag:PzoyzLjrE68PFmK7ioIOZQ==,type:str]
    name: ENC[AES256_GCM,data:MvKLN0UWg/EaBcwd6/AR,iv:dLyfOXT/pWqefiBaS2uwt87SUUHZRG1YkjpLNeMouCU=,tag:aa5pha9hSl0Doo36ln4BwA==,type:str]
    namespace: ENC[AES256_GCM,data:rxf2DRI9BTljQQ==,iv:qeqBTiNbNhe4fUgNXcC0Mfimn4SnUBUljGyZcQU8H/E=,tag:4DA71FIloU9ZT6XUlupbdg==,type:str]
    ownerReferences:
        - apiVersion: ENC[AES256_GCM,data:i9z1gUxySLoLStWQxdPbMfMFKfQ=,iv:GMenHawH9H4korDxfYwtN7jBX6jdKS6qFFuqyMa6H44=,tag:61P5PVbTItMQPjYARZdd9Q==,type:str]
          controller: ENC[AES256_GCM,data:q85obA==,iv:JdpcZXhPxDTFSwESVvu4kpS3LiVx2QgBeUvmPk6hw4Q=,tag:8wVcxBkdtQtkYZTeXG3bAw==,type:bool]
          kind: ENC[AES256_GCM,data:VbK2JpJnmBkFRM0D,iv:4hP1LBnFeJkL/AbjSU7FKUC55P8nBbmHvz2qlUQmJ3Y=,tag:5Rxgra2vpXZZ4+EtW2PxpQ==,type:str]
          name: ENC[AES256_GCM,data:6IVbcwlm7rpFcxAkVvvA,iv:SVsyBiY9IU26RBZVA5Ki1z9MLiD/cBe8XkXTb+awVoc=,tag:85pESge+mPRFCRUVr0pNog==,type:str]
          uid: ENC[AES256_GCM,data:7Q/vqykyJGNDGGLrUxviC/LInNBkYykuXvb304z0SBbK4x/4,iv:kcVUjJkRPPhUXJrVOEJCnZFHD0TKCqNBqR1N0PSQFE0=,tag:bji0qagizIQ9TaQsWGscLA==,type:str]
    resourceVersion: ENC[AES256_GCM,data:bSWD43QRWg==,iv:kfUrw7I2Muo2QMvLVoa/6OTSp6ecoszhg2KozDiUVfw=,tag:whoFd5kO+v/ngGnizbVQ9A==,type:str]
    uid: ENC[AES256_GCM,data:0aVqIInspp4tgxhvQ2J8lIQ/XWIzMtAxLjiCh9uYnYvx5Nwc,iv:w+r1hYJ1RhzHZJ1wWzTdBhvQuezeH8XGUUyLNwUz52Q=,tag:ezuF4GqEFtYfyRxyj+h+Sg==,type:str]
type: ENC[AES256_GCM,data:HIUjnlQu,iv:lY8tPKXoGxt2xH2qla06Q+dlqZgQhq5XlH3q8cZUkHw=,tag:WWa5oPVoN20sqq/yqGnqdw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g2lray3jp4plrwd6x2uzhk2gq563kcshuc0xy962e4kzkg9789gsdrlenq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwVzA0TW03Z0ZSSWRQRUZv
            SHAyOHc1TjJxOWE0dG1zVSszRWdvOG03ekhvCkk1TjZjeTVZTjg4NTQzc1BTWElC
            dmhKb1I2Z01zc2RMdld4bGZ0a2RBY1kKLS0tIEtHdFVPU0ZOcEhZUkpJbU9PTWZl
            NjliRFdPdEJVVGN0eTFoaDZZaGdNL2cKjiGOXKi5f/wHMPu7BN1j04ZDWpFJf/s+
            M1tJ9UgYTGqLg4DCCflt7p0I4+kuPnaNWxhRjowyUY7TEiYUhVjeYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-03T10:25:46Z"
    mac: ENC[AES256_GCM,data:HTo1s2Mm29SKPnwhMLrSbZB3uff41B8f1L3/jO+oQsczeUngpXXBFvwxnEeHlbiHsgbVe19e9WJ7z9oiSfqpu65fad5azHtT6XMOppZSxh6dmktFCmAqjV6VxpN+ptdwb4ioDRgwnAGv0p+YP4kszd3Se+nSNMxeKkhLw1arV5Q=,iv:qsBes67rkOIZztRvAwtAw+TdXWO/WZ8+XMbwxYKiBas=,tag:IOS9Z/pB/qQ2hgZsUaGNxg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
