apiVersion: ENC[AES256_GCM,data:YPk=,iv:1ty/rZPqFiYEzGd0WCsx/rsSyHClj7Mq0ElRtTi65pk=,tag:5w1W0O7GKFNov9ljs/1I/A==,type:str]
data:
    ADMIN_EMAIL: ENC[AES256_GCM,data:lZ8Wqu/dP6yq4GLAZiavPh6kDX7c/7/mZfV/uQ==,iv:0b1XL81Cdq1n2r4cwE/xEwvxlpBImF7YZbDJXNfXisw=,tag:+jDFYZ/L+38YHFfWdh1XAA==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:icSmr7onBCVtqP6w,iv:ayZs3df71tDk5SWt1EfUjI15VDEYpmAW8Z49A/88GeM=,tag:2iFPqX9BgHznntu1sMJl+g==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:isExoMG9vZARV4ZL1ZMFh6VKqfTk6IUe3po9UUQM5HgsJJoKRVCixCo1oUNn9Y4bRpEvLU2vplifIWvgX7t06mk32p9qgXkEAz8HVc7d5y+ttBVFnZkscFqnmKf1cPTYYeLr7dwRx4sSbgf83WOCkVHugVAJoLOF,iv:COy5XEJsCZFI60f9EyJHOY6QcebkWDN0Bu1T20yN/4Q=,tag:S4g4L+3U4UuvAuY49rpZMg==,type:str]
    FRONTEND_ORIGIN: ENC[AES256_GCM,data:Czdey4ZpdxEJim7ZfB+3qykSPxbZp2tEiuSB8g==,iv:+H0jg2ix/Pa+JKKhZc0t1e3mZPLWRzSeoja8FuqUHIg=,tag:7v2ZhVR2n2xvsUG9/mkd4A==,type:str]
    GARDENERS_SERVICE_URL: ENC[AES256_GCM,data:x1WNJnSEhjobulZk2sboR2tNDRPQ9sBmC4Le6w==,iv:oAFjOaJwp32RWh+FmfjbZAH9uckhPs9vep7W3E04DYI=,tag:Rs9WcKnvEjeZ0B42Ks82EA==,type:str]
    INTERNAL_SERVICE_SECRET: ENC[AES256_GCM,data:txMt4mqWIBd4+perW0zyDL28lUj9SrZZZPp0hA==,iv:c0aBVFkqilla2cycm0dvvHJo/GmgIBPrIpWR3R4Q+IM=,tag:7/81BAovrn4tRRfzfP7RNw==,type:str]
    JWT_ACC_EXPIRES_IN: ENC[AES256_GCM,data:sLDrSQ==,iv:NuTjviAGv9W4abZoyuQx6V3e9aOShQAmQLFZrNc+3Zs=,tag:OFlqZ5lt9mKbMFSBOBduDw==,type:str]
    JWT_ACC_SECRECT: ENC[AES256_GCM,data:zZCQ9V7vF03k0Ho+,iv:/N/8gKRTWL3g1d9hMm63Ehe7JJbfEAaNn5bZN6KUujM=,tag:MAcPcii3dfJsNsgmYxjydQ==,type:str]
    JWT_REF_EXPIRES_IN: ENC[AES256_GCM,data:bNcStA==,iv:Jx1I7v/TmjAbLzwYPqvoVMJ1bLjaZIqo3CL3gIRbE4g=,tag:REdC7nokUA19GmnC4ueeBQ==,type:str]
    JWT_REF_SECRECT: ENC[AES256_GCM,data:rZv5Qh/j6huvUMou,iv:1RlGaiG+WsnwfmMsJHsb9Gil1YVu/2XR4Clmm0v6cmM=,tag:pYuum3VGMK781z1S46u+NQ==,type:str]
    PORT: ENC[AES256_GCM,data:yIe2W/FYzz0=,iv:gBL6swno0fH+h2JiN5CfT0bqWobtQbvuAaPARgxyuWE=,tag:y2oLeROiczz9ktR+0V76LA==,type:str]
    PgSql_Database: ENC[AES256_GCM,data:tub9CijhfRfJj/QCsK4AFQ==,iv:c3/+7JaqTQZOUftzVFE8q3bFfpDRxzrLfkPr9Nvx6h8=,tag:GVpay1WMeTvouPOriCq/hg==,type:str]
    PgSql_Password: ENC[AES256_GCM,data:V19c0nQF1FnV+H6PZFFRYA==,iv:dhM4cPjaUhpv5bU65hswriIAWXOlJcGvpN9ZpHwvQhA=,tag:QMNHLwbxM3vv5p0M1BrdKw==,type:str]
    PgSql_User: ENC[AES256_GCM,data:SqiEVgUr+58S0gYg+Q70iA==,iv:0TKjyaS0IwqiOxBapkBTbBp70ANYAORjAHQIjyzbgY0=,tag:9QmATrsX0V7QORtY1/gAtQ==,type:str]
kind: ENC[AES256_GCM,data:Yhk/CBXQ,iv:qarMLEbmVtlcsYmhTloI1AmioAch0C0fn9PDiP/Pjfw=,tag:quz862cLlg5jW4N2MftSxA==,type:str]
metadata:
    creationTimestamp: ENC[AES256_GCM,data:DM+iD5n34T2FeLpRsVNARfLJwAc=,iv:3OGvszjIAzNKa408mLBJqEm5w5VUGSQDl+qFHZjAaRs=,tag:YAcaaCxWbByxaJaw7FvsJw==,type:str]
    name: ENC[AES256_GCM,data:7VkuYV1L1+a4l9mqYoZs1Ri2BWmXSzfN,iv:CSSQqXLy3vdhDtdAVwiwFQbaoC+YcpVlmd28Jnw8H3A=,tag:2kWpgpB+Yrggnq1Je41Y5A==,type:str]
    namespace: ENC[AES256_GCM,data:KlgrrxbEkWTsEw==,iv:UFSJNTzgJeTdIs3qt/rZDkJhofr2ttDzLrsDOFtJjRU=,tag:7FLwHDPiPdJLDE/BbIK1dw==,type:str]
    ownerReferences:
        - apiVersion: ENC[AES256_GCM,data:m0qsXd7OJVW2YB9bUG74vbZquCs=,iv:aAinwIuc+EJLpkeC4XWMPT33TTR1SWL3XquMDEsW+l4=,tag:KToHgrccyTcEdgWQm1fM5w==,type:str]
          controller: ENC[AES256_GCM,data:HtUGoQ==,iv:i9dTwIAFoJ1cZ9rSkjiLBFGXzYDSrrzJwRST6Mhsm/M=,tag:Xvh+UOMROOaZHY+WEKKFaQ==,type:bool]
          kind: ENC[AES256_GCM,data:PLIRNtyTFxw9LTrj,iv:thTvA9gfQjnqV+DS6A/7Hr5rMntojyeYjjb7+4EkE0Y=,tag:SDhMI24FOWGICIHszCGAxA==,type:str]
          name: ENC[AES256_GCM,data:2+vmDJWxcXbDVNjgV6sB+y0IvYdueW38,iv:NFuF+kys3L/yo8V+Yns7X72aF3bLRcnlEj6j0TAZfwU=,tag:yEaSBRLY1ZVmpVDdIHbRMQ==,type:str]
          uid: ENC[AES256_GCM,data:iFXdG2z67FZco8zImr4K0riiVy4NHyq/RO0SQvZpp1a6khMH,iv:Cg6+9qQL+F+kRldvfeE5ZeHZgZbt498Veh4sBGFHvb8=,tag:WKuTljB5kuJs9tMx+pgQuQ==,type:str]
    resourceVersion: ENC[AES256_GCM,data:VO5YOozEow==,iv:qvJvosQwzU8dTqmww5OaIZSYhiNw9haXQM/cxmKw1No=,tag:6JFF/rjEbxE7f4aCYXXN6A==,type:str]
    uid: ENC[AES256_GCM,data:exiwKzCKQzMnsmAL1mxDLqina7vvtwnaoZTJolk7r3xHQmgY,iv:dVjMSsvMTFctQ74at+WvYxSGmAh529oDX4lpMOM0bCg=,tag:JTvf99lnIYibUe2imgn5CQ==,type:str]
type: ENC[AES256_GCM,data:CmHdB0+A,iv:WjfrKsA5bqzJlB0l6qmagIbQ80SaeUO87dMOxKJFZSA=,tag:FACyXKEKanBBPTlEtPupjw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g2lray3jp4plrwd6x2uzhk2gq563kcshuc0xy962e4kzkg9789gsdrlenq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5WUVqaDUxYVNFdUVFYzJ6
            L1UwbWROQXozdW5JSjEvV2dUWFhYUFBMaTJnCnpodnl1S1JsVWNpUkpDanVYRXFJ
            ZU8xRGMvTXNGdWVveC9FOHluNk5jd1EKLS0tIG9mWHZKayt6TDVQTHIvdGVwNzla
            NkdJUlJVUEdxazNkdTJIbjN5L3JjZ0kKEasa+c5U3ksHlSgac+9mFNAtY57bo+C7
            eoRtNBX3rEUOsSOGYowoxZcjgH6lleBR2Ij8Q+4i5oiO2pv+6qethQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-03T10:25:46Z"
    mac: ENC[AES256_GCM,data:35CydByU2+kNE/m14pV46AjWJtiP3hvWHmqjs3doECiXrUxTUz8DEQaP+iKzIXmVJcmEmJ5gkAZsWCbA1lavrKE/I0gBL8t6IDydn/ppad/HaYBaSPChNBImYkDyg4QxYWIkLUV6Qa1AIadcv9Gq7mqO8qKUkXad/HUg5o10mYU=,iv:KknSXpUPRviOWDU0S3/NbjoUPvEQFew3waHZ8rdZsQw=,tag:ijV0rMyhmsaSS1uyInSDZQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
