apiVersion: v1
data:
    ADMIN_EMAIL: ENC[AES256_GCM,data:Dx6Bbrb8C4Rd3YSqgBSX5ueKjgz1vhTNLRYflg==,iv:a/NyYa3Ieyn22fyKJdo0YVoXrrNpqhwY5ofBtYeyF/M=,tag:9sGM8Pd5sKHTYVESBVvv4g==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:vMx2R7vRRzW2c4Np,iv:TCp7gUfHBssFo37/4zqd/1uZzHMN7NcFIkKSjVQfYiY=,tag:+ratBFLdsobVq3i3CulBZA==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:L1AI2wjAiBezcNa03ndXgEvXwschh5paJOmafrqlFlFNvgXDOyV+XeedEYt2EM4QuYUitwv7lySxQgnD7df26urzslv8ylSjIbmz+E5iVhdRppi9QvgUSgjMjqk8jveWlqhmAD6f8iC/C1Gs0+SRT86ug1UBb5tq,iv:yjzCCGH/aNhvY4S4HMhgR7H9Rv4yTDTrRvfwyUYaY6k=,tag:8L4m8SGbr4qSthQF8+lQfA==,type:str]
    FRONTEND_ORIGIN: ENC[AES256_GCM,data:FK3LviaQqI2K9qfOw0ZgdXiJwwd/lB0AMev8FA==,iv:oQ6W2UK5h/TZ8skX9VA7JrAbo03dKLKkmlx0XnApVss=,tag:fFL3EjZL3BFe2fT+Kd4ZrA==,type:str]
    GARDENERS_SERVICE_URL: ENC[AES256_GCM,data:GM2qXCOxpMBgVeKm/Mjp60V0iOm5tKNF5liYUQ==,iv:mi4j86hTk24H4SA5GeFL6pDFWJdR7Kn8+X6UV9QwU78=,tag:h6jr/s2Y326O0Mjk+7OKdQ==,type:str]
    INTERNAL_SERVICE_SECRET: ENC[AES256_GCM,data:RnfU+uNM0wlN4O0YSfXok88aP6IXNoEoPgNTJQ==,iv:d9Lg6W0ZRH5SZCN8QVRLjcrh0ycDwSlJYnUJhhkFE2s=,tag:iuFNU5pNmcW6t+jq6A8Rkg==,type:str]
    JWT_ACC_EXPIRES_IN: ENC[AES256_GCM,data:A5T9Ag==,iv:mxijrki7WLRj1EYilYbbaYek9N5gyNqx5Wef6gtEaIY=,tag:7DqQvchMtaihbgX3LuuZwA==,type:str]
    JWT_ACC_SECRECT: ENC[AES256_GCM,data:L5y15QQEZW6W5ueG,iv:nz52xtH3iQvIHAH+3x1V8T7SxtxGmL/U9VYRmJtNdeA=,tag:a6tPFrCNJa0Cl7RVnL5MDg==,type:str]
    JWT_REF_EXPIRES_IN: ENC[AES256_GCM,data:G4QkBw==,iv:bT8AvWvcZqttFweKBtdRpMo3XVm6XQBAi2iyGE6pLU0=,tag:00IKXX1gmhcMb/rIXpT3Tw==,type:str]
    JWT_REF_SECRECT: ENC[AES256_GCM,data:DTgwAz1rqZ8+P9F5,iv:xayD01i2u0nUcEIYQ65alD8XC8T8smbFxiDVmRUSGlY=,tag:H7abVYugjwy0nTQJ0COTbA==,type:str]
    PORT: ENC[AES256_GCM,data:qEqSTrXaXTk=,iv:32YpkqxmyjjYehLNTAkd6pMFhq3Huw1xMkMTOMxcVt0=,tag:xieJjJCYVBWczZGAhzQr3g==,type:str]
    PgSql_Database: ENC[AES256_GCM,data:3sj3BoR/WPj+HKKVT5kM5Q==,iv:NkdU20Qrbs6O+3BP6nMoZRX+7e5aqy4tVLCqc1Il3oo=,tag:PhI4nR2EHE8G558Aw5YhsQ==,type:str]
    PgSql_Password: ENC[AES256_GCM,data:RNVw9zRu7gS/sz8EYzNyMQ==,iv:/Y5uz6kBn81+TXKFemXF9g19oNKRNl5HrdF68jLSxUI=,tag:CznZ9I7DLXdojkFbx+TD8w==,type:str]
    PgSql_User: ENC[AES256_GCM,data:gni1Ofb5PNbrN1qlHoCgWA==,iv:gjENsJXu/5kEydTfd2NhZxody6dEtLesGbYVhinnwjk=,tag:6nMc3l9LBIjeMbGinkj76Q==,type:str]
kind: Secret
metadata:
    name: visitor-services-secrets
    namespace: bonsai-dev
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g2lray3jp4plrwd6x2uzhk2gq563kcshuc0xy962e4kzkg9789gsdrlenq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBseTFTVUlDNGpuYk1LYXNR
            bEJ2YWdpaG1kVWtwMjNCM0xqcGVLZHVpeGc0Cm5DQitPcmRLV2c2a3Y0Wkp5WHp0
            MVZsTVpRVlMxbmNrbmlyNnVjdDN3WTAKLS0tIGJjUlpRRHM5K0VJM3dUV282Q2RL
            YTltTytEUE9IN3RZQ1dPRmp4ZGh5UDAKia58esU7Vo3XjG69g9qboSY9IiFc5FD1
            S9G/9tGgptG0XApggPXBmnE+PJLLTiPYgSOnF8KZ991AHojDxHqmkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-06T14:10:52Z"
    mac: ENC[AES256_GCM,data:tzu6elFC98OgzYY6a2gEmneQocbHCDsVodjEfHFVlxcNs6LFW6uRw9phx4rDeO+Y+XR8m1xzQDSevqJiezxDPM3ouclKK2rBQ9cL4qBdlWmBimM6KxHSFMa7NXmCtCas4NfpB+9a8GlWZXRlsbylC+Sg9PTVRKUeksCXUQO5oCg=,iv:t8LCPpU3ZTehqub0NLIg36FEM2aV0MLEBUI0U6MRQ3k=,tag:8dnb3qXt9CQdXCFBLPkT5w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
