apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "bonsai-observability.fullname" . }}-grafana-secrets
  labels:
  {{- include "bonsai-observability.labels" . | nindent 4 }}
spec:
  encryptedData:
    GF_SECURITY_ADMIN_PASSWORD: AgBIJ5jDcfGoZm1gA6uSVVjNvjiBamKvXqbYKA94ySzTsihqTf0QF6emJyWBajUWjxp51NwvZFqZd4NUtuY9nXoCkxVNOolyvCOwd27yUmEtERnm7oghZxSmEQJIl2rK4/3d9nx2CDh0XzD6iZwXSgU6Wl+oE/Kebmuw/NlFJLSQ+LgXSnBs9W0XR/gQrYutvKZQn+LdjRmnLdq/EVOqngtuABE9TatoiiagAd0HCKv0h6G4qqKwjQcdjHNcU47UG6EBl1fw6fCx54shZL8U3zBgaASzIrrp8gipkOr4OGfcPQ0ZMTyHskZeGRbhcvVv+FttSk/d3SRYjhgcWc5tsts/3LYjlzRyyc5kh+NrFC3w35+RvIQNK3SAsIRCMkj40YhNhz7+mNB5lADf/9dfHpes4LQ7UI063N3Mei3Tf5xE9lGlGvh7l2Oz4kCZjPXnIlpcva6EuI5tNbDutAjvSgvHURqcL4LXUW4OoiAbCwPGqhdNexZzJrkSXc6LiYSxwdhVYtc+r13YzZCK2Mvn1LzR7cBAYsaLcUU9ZOSdWtrfEYefXNMTEcHDAM1P/gCugLwkJC+HHlDu459izsh1z1uzAvxYupLSMdBl6WZYQpqyOyLgjk8aOyl8QIuiBJCNtkP36184yQ1EEHP/M8hNFv2eXdpYx90c2Ff35zsWzlqv1noiyOT2NpiZugViIBiB3tvmWDM4MUJgGW7R+aLdBL75
  template:
    metadata:
      creationTimestamp: null
      name: grafana-secrets
      namespace: bonsai
