apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "bonsai-observability.fullname" . }}-grafana-data
  labels:
  {{- include "bonsai-observability.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.grafanaData.storageRequest | quote }}
