apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "bonsai-observability.fullname" . }}-loki-htpasswd
  labels:
  {{- include "bonsai-observability.labels" . | nindent 4 }}
spec:
  encryptedData:
    loki-htpasswd: AgBocRW+jVPu/HjBjekqiMQzZtMfWmlE4QsWiC8hRMO6lFlLkkjK76HJO5l3WiwVZVW7UPd2ep835rQzIBO26YPKJgwPV0CzqNU8wg1S6AAMdfVtlAxsCTUdI/2xw3glBgK+h87hR63h4+T/0uuLtjtGcdh+/UnEuPREZ72/xs1IlrY1D8sITXzUd2ZXRVJTGKN7G4eK+Jgegd9IR0Qw2hDo3qaHRSGclOkRP6soTsqX7H+MFpwUhIJ2nzQfM1tTsVmuh1zbFOFlEoXiXNvraY2CHiBxxV65nKCDzauDIRO+WBG9WzV0YlUuVtwP1yM3M8Dq8/vIxzuC0mM/vM/YMF6AKQ1CeCGeO0ToJqTTyfNKmF+2ZNV6gCN3R4kWx0d+v77LmDMLy0QRfJoSC0ryRuF4pAg8NbyVrByXEMHgqiW5U7TmhK+HMRBwMyhWqWAfxmY2FyzDgjLDK1yF4K1w4BCvdw6ZlgBqlDqITL/Bwym7hq0+BoAdR7hx4e94ubVulyU/Kc3e1sH6DEnOJCKkzyriFR1KkQymU2J7wocY+tHa6QNgiJa11tJsDBDwmR7/R0QMBCpYrBPt5hT97FyyvCojT1dq7F+vbCSZXmWIGiOysvJQBdDkmMhO7Fi2kPaFT7Lp2h2vKdoUmzsDgxHFMkDwp6sHoDHetWLwMJ6rC+3lxBtIGOfGsqHR7ZMhiCrCG9l/6Epttc7y1lNQI8x3ae5XvrX6MJcPyunkO1fdBVSIUOyo6kvbNmeIGJRW05ojbrM=
  template:
    metadata:
      creationTimestamp: null
      name: loki-htpasswd
      namespace: bonsai
