apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "bonsai-observability.fullname" . }}-prometheus-web-creds
  labels:
  {{- include "bonsai-observability.labels" . | nindent 4 }}
spec:
  encryptedData:
    PROM_PASSWORD: AgBqvU3QDwmEsmCx86g8kKYIcfcw/GkBZn8WYe48/F9emECYVCb/mTMXkuNG1WZBvoVskmZdrqaNDDH3qwyvbyBoERbfOc2XAsIKiGxfqnrIvEVyiRQ2GiNk15Z408o1b2hSQ3ro1TL9Bb0EK6sNjZT3IhAFv44o4VCzy+SDNgBIILOoAh4AQ+QmH3wYvBOwTZmDhFiTCWwJGTYMmD2Fl+Syj7TU2Smm0YCo5OLMhsk6+WBGBPzrXxxsmq6C7KDEnisOmwrcLQklVzO1c4hjqF0TC5jEyfULieMMIZgRqHoofBQbzJPjGPuBrpqKx3CYremDG03fgeOsYrqHaVA0uOrI9n2H5M9JU1JJIOxzgBPyLAelABKEcUlIpmKbCjsJIycWAPDkHH+FgQublUgmU8BuArxGMiMzexAYmOEVKn9KVNY1/myh1ZSOGG6rThn5x9uiKOMyu6vn7GtneP/bRY28Sxjs8YYsu6SeYspvCMn8AbVBmkaGbX1sBxSouxSJwStMdMrC+FtGSqNBb5sC/wO/e20SPQc43ZeKKjF3K7M+aeqcoXyZ1vlTLV8b6eTfKmKKcRmYq1F2f+82wIype3LaUzYUsuD+wyGBaGuLB3l6XwbjQeoBMLGW+nxgGnGksNbSYblifoI9MplVERfuu+u5qGF1QmrbmTn8+BOCO7qAkeXlzQR3/Xs/yoDl/JC8TAjgnS/Ipw3MzTOSobw8FROM
    PROM_USER: AgASfmtynHy8AHjtPSw7doW4XYu5lUVfS1shTBNaFew7uWnJvjWhdA6ohNTpRdkN9TkDTQuNl+hwXP0YMGBexH09+03i4tAHKRmYHV3edEoSUH2x/ke5q6DbSkzQGONDdIk/f2ChLmgs3jrAvTCX/lDkVkmNLE6mcUmTgfNdHHEB3Swo/JnsW/5CrUaDS9S70nzhebn/BtXTiYyoAvzSC2NT0vtPD0W66aZi/7zPHousiNrGdAHpvO3baYBOP/bCC8nkyJ5Q5A/RSt2Mhqsdo7EcNZ8loRjJ4JL7w+5a0wAVPTGAMlh4o76eMxW2FGA1GEQAeC79wn/kG3KjMaipFOHHdohXoflAWJY6KizpDnOl3c4cx3Flq6OuUlakdRxJiU5P1wGWAVUDpmx9hWtEgopCxRJe5DfIhzfKLplB2CycYV4PCE/S1YG8evRmnrUm+0CWdsGICej9hb3lhCE84zPDbjz1IE7+yzncR79qaocbjx6Rh37lMpvDo7JVicgfgR/38HI7pdCiWI596npadQ/a7vE53uiNh/V4S7sWC9NfusQcy0ujuUhDaS7D0lRckamAKNuH6jlCSERGeGEHvBU6X9FkLDMjOcepK4bAGGyp2V+3oWkObSPmHyWr4VxGxBKe+uMZFVwEm3lmgm4IIUvCIzkpQ1+8ajKDYxuE8Tlcf5ZmirXUGCo/3LEahzbsplJeWKEmtQ==
  template:
    metadata:
      creationTimestamp: null
      name: prometheus-web-creds
      namespace: bonsai
