apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bonsai-observability.fullname" . }}-promtail-config-gc5hfh8628
  labels:
  {{- include "bonsai-observability.labels" . | nindent 4 }}
data:
  promtail-config.yml: {{ .Values.promtailConfigGc5Hfh8628.promtailConfigYml | toYaml
    | indent 1 }}
