apiVersion: v1
kind: Service
metadata:
  name: {{ include "bonsai-observability.fullname" . }}-prometheus
  labels:
    io.kompose.service: prometheus
  {{- include "bonsai-observability.labels" . | nindent 4 }}
  annotations:
    kompose.cmd: kompose convert -f observability-compose.yml -o k8s/observability/
    kompose.version: 1.31.2 (a92241f79)
spec:
  type: {{ .Values.prometheus.type }}
  selector:
    io.kompose.service: prometheus
    {{- include "bonsai-observability.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.prometheus.ports | toYaml | nindent 2 }}
